### ISSUE TITLE
idea/wish: copy/clone input

### ISSUE THREAD

**Issue by mrfreezer** [Graylog2/collector-sidecar#10]
if you have to define several rather similar inputs for a collector a clone (or copy) button would be nice.
i know there are wildcards but sometimes this simply does not cut the mustard.

### Environment

* Sidecar Version:  0.5.0
* Graylog Version: 2.0.0 rc1

**Comment by mariussturm** [comment]
This is implemented with this commit: 9df9c47207676d866e13fc5fcc29bdefa6876511

**Comment by mrfreezer** [comment]
thanks. i hope others are going to benefit from this as well :)
