### ISSUE TITLE
Multiple configurations per host

### ISSUE THREAD

**Issue by joakimberglund** [Graylog2/collector-sidecar#100]
### Problem description
If one configures multiple configurations for one host it merges the configuration to one instance which can override or collide with eachother. Ex using one graylog input for one set of log files and a another for other log files.

### Steps to reproduce the problem

1. create a configuration that follows logfile1 and as output uses output localhost:5044
2. create another configuration that follows logfile2 and as output uses output localhost:5043

One of those outputs are lost if one checks the resulting configuration on the host.

### Suggestion

1. use the configuration name from graylog to create a config with that name on the host.
2. Since the graylog-collector-sidecar process spawns the filebeat process itself, spawn one instance of filebeat for each configuration file.

**Comment by mariussturm** [comment]
Hi,
the behavior your describe is by intention. The idea is to be able to decompose the collector configuration, e.g. one with outputs only one with inputs and then merge them via tags. We are not there but the goal is to reduce the collisions.
What you are trying, can be achieved by adding a static field to a file input and then assign the messages with the given field to a special stream in Graylog. No need to seperate on the input level.
