### ISSUE TITLE
support for metricbeat?

### ISSUE THREAD

**Issue by rompic** [Graylog2/collector-sidecar#103]
### Problem description
It would be great if sidecar could support additional beats like metricbeat.

### Steps to reproduce the problem

1. ...

### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
* Elasticsearch Version:
* MongoDB Version:

**Comment by joschi** [comment]
Refs Graylog2/graylog-plugin-beats#19
Refs #69

**Comment by SwagMuffinMcYoloPants** [comment]
Any idea when this is targetted?

**Comment by reighnman** [comment]
Bump -

**Comment by mpfz0r** [comment]
The new Sidecars in 3.0 will be using a more generic approach:
You can define your own collectors and manage their configuration in plain text.
Setting up metricbeat shouldn't be a problem then.
