### ISSUE TITLE
Support few variable in sidecar config file

### ISSUE THREAD

**Issue by thomasegis** [Graylog2/collector-sidecar#106]
Hello there,

It could be handy to be able the variable such as the hostname in the collector_sidecar.yml file, for instance :
node_id: ${HOSTNAME}

### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
* Elasticsearch Version:
* MongoDB Version:

**Comment by mariussturm** [comment]
Hi,
you can leave the the node_id blank and the Sidecar will fall back to the hostname automatocally. Let me know if there are more use cases.
