### ISSUE TITLE
idea/wish: configure log rotation via sidecar

### ISSUE THREAD

**Issue by mrfreezer** [Graylog2/collector-sidecar#11]
as far as i am aware nxlog comes with its own log rotation engine. wouldn't it be nice if one could configure this via the sidecar?

### Environment

* Sidecar Version: 0.5.0
* Graylog Version: 2.0.0 rc1

**Comment by ion9** [comment]
Cant you do this with Snippets

Snippets can be used to represent more complicated collector configurations. Simply paste the whole content of your NXlog configuration into a snippet or use it as an extension to the inputs and outputs defined before. All snippets will be copied directly to the generated collector configuration, no matter if there inputs or outputs defined.

```
<Extension logrotate>
      Module  xm_fileop
      <Schedule>
             When    @daily
              Exec    file_cycle('/var/log/nxlog/nxlog.log', 7);
              Exec    file_cycle('/var/nxlog/message.log', 7);
      </Schedule>
</Extension>
```

**Comment by mariussturm** [comment]
We have added this to the `nxlog-default` snippet. So with a new configuration the nxlog log file will be rotated once a day. If you need other settings you can click on `Edit` next to the snippet. You can also add more files there. This will be released with the next version of the collector-plugin.

**Comment by mrfreezer** [comment]
ok, my idea, which i obviously didn't describe exactly enough was to define this inside the input definition. since maintaining this seperately inside a snippet means twice the works plus more possibilities for mistakes - which means even more work :-D

**Comment by mariussturm** [comment]
I looked into this but there are way too many options to make this configurable through a proper UI. You can add all kinds of conditions and schedulers, there are about 30 different options just for the xm_fileop module. So I think the best way is to edit this manually in a snippet.
