### ISSUE TITLE
cannot install nxlog on CentOS 7.2

### ISSUE THREAD

**Issue by appop** [Graylog2/collector-sidecar#110]
### Problem description
rpm -ivh /tmp/nxlog-ce-2.9.1716-1_rhel6.x86_64.rpm
error: Failed dependencies:
	libpcre.so.0()(64bit) is needed by nxlog-ce-2.9.1716-1.x86_64

### Steps to reproduce the problem
even I link 
/usr/lib64/libpcre.so.1.2.0 to /usr/lib64/libpcre.so.0
But this don't work 
Is there an workaround ?

1. ...

### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
* Elasticsearch Version:
* MongoDB Version:

**Comment by appop** [comment]
Hi  I use filebeat to instand

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
