### ISSUE TITLE
common/logger_unix.go:48: undefined: rotatelogs.NewRotateLogs

### ISSUE THREAD

**Issue by kira8565** [Graylog2/collector-sidecar#113]
### Problem description
 I Build collector-sidecar on my mac,and build fail ,here is the message

```
go build -ldflags "-s -X github.com/Graylog2/collector-sidecar/common.GitRevision=a93cad9" -v -i -o graylog-collector-sidecar
github.com/Graylog2/collector-sidecar/common
# github.com/Graylog2/collector-sidecar/common
common/logger_unix.go:48: undefined: rotatelogs.NewRotateLogs
make: *** [build] Error 2

```
### Steps to reproduce the problem
1. make build
### Environment

* Sidecar Version: master
* Graylog Version: 2.1.0
* Operating System: osx
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.1

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by shimengwang** [comment]
I have this problem when compile the source code， How did you sloved this proble？ 
Environment：
go 1.9
Ubuntu 16.04
