### ISSUE TITLE
add cpu and memory usage to monitor the agent

### ISSUE THREAD

**Issue by kira8565** [Graylog2/collector-sidecar#115]
### Problem description

Recommended in the collector-sidecar of nxlog and filebeat collection of CPU and memory usage indicators, on the one hand we can better observe the Agent on client resource consumption, on the other hand, we can restart or shutdown the agent when they use too large resources by collector-sidecar

### Steps to reproduce the problem

1. ...

### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
* Elasticsearch Version:
* MongoDB Version:

**Comment by mariussturm** [comment]
When you click on a (linux) collector in the collectors overview page you can see some metrics which should help the administrator to identify broken hosts. You can see CPU Idle, Load and disk volumes witch are about to run full. Is this what you are looking for?

**Comment by kira8565** [comment]
not at all.
Because of the operation and maintenance personnel, use of agent resources is a sensitive issue, if the agent use too many resources , may be  complaints, or cause it is difficult to spread out, so to be able to collect the performance  of nxlog or beat is also very useful. i tried because the regular configuration of nxlog with incorrect result nxlog takes up too much memory, so i think agent control is very valuable



Marius Sturm <notifications@github.com>编写：

**Comment by mariussturm** [comment]
Sorry, I didn't got what the actuall feature request is. Do you want to see the used resources of a backend (nxlog/beat) in the web interface like cpu and memory? Or do you want the sidecar to limit the resources of a backend?

**Comment by kira8565** [comment]
yes,there are two feature i request,one is  see the used resources of a backend (nxlog/beat) in the web interface like cpu and memory,the other one is want the sidecar to limit the resources of a backend

**Comment by mariussturm** [comment]
Ok, got it. After looking into this a little bit I think this is not easily doable. I couldn't find a portable way of managing process resources on Linux and Windows in a proper way. For Linux there are a couple of possibilities like ulimit or cgroups but for Windows I could only find the JobObjects API which is not supported by the Go language of the time of writing (correct me if I am wrong).
Till there is a common go library for doing this I would recommend to leave this task to the operating system. You can edit the start script and set ulimits or start the Sidecar process in a limited Cgroup, that should solve your problems.

If someone knows a good solution to this, shoot us a message or even better a PR!

**Comment by jalogisch** [comment]
closing this for now. 

If in the future the ecosystem give us better and easier integration we might look again.

**Comment by tuxknight** [comment]
Hi，may be it time to consider it  again. Filebeat can expose internal metrics through an HTTP endpoint. 
https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
