### ISSUE TITLE
Evaluate the use on Desktop machines especially macOS

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/collector-sidecar#119]
### Problem description
For managed desktop environments it could make sense to deploy the Sidecar. Open questions are
 - How to create packages (.dmg)
 - How to handle longer server timeouts (travelling Laptops)
 - Changing networks (Road warrior)
 - Which control functions do the end user need? Which the admin?
 - Resource limitations

**Comment by jabenninghoff** [comment]
FWIW, I've created a homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/collector-sidecar.rb) for macOS and successfully implemented collector-sidecar on macOS in a test environment.

**Comment by scottcc** [comment]
Also can confirm that I've recently installed using the above homebrew recipe on a 10.16.6 headless mac mini, and it's happily shipping events using filebeat, FWIW.
