### ISSUE TITLE
include 

### ISSUE THREAD

**Issue by ion9** [Graylog2/collector-sidecar#12]
### Problem description

It would be nice to be able to include spinets in the inputs in graylog. like i show below, that way get can pull out some basic info like timestamps to start with.

### example config
```
<Input in>
        Module  im_file
        File    "C:\\tmp\\\\example-log.txt"
        SavePos  TRUE
        Recursive TRUE
        InputType       multiline
        exec if $raw_event =~ /(?:\{"([0-9]+?), ([0-9]+?), "(.+?)", "(.+?)", "(?:.+?)","(.+?)\n(?:[a-zA-Z0-9:,"\n\r\s\f\t\-\{\}\.\(\)]+?)New\sLogon:\s*(?:.+?)\n\s*Account\sName:\s*(.+?)\n(?:[a-zA-Z0-9:,"\n\r\s\f\t\-\{\}\.\(\)]+?)Source\sNetwork\sAddress:\s*([0-9\.]{7,15})\n(?:[a-zA-Z0-9:,"\n\r\s\f\t\-\{\}\.\(\)]+?)"\})/g; 
     
    $timestamp = $1; 
    $event = $2; 
    $status = $3; 
    $type = $4; 
    $short = $5; 
    $user = $6; 
    $source = $7; 
    
</Input>
```

**Comment by mariussturm** [comment]
Please take a look at Graylog's extractors, they are made for exactly doing this in a more performant way: http://docs.graylog.org/en/2.0/pages/extractors.html

However, this is a little bit tricky. We have to keep the balance between exposing the needed configuration options for the collectors and getting a simple intuitive web ui. This request seams to me a little bit too complicated to understand for users. So I would keep the Sidecar simple and use Graylog's build in functionality for this use case.

**Comment by allangood** [comment]
Sorry for reopen this old thread,

But I need to agree with ion9. There's many use cases for this suggestion, let me try to enumerate:
1) Logs from MS SQL Server. They are encoded as UTF-16LE and before send it to Graylog, NXLog need to convert it with:
Exec    $Event = convert($raw_event,"UTF-16LE","UTF-8"); to_json();
Inside <INPUT> section. For now, collector-sidecar is incompatible with MSSQL.

2) Try to fetch and parse W3C (IIS) logs, this will result in many missing lines.
A line like this:
InputType  w3c_parser
Inside <INPUT> section will solve the problem.

These are only two examples.
My suggestion is to split "snippets into two: "configuration snippet" and "input snippet"

Regards.

**Comment by mariussturm** [comment]
@allangood at the bottom of the Input configuration is a `Add verbatim configuration` field. That should do what you are looking for.

**Comment by allangood** [comment]
Thank you mariussturm!
I didn't notice that "Add verbatim configuration" will add code inside the <INPUT> tag.
This works perfectly for my needs and I believe is flexible enough for most of cases!

Thank you again!
