### ISSUE TITLE
winlogbeat renames gl2_source_collector

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/collector-sidecar#127]
### Problem description

Using the latest (0.1.0-beta.2) beta of 0.1 no messages are shown when search for `gl_source_collector:collector_id` but the field `winlogbeat_gl2_source_collector` is present, holding the collector-id.
This happens when only using winlogbeat on win 10.  

### Steps to reproduce the problem

1. install sidecar 
2. configure winlogbeat 
3. disable filebeat

### Environment

* Sidecar Version: 0.1.0-beta.2
* Graylog Version: 2.1.2

**Comment by bernd** [comment]
This is already fixed in the master branch. I guess @mariussturm should release a new sidecar beta. :smile:

**Comment by mariussturm** [comment]
@jalogisch could you please test again with beta.3? https://github.com/Graylog2/collector-sidecar/releases/tag/0.1.0-beta.3

**Comment by jalogisch** [comment]
this still happens with the latest beta (using winbeat)

**Comment by bernd** [comment]
> this still happens with the latest beta (using winbeat)

You have to use at least winlogbeat 5.x for it to work.

**Comment by jalogisch** [comment]
i use the bundled version so it should have the latest winlogbeat

**Comment by bernd** [comment]
Okay, it worked for me so we have to investigate. /cc @mariussturm

**Comment by bernd** [comment]
@jalogisch Which Graylog server version are you using?

**Comment by jalogisch** [comment]
2.1.2

**Comment by joschi** [comment]
@jalogisch I'm not sure this is supposed to work with Graylog 2.1.x.

Also make sure that you're using the latest Beats input plugin.

**Comment by mariussturm** [comment]
@jalogisch @joschi you need to run Graylog beta.4 or at least the latest Beats plugin to get this working.

**Comment by mariussturm** [comment]
Can this be closed?

**Comment by jalogisch** [comment]
ok 
* install beats plugin: https://github.com/Graylog2/graylog-plugin-beats/releases/download/1.1.4/graylog-plugin-beats-1.1.4.jar (remove 1.1.3) 
* used latest collector: 0.1.0-beta.3

noticed that some messages had  _winlogbeat_version **3**_ and some have **5** set. 

as I did update the collector from 0.1.0-beta.2 without removing, I cleaned the windows part, reboot and did a fresh installation of beta.3

then this was fixed and working with graylog 2.1!
