### ISSUE TITLE
Feature: Extra input fields 

### ISSUE THREAD

**Issue by joshrp** [Graylog2/collector-sidecar#13]
Thankfully the `Filename` field was added in the release the other day, very useful, but it would be very nice to be able to add other arbitrary fields to an input to be able to tell them apart. 

There's currently very little to be able to tell where messages came from, other than maintaining a all messages per host, and knowing what they do. Things like Application Name and Environment would save a lot of time and custom configuration.

**Comment by mariussturm** [comment]
You mean like static tags?, e.g. ApplicationName: loginservice

**Comment by joshrp** [comment]
I think you're referring to tags in the collector for targeting configurations?

I'm talking about sending extra fields back to Graylog to help identify different files and servers easier which would look like `Exec $application_name = "app_name";` or similar in NXLog. 

Having a way to define these along side the Input/Output of a collector configuration would be really useful, as the NXLog config files obviously can't be configured manually. The custom spec files also don't really help here as you can't extend the Output or Input blocks, the extra fields must be defined inside them.

**Comment by mariussturm** [comment]
Ok got it, sounds good. Will add this to the backlog.

Thanks!

**Comment by mariussturm** [comment]
This is implemented in https://github.com/Graylog2/graylog-plugin-collector/commit/be22699ef5d8c0ec6b392d297640b1b1f4c62abc You can update the collector plugin separately or wait till the feauture is available in the normal Graylog release.
