### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by kwisatz** [Graylog2/collector-sidecar#132]
I don't claim to have any prior experience in how one approaches these things, but I was wondering whether there were possibilities to change or adapt the versioning scheme used for packages and releases?

I've built the graylog-sidecar-collector puppet module over at https://github.com/tentwentyfour/puppet-graylog-collector-sidecar and am struggling with your versioning scheme. OK, you could say one probably shouldn't be using a package while it says **beta** anyway ;)

Anyways, I'm splitting up a package version string such as **0.1.0-beta.3** as follows: 

```
$version_parts = "${package_version}".match(/(\d)\.(\d)\.(\d)(-+.*)/)
```

Now I'm using them to build the URL to the actual package, which differs in format, e.g. for Debian:

_https://github.com/Graylog2/collector-sidecar/releases/download/${major_version}.${minor_version}.${patch_level}${extra_level}/collector-sidecar_${major_version}.${minor_version}-${patch_level}_${::architecture}.deb_

And I'm not even sure, is -${patch-level} in the package name actually the patch level or does it refer to something else?

So that's all OK, but now the hard part. I cannot 

```
package {
  ensure => ${package_version},
}
```

because the package version for all beta releases is 0.1.0-1 (yet another format ;)). 

So even when users would bump the $package_version variable, puppet's apt resource would not attempt to reinstall the package and I have no way of figuring out which version is actually installed. (beta.2, beta.3?)

What is your opinion on this?

**Comment by mariussturm** [comment]
I have the same problem for the Chef cookbook and it's already on my list. Will take a look!

**Comment by kwisatz** [comment]
Great thanks!

**Comment by mariussturm** [comment]
With RC.1 we have introduced versioned packages. The version suffix is now also reflected by the `-version` switch. We use the same schema like we the Graylog server packages. E.g. `0.1.0-1.rc1` stripped to pieces: `0.1.0` - major,minor,patch version of the Sidecar. `-1` is the package build iteration (gets bumped when the package is rebuild without a software change). `.rc1` is the version suffix added for pre-releases (empty for full releases). In that way systems like apt or rpm detect an package update when we bump from `-beta.1` to `-beta.2` for example.
