### ISSUE TITLE
need systemd for ubuntu 16 - upstart error / not present on ubunutu 16

### ISSUE THREAD

**Issue by dejannenov** [Graylog2/collector-sidecar#137]
### Problem description

when executing  sudo start collector-sidecar on ubuntu 16.0.4 LTS upstart is not present and we get start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

### Steps to reproduce the problem

1. Follow sidecar installation on Ubuntu 16.0.4

### Environment

* Sidecar Version: collector-sidecar_0.1.0-1.rc.1_amd64.deb
* Graylog Version: Graylog v2.1.3+040d371
* Operating System: Ubuntu 16.0.4 LTS
* Elasticsearch Version: 
{
  "name" : "Bloodshed",
  "cluster_name" : "graylog",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

* MongoDB Version:

db version v3.2.5
git version: 34e65e5383f7ea1726332cb175b73077ec4a1b02
allocator: tcmalloc
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64

**Comment by mariussturm** [comment]
Thanks for the report,
on Ubuntu 16.04 Systemd is used for service control. You can start the Sidecar daemon with:
`sudo systemctl start collector-sidecar`
I have added that to the documentation.
