### ISSUE TITLE
Ignoring "tail" flag after configuration update (Beats)

### ISSUE THREAD

**Issue by tehpanta** [Graylog2/collector-sidecar#138]
### Problem description
After I edit configuration of a collector set (for example I add a new file for filebeat), the sidecar will notice this change and reloads configuration of the whole filebeat and ignores the tail flag (ie. starts loading whole logfiles to graylog server, creating duplicities and overloading the whole server).

The "tail" flag works fine otherwise. It just ignores it after update to configuration.

### Steps to reproduce the problem

1. Have N already configured and working (50 in my case) filebeat inputs in one configuration.
2. Leave sidecar running and working.
3. Add one more filebeat input (even a small file) 

### Environment

* Sidecar Version: 0.0.9 / 0.1.0
* Graylog Version: 2.2 RC1
* Operating System: Redhat Linux 6/7
* Elasticsearch Version: 2.2
* MongoDB Version: -

**Comment by mariussturm** [comment]
Hi, thanks for reporting!
Could you please share the sidecar configuration before and after the breaking change, with: `mongoexport -h <MongoDB IP> -d graylog -c collector_configurations --pretty -o collector_configurations.json`

**Comment by mariussturm** [comment]
We plan to implement #200 and #201 in Graylog 3.0.0. This issue will become obsolete by then, so closing it for now.
