### ISSUE TITLE
NXLog Hostname

### ISSUE THREAD

**Issue by joshrp** [Graylog2/collector-sidecar#14]
This may be related and could be solved by #13 but may need it's own solution.

Currenlty NXLog uses a short hostname when reporting which **I am assuming** gets used as the Source field in graylog, this is causing me some problems as the short hostnames are not unique across all my collectors. I currently can't see a way to work around it. NXLog does not let you configure this as a global option and suggests you override it by setting `Exec $hostname...` but as described in #13, I can't affect the content in these blocks. 

It may be worth having a "snippets" section that will be included in each input for fields that you want to include in all. 

A short term solution could be to just place `Exec $Hostname = hostname_fqdn();` in all inputs, which I think should be the default anyway.

**Comment by mariussturm** [comment]
Hi,
thanks for the feedback!
I have added the `$Hostname = hostname_fqdn()` solution to version 0.0.6. Think thats a sane default.

Having a snippet section for every input is not so easy from a UI perspective, you easily overload the form with too many options. Let's see if we can distil it to a option set that works in 90% of the use cases.

**Comment by joshrp** [comment]
I was going to suggest something a little lower level maybe in the collector YAML config itself. If I could place fields in there for things like application name, environment, region etc. this file is already user controlled and is per server rather than per collector configuration.
