### ISSUE TITLE
REST communication should be better secured

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/collector-sidecar#141]
### Problem description
The communication between the Sidecar and the Graylog server is not as good secured as it could be.
A mechanism based on certificates or a pre-shared key would improve this. We need to design this and create the infrastructure for this. Ideally this will not make the installation of the Sidecar much more complicated

**Comment by eric-tucker** [comment]
Generally speaking, is this item covering the fact that any sidecar can register with Graylog without needing to authenticate and that the APIs for sidecar are wide open?

I don't know why someone would want to register their random server with my Graylog instance but it shouldn't be allowed.

**Comment by bernd** [comment]
This will be implemented in the upcoming 3.0 release.
