### ISSUE TITLE
Configuring JSON input in NXLog

### ISSUE THREAD

**Issue by Svolentin** [Graylog2/collector-sidecar#144]
NXLog can act as gelf relay by receiving plain json messages and send it to graylog. But Collector Sidecar can't configure json handler, but it would be very useful to send rich json logs from app directly to localhost nxlog , configured via sidecar.

**Comment by joschi** [comment]
@Svolentin This should be possible by using snippets.

Maybe you can elaborate a little more on your usecase and the necessary configuration settings.

**Comment by Svolentin** [comment]
@joschi in production we use several Graylog servers, so one or more of them can go down. in this case we must use TCP instead of UDP. Sending data via TCP consume resources from app, but 'fire and forget' is the best way for logging. 

in this case a good idea to have middleware like NXLog which receive, aggregate and sequentially sends logs to right graylog node, but nxlog configured via sidecar, can be configured to eat logs from:
- file
- udp syslog 
- tcp syslog 
![screen shot 2017-02-17 at 13 30 25](https://cloud.githubusercontent.com/assets/325606/23062049/4da45930-f515-11e6-98a9-29994d4189f9.png)
In this usecase we must choose between three bad variants:
- sending via gelf_tcp: guaranteed delivery via tcp but additional load in app, rich log message;
- sending via gelf_udp: no additional network handling in app, rich message, delivery not guaranteed.
- sending via NXLog with any type of it can eat: localsyslog or from file = always plaintext message, no additional handling in app, guaranteed delivery.

so we need graylog relay for localhost which receive json via udp locally and next sends it to graylog via tcp.

**Comment by jalogisch** [comment]
@Svolentin as @joschi already written, this can be solved using snippets for nxlog.

your use case is not very common and will not be solved by drop-down-menu.
