### ISSUE TITLE
yml file on Windows version 0.1.0-rc.2

### ISSUE THREAD

**Issue by christianmarangoni** [Graylog2/collector-sidecar#149]
### Problem description
When you install the  0.1.0-rc.2 on windows the url and tags are not inserted in collector_sidecar.yml file
### Steps to reproduce the problem

1. install graylog sidecar to windows
2. in the wizard insert url & tag
3. end the wizard installation
4. check the collector_sidecar.yml

### Environment

* Sidecar Version: 0.1.0-rc.2
* Graylog Version: 2.2.0
* Operating System: windows 2003/08 64 bit
* Elasticsearch Version: 
* MongoDB Version:

**Comment by mariussturm** [comment]
Hi, thanks for the feedback!
Is this a fresh installation or an update from a former version?

**Comment by christianmarangoni** [comment]
Fresh installation, at the end i has rollback to rc1

**Comment by nsiakotos** [comment]
I also experience this.  Windows 2012R2 during a clean install on a system that has never had the sidecar installed.  This happened all 5 times installed it.

**Comment by mariussturm** [comment]
This should be fixed in 0.1.0!
