### ISSUE TITLE
Logstash backend?

### ISSUE THREAD

**Issue by chouex** [Graylog2/collector-sidecar#15]
### Problem description

Will Logstash backend be enhance? because nxlog backend configured by Collectors can not extract log at log client.

**Comment by joschi** [comment]
@chouex Could you please elaborate on the problem you have with nxlog? Which logs can't exactly be "extracted"?

We're currently planning to add support for the Elastic Beats platform to the collector sidecar, so that might solve your problem, too.

**Comment by chouex** [comment]
`Graylog 2.0.1 (81e0187) on graylog (Oracle Corporation 1.8.0_77 on Linux 4.2.0-36-generic)`

In `Collector Configuration` -> `Configure Collector Inputs` 
the `file log type` can not specify the log format (eg. apache combine log) that extracted each line of access_log to fields before send to graylog server.

currently i use different input in graylog server with extractor to extract the access log, but i have to create multiple input to map different log format(eg. audit,maillog etc)

**Comment by joschi** [comment]
> In `Collector Configuration` -> `Configure Collector Inputs` 
the `file log type` can not specify the log format (eg. apache combine log) that extracted each line of access_log to fields before send to graylog server.

You can simply create extractors (e. g. a Grok extractor with the `%{COMBINEDAPACHELOG}` pattern) for this in Graylog.

**Comment by chouex** [comment]
yes, i could extracted ay server-side, but i want to extracted at client-side so i able to use same input(and port)

**Comment by mariussturm** [comment]
The priority for adding Logstash is relatively low at the moment. As joshi said, the Beats platform is the next collector framework we will support.
You can use a static field like `from_apache: true` or `from_maillog: true` in the Sidecar configuration to distingish your different log sources. But the general Graylog architecture is to extract log fields on the server, not the client.

**Comment by jalogisch** [comment]
this is out of scope of the collector sidecar. 

this is why we close this issue.
thank you
