### ISSUE TITLE
Support for compressing log data for the trip to the server

### ISSUE THREAD

**Issue by belmow** [Graylog2/collector-sidecar#153]
### Problem description

I have multiple sites and I would like to have collector-sidecar send logs to a central graylog server via filebeat.  I would like to have the option to enable compression of the log data in order to sacrifice some CPU and latency to save bandwidth.

### Steps to reproduce the problem

1. ...

### Environment

* Sidecar Version: 0.1.0
* Graylog Version: 2.2.2+691b4b7
* Operating System: Linux
* Elasticsearch Version: 2.4.4
* MongoDB Version: 2.4.9

**Comment by mariussturm** [comment]
Filebeat is using the Beats-protocol to transfer the actual data. The Beats protocol is compressing the data by default with level 3, what is a good compromise between speed and compression ratio: https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html#_compression_level_2
