### ISSUE TITLE
The documented debug command does not work

### ISSUE THREAD

**Issue by freebsdsa** [Graylog2/collector-sidecar#154]
### Problem description
The documented way to debug issues with the '-debug' command line option does not seem to work. I am trying to work through a filebeats issue and it would be nice to be able to debug what is going on better.

### Steps to reproduce the problem

`# /usr/bin/graylog-collector-sidecar -debug -c /etc/graylog/collector-sidecar/collector_sidecar.yml`
`flag provided but not defined: -debug`
`Usage: graylog-collector-sidecar -c [CONFIGURATION FILE]`
`  -c string`
`    	Configuration file (default "/etc/graylog/collector-sidecar/collector_sidecar.yml")`
`  -configtest`
`    	Validate configuration file and exit.`
`  -service string`
`    	Control the system service [start stop restart install uninstall]`
`  -version`
`    	Print version and exit`
`# /usr/bin/graylog-collector-sidecar -version`
`Graylog Collector Sidecar version 0.1.0 (840d51b) [go1.7/amd64]`

### Environment

* Sidecar Version: 0.1.0 (840d51b)
* Graylog Version: 2.2.0
* Operating System: Centos 7.2

**Comment by mariussturm** [comment]
Please update to the 0.1.0 final release, the debug option was introduced at a later point and is not available in youer version.
