### ISSUE TITLE
Support collecting from systemd's journal

### ISSUE THREAD

**Issue by tanapoln** [Graylog2/collector-sidecar#159]
### Problem description
Looking for support in collecting log from journald.

There is Journalbeat (https://github.com/mheese/journalbeat) which does the job but I think it may not match what graylog required.

### Background
In my case, I would like to send container logs (docker) to graylog server. Docker also provided somes logging driver (including GELF) but the big flaw for GELF driver is that it lost ability to execute `docker logs` locally.

I'm seeking for solution in my case, I think journald is the best match which including ability to see log locally, each log has metadata included (container id, container name, etc.)

But the problem is that journald is not support remote logging.

#### redirect journald to syslog and send to remote graylog server
I think this is easiest way to do but from what I tried it discard metadata of the log which is not useful in my case (for example, I want to query log only from a specific container name)

#### make collector-sidecar to support journald
This is the way I think it sound great but I also have no idea how to do that.

What I imagined is make collector-sidecar to talk directly to journald and convert data into GELF then send to graylog.

There are things that I still don't know:
- Is GELF format compatible with/convertible to journald?
- collector-sidecar need to maintain log position so that we won't get duplicate log
- how we connect to journald? Is there any API?

Anyone can help with this? do we have another solution?

I'm very beginner for Go, in case if I can help contribute.

**Comment by joschi** [comment]
@tanapoln Graylog has a Beats input, so you can send messages from journalbeat directly to Graylog.

**Comment by jalogisch** [comment]
@tanapoln I run that beat in my lab and it is working with no issue - using a beats input as @joschi wrote.

shipping that beat direct with collector sidecar would not be that easy as you need a special version for every OS.

As soon as you have a generic beat we will look again into this.

**Comment by jalogisch** [comment]
@tanapoln 

as already said - you can use journal beat and ship the logs to any beats input you have configured in graylog. 

management of journal beat via sidecar will be not implemented in the near future.
