### ISSUE TITLE
Configure host side tags through web UI

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/collector-sidecar#162]
### Problem description
In preparation of a multi user scenario the host side of the tag configuration should be moved to the web interface as well. In this way non admin users could take full control over the collector configuration without interference of an admin.

**Comment by lennartkoopmann** [comment]
@marius can you elaborate a little more on this from a workflow perspective? Would this mean, that the user could assign tags to a host from the web interface after the host has reported in for the first time?

**Comment by martinbydefault** [comment]
From my experience, I think the feature should be something like this:  
For the connected hosts listed in the "collectors" section in web UI, there should be an option to change the tags (add or delete).  
Maybe an "edit" button next to each host, and when clicked, a list of tags is displayed (current tags) that can be modified or deleted, and also you can add new tags.  
As an improvement of this feature (once implemented) it will be useful to edit hosts tags in bulk:  
After selecting multiple hosts (having checkboxes next to them) and pressing an edit button, a list of common tags si presented and each tag can be edited, deleted and it can be also added news tags, and the action is applied to all selected hosts.

**Comment by mariussturm** [comment]
From a UI perspective this is a bit tricky but the goal is to start the Sidecar with a minimum configuration (basically just the Server API URL) and everything else happens in the web interface. So that an admin can start Sidecars on a bunch of servers and other Graylog users can fully control them by adding or deleting tags themselves. If we implement this like @martinbydefault described or if we use some other UI concept is not clear at this point.

**Comment by bernd** [comment]
@mariussturm Can this be closed?

**Comment by mariussturm** [comment]
Yes, this is obsolete with 3.0.
