### ISSUE TITLE
windows server 2003 r2 setup

### ISSUE THREAD

**Issue by faxonnet** [Graylog2/collector-sidecar#164]
### Problem description
in 2003 server r2 ita "program files" not exist 
to fix this problem i try to change path in 
collector_sidecar.yml
but there is some path hardcoded..
###WORK Around
create folder "program files" and then move all graylog folder on it 
### Steps to reproduce the problem
install on 2003 r2 ita

### Environment
2003 r2

**Comment by mariussturm** [comment]
Hi, thanks for the feedback!
Windows Server 2003 is quite some time end-of-life by MIcrosoft, therefore we are not actively providing fixes for it anymore. If you want to contribute a pull request for this issue we are happy to review it.

**Comment by faxonnet** [comment]
For posterity
If you want to use 2 or more snippets you can directly insert the configuration into snippets leaving blank inputs and outputs in the configurator.
Below a working example
{{If .Windows}}
Output:
   Logstash:
     Hosts:
     - 192.168.1.1:5044
path:
   Date: C: \ Program Files \ graylog \ collector-sidecar \ cache \ winlogbeat \ data
   Logs: C: \ Program Files \ graylog \ collector-sidecar \ logs
Tags:
- allin
Winlogbeat:
   Event_logs:
   - name: custom_app
     Event_id: 1700, 1800
   - name: Security
     Event_id: 528-540, 551
{{End}}
