### ISSUE TITLE
Sidecar configuration + Environment variables

### ISSUE THREAD

**Issue by tehpanta** [Graylog2/collector-sidecar#167]
### Problem description
Collector-sidecar.conf is not able to use environment variables.

### Steps to reproduce the problem

1. Try to configure collector sidecar to have node_id: APPNAME_TESTING_$HOSTNAME

### Environment

* Sidecar Version: 0.1.0
* Graylog Version: 2.2.3
* Operating System: RedHat Linux

**Comment by mariussturm** [comment]
Hi,
thanks for the feedback!

This works for me in the latest version (0.1.1):
`node_id: graylog-collect_$USER`

Maybe $HOSTNAME is not set in the shell environment the Sidecar is started in?
There should also be a log message about the replacement like: `INFO[0000] [ConfigFile] Replacing config environment variable...`

**Comment by jalogisch** [comment]
@tehpanta is your issue resolved now?

**Comment by tehpanta** [comment]
Yep, sorry for even creating this.

**Comment by joschi** [comment]
@tehpanta Not a problem. Glad we could help!
