### ISSUE TITLE
snippet filtering

### ISSUE THREAD

**Issue by faxonnet** [Graylog2/collector-sidecar#169]
### Problem description
i'm not able to find documentation for complex filtering
who can help me ? 
### Steps to reproduce the problem

add snippet like this :

- name: Security   
   event_id: 4624
   !event_data.LogonType: 0
   !event_data.LogonType: 5
   !event_data.TargetUserName: "ANONYMOUS LOGON"

### Environment
windows server 2008r2
* Sidecar Version: 1.1

**Comment by mariussturm** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
