### ISSUE TITLE
no configuration found for configured tags.

### ISSUE THREAD

**Issue by neophilipp** [Graylog2/collector-sidecar#17]
### Problem description

I added 2 tags (linux, apache) to the .yml file. These two i configured in graylog with 2 configurations (each tag one configuration) and i let each read a file. this works (i could see the content of both logs in Graylog) but i get every 10 seconds a syslog entry:

_2016-05-18 14:51:10.000	test-debian
May 18 14:51:09 test-debian /usr/bin/graylog-collector-sidecar[3389]: time="2016-05-18T14:51:09+02:00" level=info msg="[RequestConfiguration] No configuration found for configured tags!"_

_2016-05-18 14:51:10.000	test-debian
May 18 14:51:09 test-debian graylog-collector-sidecar[3389]: time="2016-05-18T14:51:09+02:00" level=info msg="[RequestConfiguration] No configuration found for configured tags!"_

Why?? What does it mean? 

What is the Syntax in yml file for more than one tag?

_tags:
    - apache linux_

or

_tags:
    - apache, linux_

or

_tags:
    - apache
    - linux_

yaml sytax should be the last one with dash but log tells me that the config file is corrupt.
_level=error msg="[nxlog] Error during configuration validation: exit status 1_
### Environment

* Sidecar Version: newest, 0.0.7
* Graylog Version: newest, 2.0.1
* Operating System: Debian Jessie
* Elasticsearch Version: 2.3

**Comment by perbly** [comment]
Hi

I use the windows sidecar and use this syntax for multiple tags, and that´s working.

tags: 
    - windows
    - iis

/Per

**Comment by neophilipp** [comment]
THX but not working for me:


_Mai 19 09:58:32 test-debian /usr/bin/graylog-collector-sidecar[4515]: time="2016-05-19T09:58:32+02:00" level=error msg="[nxlog] Error during configuration validation: exit status 1"

Mai 19 09:58:32 test-debian /usr/bin/graylog-collector-sidecar[4515]: time="2016-05-19T09:58:32+02:00" level=info msg="[nxlog] Collector configuration file is not valid, waiting for update..."_

**Comment by mariussturm** [comment]
Hi,
this is now a different error. Your nxlog configuration is not valid and the actual collector can not be started. Could you please post the generated file?

**Comment by neophilipp** [comment]
Hello Marius, 

i know. My second post show the effect when i added the tags like user "perbly said".



I attached the sidecar conf file and the generated nx

**Comment by neophilipp** [comment]
[nxlog.conf.txt](https://github.com/Graylog2/collector-sidecar/files/277479/nxlog.conf.txt)
[collector_sidecar.yml.txt](https://github.com/Graylog2/collector-sidecar/files/277480/collector_sidecar.yml.txt)

Here are my 2 Files:

**Comment by mariussturm** [comment]
The configuration file is valid but has some duplicated entries. Please make sure that there is just one `nxlog-default` snippet when you merge two configurations together. It's generated by default when you create a new configuration.
Other than that, make sure that the NXLog log path is writabel by the nxlog user: `sudo chmod nxlog.nxlog /var/log/nxlog/`
You can also validate the configuration file yourself to get some debug informations: `sudo nxlog -v -f /etc/graylog/collector-sidecar/generated/nxlog.conf'

**Comment by mariussturm** [comment]
Closing this for now, feel free to re-open when this is still an issue.
