### ISSUE TITLE
Have a roadmap, with support all beats family ?

### ISSUE THREAD

**Issue by bj1116** [Graylog2/collector-sidecar#170]
Hello ,
Have a roadmap, with support all beats family ?
Tks!

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
