### ISSUE TITLE
Secure connection with tls

### ISSUE THREAD

**Issue by Winschi1** [Graylog2/collector-sidecar#173]
### Problem description
Hello,
with filebeat 5.0 the tls section of the config file was changed to ssl (see https://www.elastic.co/guide/en/beats/libbeat/master/breaking-changes-5.0.html#_configuration_file_changes). The collector-sidecar with Version 0.1.1 generated the old section with tls not ssl. So the communication from filebeat to graylog don't work. As a Workaround i can create a snippet with the correct ssl section and then the communication work.

Attached a generated file beat config file with ssl section from snippet.
[filebeat_tomcat.zip](https://github.com/Graylog2/collector-sidecar/files/989931/filebeat_tomcat.zip)

### Steps to reproduce the problem

1. create Collector with beat output of type Filebeat and  select Enable TLS Support
2. Start a sidecar-collector that read the configuration from graylog
3. Check the generated filebeat config file
### Environment

* Sidecar Version: 0.1.1
* Graylog Version: 2.2.3
* Operating System: Linux
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.4.2

**Comment by mariussturm** [comment]
Hi,
the Sidecar is testing the version of the configured binary and switches to the new configuration syntax accordingly. Are you sure you updated the Filebeat binary at the configured path?

**Comment by Winschi1** [comment]
Yes, i have checked it. The binary of filebeat are from 28.04.2017 19:36

**Comment by mariussturm** [comment]
The problem is that we check the minor version as well. Currently we support Filebeat up to 5.1.x. Once we see that the configuration part of Filebeat is stable enough we can relax that check to only check the major version number. For now please use a supported version of Filebeat.
