### ISSUE TITLE
Collector_sidecar_installer.exe silent install should have more options so editing collector_sidecar.yml won't be needed to simplify automated installation

### ISSUE THREAD

**Issue by np422** [Graylog2/collector-sidecar#176]
### Problem description

When using silent install on windows there are two placeholders in collector_sidecar_windows.yml that can be specified on the command line, SERVERURL and TAGS.

It looks like easy task to extend the standard config file with more placeholders and update the dist/recipe.nsi to do further editing of the installed config file using the placeholders and command line switches.

Automated installs would be simplified if they could avoid to use templates or the need copy prepared configuration files.

The extra edit I usually need to do after an install in addition to the silent install provided options is to to set tls_skip_verify and node_id.

If the different backends could be specified or removed by the use of silent install command switches it would be truly awesome, although this feature is of less priority IMHO.

### Steps to reproduce the problem

1. Install collector-sidecar on a windows host

### Environment

* Sidecar Version: 0.1.1
* Graylog Version: 2.2.3-1
* Operating System: ubuntu 16.04 / Windows server 2012 R2 Standard
* Elasticsearch Version: 2.3.4
* MongoDB Version: 3.2.12

**Comment by joaociocca** [comment]
It would be nice to have an option to set the install path. It'd be really nice if I could use something like "-installPath 'c:\Program Files\Monitoring\graylog-sidecar' -SERVERURLS -TAGS".

**Comment by jczinger** [comment]
I cannot second this more. This would be great.
