### ISSUE TITLE
winlogbeat, windows-event-log send non readable signs

### ISSUE THREAD

**Issue by neophilipp** [Graylog2/collector-sidecar#177]
Hello, 

I have started a global Beats Input on port 5044 and finished a collector configuration. 
If I started the Windows Sidecar Service I can see hundreds of messages come in (on upper right side IN/OUT selection) but I can't see any message in "search" selection "showed recieved messages" in "Inputs" area. 

I think the messages came in in a wrong format and the Beats Input can't handle that.

I check it like this: If i change the input port to a RAW TCP Port something like that come in:

<img src="https://cdn-business.discourse.org/uploads/graylog/original/1X/9cf7cda2de93c17d0752eb2eb121614dce35d5d7.png" width="690" height="402">

On Logs I find such things:

ERROR [DecodingProzessor] Unable to decode raw message...
ERROR [GelfCodec] Could not parse JSON....

Are there any known Problems with Windows Server 2012R2 as log Source?

### Environment

* Sidecar Version: 1.1
* Graylog Version: 2.3
* Operating System: Debian, W2012/R2
* Elasticsearch Version: 5.4
* MongoDB Version:

**Comment by mariussturm** [comment]
Hi,
usually thats a timezone issue. Could be that the Windows host have a different timezone configured than the Graylog server, when you now search for messages in the last x-minutes you see nothing. Set the time selector in the GRaylog search to 'All messages' to see if that's the case.
Please use our Discourse forum for more general questions.
