### ISSUE TITLE
Send logs to Kafka server

### ISSUE THREAD

**Issue by k1-hedayati** [Graylog2/collector-sidecar#180]
### Problem description
Sidecar has a nice feature that it is possible to control it directly from Graylog server but it only allows sending log data to graylog itself. Currently I'm using rsyslog to send logs to kafka server and consume it using graylog, configuring each rsyslog instance is a hassle, if sidecar had feature to send logs to kafka server I won't have to use rsyslog.

### Environment

* Sidecar Version: 0.1.3
* Graylog Version: 2.2.3

**Comment by joschi** [comment]
@k1-hedayati The Graylog Collector Sidecar itself doesn't send any log messages to Graylog. It merely configures a third party collector such as NXLog or Filebeat.

**Comment by k1-hedayati** [comment]
@joschi apparently Filebeat has a feature to [send logs to kafka](https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html), so I should use Define Beats Snippets to add related configs?

**Comment by joschi** [comment]
@k1-hedayati Yes.

**Comment by florianvolle** [comment]
Thank you but this is currently nothing that we think fits into the idea of Sidecar.
