### ISSUE TITLE
Graylog 2.3 and Sidecar 

### ISSUE THREAD

**Issue by opHASnoNAME** [Graylog2/collector-sidecar#182]
### Problem description

Input is not listening on port 5044. I can send logs via internal network, but not via
public ip.

If i check "netstat -a" port 5044 is listeing in *:5044 (ip4). UFW and other Firewalls are disabled. Ist Sidecar 0.1.3 compatible with Graylog 2.3 Beta?

### Steps to reproduce the problem

Create net Beats input, bind to 0.0.0.0 with port 5044

### Environment

* Sidecar Version: 0.1.3
* Graylog Version: 2.3
* Operating System: Ubuntu 16.04.x LTS
* Elasticsearch Version: 5.x
* MongoDB Version:

**Comment by joschi** [comment]
For the record, Graylog Collector Sidecar 0.1.3 is compatible with Graylog 2.3.x.

**Comment by opHASnoNAME** [comment]
Thanks - our problem was a corrupted network security group @ azure (something like a poor mans firewall)
