### ISSUE TITLE
expandEnv does not work for Windows System Variables

### ISSUE THREAD

**Issue by ogni90** [Graylog2/collector-sidecar#189]
When trying to set a Windows system variable in a configuration file it doesn't get replaced. 
The expandEnv function in cfgfile/cfgfile.go uses golangs os.Expand feature which does not support '%foo%' style Windows variables (https://groups.google.com/forum/#!topic/golang-dev/dUkSp7pnsdM). A wrapper would need to be written that finds such variables and replaces them via os.Getenv(key).

**Comment by mariussturm** [comment]
You can replace `%foo%` with `${foo}` to get it working.
