### ISSUE TITLE
Assign tags via Graylog web interface

### ISSUE THREAD

**Issue by Wernervdmerwe** [Graylog2/collector-sidecar#191]
Bit of a two-prong request.

1. We are mostly a MS shop, the Windows guys can do their own config snippets, but then it comes to me and my Linux team to update the hiera yaml files to assign those tags in the sidecar config files.

It would be hugely helpful if the tags can be assigned via the front-end, so they can take ownership of the entire process themselves, but I understand this is not an easy change to implement.
It also simplifies the implementation requirement of the below request.

2. We have multiple tenants in our VM farms, and Graylog becomes a value-add to our service offering. Each tenant has their own port/port range for GL inputs. The port allocation is based on either tenant name if low traffic, or application name if they have larger volume of traffic. Streams is then based on the GL input port for their user to access.

This works great, but it does result in me having to duplicate for example the NginX or EventLog/Syslog or Apache snippet for each tenant/app. As each server will have those shipped, but needs to go to a different collector-output to accommodate the stream requirement.
(I can't base this on source only as we do have some common application servers)

Having the ability to create 'global' inputs and outputs could be helpful. Thus having a tag for say a globally available Syslog/Eventlog input that can be allocated to any server, and then being able to select a tenant specific output. This allows me to maintain one config snippet (for say Nginx), but retain the ability to use a different collector output per app/tenant/use-case to send to the different GL inputs.

**Comment by mariussturm** [comment]
Closing this in favour of #162
