### ISSUE TITLE
ARM build for running the sidecar on a raspberry pi

### ISSUE THREAD

**Issue by danielclasen** [Graylog2/collector-sidecar#192]
Hey there, 
just reaching out to you to ask for an ARM version of the .deb of the sidecar. I am currently planning to collect log files from a raspberry pi running raspbian 8.0 (which is a small dev system for an IOT device) and ship those to graylog. I know that I could just use a different way of shipping my files from the pi but since the production hardware is going to use the sidecar I want it to be as equal as possible in both environments.

Any help appreciated, cheers
-daniel

**Comment by florianvolle** [comment]
Hi @danielclasen we are currently not planning to build this. You can take a look at the Makefile to figure out how to compile it. 

Thank you!

**Comment by mzac** [comment]
+1 on this, sad that it is closed, I too would love to have an official build of sidecar running on a few Pi servers...
