### ISSUE TITLE
Unknown beats protocol version: 102

### ISSUE THREAD

**Issue by ladenedge** [Graylog2/collector-sidecar#194]
### Problem description

Beats input shows messages coming in, but they don't appear in searches.  *graylog-server* logs report a Beats protocol issue:

```
ERROR [NettyTransport] Error in Input [Beats/59e461971e71ff0362a461e1] (channel [id: 0xfd83e615, /192.168.7.133:2329 => /192.168.7.118:5044])
java.lang.Exception: Unknown beats protocol version: 102
```

### Environment

* Sidecar Version: 0.1.4-1  (collector_sidecar_installer_0.1.4-1.exe)
* Graylog Version: 2.3.1+9f2c6ef
* Operating System: Windows 10

My Sidecar seems to have shipped with **filebeat version 5.5.1 (amd64), libbeat 5.5.1**.  When I replace filebeat.exe with a newer version (**filebeat version 5.6.3 (amd64), libbeat 5.6.3**) and restart sidecar, my messages make it to the index and appear in searches.

**Comment by mariussturm** [comment]
Closing this, filebeat version got updated in newer sidecar packages.
