### ISSUE TITLE
k8s  containter log  collect   through collector-sidecar

### ISSUE THREAD

**Issue by xuanyuanaosheng** [Graylog2/collector-sidecar#196]
I want to collector k8s'containter logs to graylog through deploying collector-sidecar containter on every k8s nodes.  Can collector-sidecar be used as a daemonset like k8s official fluentd ?  I think this is a good way to collect log in k8s.

**Comment by jalogisch** [comment]
just to have it said - fluentd can output gelf to graylog with a plugin: https://github.com/bodhi-space/fluent-plugin-gelf-hs

**Comment by florianvolle** [comment]
Hi @xuanyuanaosheng this is not on our current roadmap. We suggest to use the plugin that @jalogisch pointed out. 
Anyway we are willing to review any pull request.

Thank you!
