### ISSUE TITLE
add install package for solaris

### ISSUE THREAD

**Issue by cha-won** [Graylog2/collector-sidecar#20]
### Problem description

We are trying to adjust graylog to our project and we think it's pretty helpful for us.

i think the collector-sidecar is great idea to gathering logs on the nodes file system.

you are providing packages for both and fortunately most developers are using ubuntu or centos .

i hopefully ask you to provide package for the solaris os. 

actually we tried to build from source on the solaris os , it resulted to fail.

thank you.

### Steps to reproduce the problem

1. ...

### Environment

* Sidecar Version: 0.0.7
* Graylog Version: 2.0 rc
* Operating System: solaris
* Elasticsearch Version: 2.x
* MongoDB Version: 3.1.x

**Comment by joschi** [comment]
@cha-won Which version of Solaris are you running specifically?

**Comment by cha-won** [comment]
@joschi specifically , we are using the smartOS based on openSolaris. thank you.

**Comment by mariussturm** [comment]
Hi,
we dont have the resoures right now to maintain Solaris packages but I have added all necessary settings to (cross-)compile the project for Solaris. So you can install `go` and `glide` on a random platform and do:

```
$ glide install
$ make build-solaris
```

To compile the project yourself for Solaris. Afterwards you can find the binary in `build/0.0.x/solaris/amd64/graylog-collector-sidecar`
