### ISSUE TITLE
cant build packages 

### ISSUE THREAD

**Issue by Manjukb** [Graylog2/collector-sidecar#204]
### Problem description  

not able to build packages 

> 

### Steps to reproduce the problem
`make build` was successful  but `make package-all` fails 
got below error 
`: unknown file type: ../../build/0.1.5/linux/amd64/graylog-collector-sidecar (RuntimeError)
        from /usr/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
        from /usr/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
        from /usr/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
        from /usr/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
        from /usr/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
        from /usr/lib/ruby/2.3.0/fileutils.rb:1585:in `fu_each_src_dest0'
        from /usr/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
        from /usr/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
        from /var/lib/gems/2.3.0/gems/fpm-cookery-0.33.0/lib/fpm/cookery/source_handler/local_path.rb:17:in `fetch'
        from /var/lib/gems/2.3.0/gems/fpm-cookery-0.33.0/lib/fpm/cookery/packager.rb:87:in `block in dispense'
        from /var/lib/gems/2.3.0/gems/fpm-cookery-0.33.0/lib/fpm/cookery/packager.rb:84:in `chdir'
        from /var/lib/gems/2.3.0/gems/fpm-cookery-0.33.0/lib/fpm/cookery/packager.rb:84:in `dispense'
        from /var/lib/gems/2.3.0/gems/fpm-cookery-0.33.0/lib/fpm/cookery/cli.rb:125:in `exec'
        from /var/lib/gems/2.3.0/gems/fpm-cookery-0.33.0/lib/fpm/cookery/cli.rb:87:in `block in execute'
        from /var/lib/gems/2.3.0/gems/fpm-cookery-0.33.0/lib/fpm/cookery/book.rb:22:in `load_recipe'
        from /var/lib/gems/2.3.0/gems/fpm-cookery-0.33.0/lib/fpm/cookery/cli.rb:83:in `execute'
        from /var/lib/gems/2.3.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
        from /var/lib/gems/2.3.0/gems/clamp-1.0.1/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /var/lib/gems/2.3.0/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
        from /var/lib/gems/2.3.0/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
        from /var/lib/gems/2.3.0/gems/fpm-cookery-0.33.0/bin/fpm-cook:7:in `<top (required)>'
        from /usr/local/bin/fpm-cook:23:in `load'
        from /usr/local/bin/fpm-cook:23:in `<main>'
Makefile:102: recipe for target 'package-linux' failed
make: *** [package-linux] Error 1`

1. ...

### Environment

* Sidecar Version: master 
* Graylog Version: NA 
* Operating System: ubuntu 16.4
* Elasticsearch Version:Na
* MongoDB Version:Na

**Comment by mariussturm** [comment]
Hi,
before you can package the software you need the linux and windows binaries in `buid/<version>/`. Check that the binaries exist, in doubt re-build them with:

```
make linux
make linux32
make windows
make windows32

make package-all
```
