### ISSUE TITLE
Feedback to current collector-sidecar 0.1.4

### ISSUE THREAD

**Issue by dnauck** [Graylog2/collector-sidecar#207]
Hello,

i want to provide you some feedback to a private test of the current collector-sidecar:

I'm working currently in a project that rolled out a SIEM infrastructure (with a competing solution) to more then 45.000 servers (windows, linux, etc.) and had also the issue to read file based logs of applications and windows events logs, etc.

Now i tested the graylog-sidecar in another project and found the following issues:

## automatic deployment

Currently its not easily possible to deploy the collector-sidecar with standard solutions on Windows (e.g. Active Directory GPO deploment or SCCM, for example because of #179 and #176). A *.msi package is missing.

Also the default created sidecar configuration is not usable at all (it crash because you need to configure winlogbeat _and_ filebeat even if you don't use it (ts enabled by default)). Also the `node_id` is a hard coded value (see #198).

It would be helpful if you:

- provide a msi package
- just require to set the `server_url` via parameter
- set `node_id`by default to the FQDN of the host (FQDN as you may have more then one domain)
- disable all inputs by default, so it won't crash if not configured

## configuration by tags

The idea is cool (we use something similar in the large project).

But:

- currently multiple tags are evaluated with **OR** and not **AND**, e.g. a configuration of [`windows`, `server 2016`, `dhcp`] will be deployed to host that have **at least** one of the tags configured. I would like to only deploy such an configuration to all host that have **all** of the tags defined.
- tags needs to be configured on each client in the sidecar configuration. That is very painful for automatic deployment. Just allow to classify clients via the web-ui (#162) and rest api and via lookups (in larger environments you'll have a configuration management database that knows exactly what software is installed on a server.)

## documentation and best practises

E.g.: please provide some information about winlogbeat vs nxlog (pros and cons from a graylog perspective), etc.

You could also provide default (editable) configs sets/templates for domain controllers, etc.

## our current workflow

A `collector` is installed via platform specific tools (e.g. SCCM for Windows, etc.) just with a `default deployment server url` set (nothing else is configured). As soon as the server is ready the `collector` asks the `default deployment server` for a new configuration. The `default deployment server` has a list of all allowed (is the system SIEM relevant?!) servers (hostname, ip address, data center location, security zone,, etc.) and sends them a config to connect to their correct/responsible `deployment server` in the same data center, security zone, etc.

This `deployment server` has information (from a CMDB, lookup, etc) about installed applications, server stage, active/passive stuff on clustered systems, location of logfiles of the applications, etc.

It sends the server a configuration for each monitoring target and where to send the logs. Its also able to classify log messages (adding tags to them) and do some simple prefiltering (to not add load on the network with unused logs, e.g. ignoring windows events logs with id x,y,z, etc.)

I hope this helps a bit.

**Comment by mariussturm** [comment]
Thanks for the detailed feedback, this is were welcome! We will pour it in into the next roadmap planing. However what you describe in your workflow is pretty environment specific imo but we always need to keep an eye on general use-cases. But I hope we can find a better working solution for you and for others in the next version of the Sidecar. Thanks a lot!
