### ISSUE TITLE
Add possibility to stop filebeat under System -> Collectors

### ISSUE THREAD

**Issue by Rand72889** [Graylog2/collector-sidecar#209]
Under System ->Collectors it is only possible to restart the service.
I think it would be helpful to be able to start/stop the filebeat service temporary instead of connecting to the server manually.

**Comment by mevansFCStone** [comment]
OMG you are awesome

**Comment by bernd** [comment]
This will be possible with the new sidecar system in the upcoming Graylog 3.0 version.
