### ISSUE TITLE
Looking under wrong directory for NXlog module on RedHat

### ISSUE THREAD

**Issue by sebw** [Graylog2/collector-sidecar#21]
RHEL 6.3

Sidecar is looking for NXlog modules in /usr/lib/ while RPM installs everything under /usr/libexec/

```
Name        : collector-sidecar            Relocations: / 
Version     : 0.0.7                             Vendor: graylog
Release     : 1                             Build Date: Fri 13 May 2016 12:32:04 PM CEST
Install Date: Mon 23 May 2016 10:47:52 AM CEST      Build Host: ubuntu
Group       : optional                      Source RPM: collector-sidecar-0.0.7-1.src.rpm
Size        : 11064832                         License: GPLv3
Signature   : (none)
Packager    : Graylog, Inc. <hello@graylog.org>
URL         : https://graylog.org
Summary     : Graylog collector sidecar
Description :
Graylog collector sidecar

Name        : nxlog-ce                     Relocations: (not relocatable)
Version     : 2.9.1504                          Vendor: NXLog Ltd
Release     : 1                             Build Date: Tue 08 Dec 2015 02:07:49 PM CET
Install Date: Mon 23 May 2016 10:58:53 AM CEST      Build Host: localhost
Group       : System Environment/Daemons    Source RPM: nxlog-ce-2.9.1504-1.src.rpm
Size        : 5270620                          License: NXLog Public License
Signature   : (none)
URL         : http://nxlog.org
Summary     : nxlog is a modular, multi-threaded, high-performance log management solution
Description :

```
/var/log/graylog/collector-sidecar/nxlog.log:

`2016-05-23 13:57:29 ERROR Failed to load module from /usr/lib/nxlog/modules/extension/xm_gelf.so, /usr/lib/nxlog/modules/extension/xm_gelf.so: cannot open shared object file: No such file or directory;DSO load failed`

Installed:

```
# rpm -ql nxlog-ce | grep xm_gelf
/usr/libexec/nxlog/modules/extension/xm_gelf.so
```

**Comment by mariussturm** [comment]
Hi,
you can change this in the web interface with the `nxlog-default` snippet in your configuration.

**Comment by coffee-squirrel** [comment]
We just ran into this, as well as something similar with `PidFile` (only seen due to how we're scripting the installs).  Modifying each snippet to match the actual nxlog paths isn't ideal, but did fix the issue.

@mariussturm would some sort of special handling for Fedora/CentOS/RHEL, or something like global snippets, be possible?

**Comment by mariussturm** [comment]
Just added a simple distro detection to the snippet parsing: https://github.com/Graylog2/collector-sidecar/commit/c29dd3d51c7fad7402cc2302435037a9566a4703
With that you can use this in a snippet:

```
{{if eq .LinuxPlatform "debian"}}
   foo
{{end}}
{{if eq .LinuxPlatform "redhat"}}
  bar
{{end}}
```
The `nxlog-default` snippet will reflect this and provide the correct path for the target system

**Comment by coffee-squirrel** [comment]
Thanks, that's greatly appreciated!

**Comment by arogozin** [comment]
```ln -s /usr/libexec/nxlog /usr/lib/nxlog```
