### ISSUE TITLE
Filebeat config update issue

### ISSUE THREAD

**Issue by serverint** [Graylog2/collector-sidecar#212]
### Problem description
We have installed collector-sidecar to get the logs from an ubuntu machine which is fetching the data with filebeat.....The issue that I am facing is when we update the input from collector>configuration>input> it updates the changes to filebeat.yml in the client host however, the change doesn't get implemented until we manually restart the filebeat service in the client machine.

### Steps to reproduce the problem

1. ...

### Environment

* Sidecar Version:
0.1.4-1_amd64.deb
* Graylog Version:
Graylog 2.3.2+3df951e on graylog 
* Operating System:
ubuntu 16.04
* Elasticsearch Version:
* MongoDB Version:

**Comment by mariussturm** [comment]
Could you please provide some log files from the Sidecar in question. You should see restart attempts and configuration updates there.

**Comment by rvishwakarma825** [comment]
Yes, i noticed it later.......my bad. Anyway Thanks for your help @mariussturm 
However, i couldn't see any GUI option to exclude files from the input like we have for the lines "Lines that you want Filebeat to exclude" . I only got a reference of using it as below in filebeat conf which i guess will get override at next configurational change.......

  paths:
    - /var/log/apache2/*.log
    exclude_files: ['access.log']

**Comment by mariussturm** [comment]
@rvishwakarma825 for general questions please use our public forum. If there is no actual issue with the configuration update I am closing this for now.
