### ISSUE TITLE
Install collector sidecar with custom path on using windows binary

### ISSUE THREAD

**Issue by GaneshbabuRamamoorthy** [Graylog2/collector-sidecar#214]
### Problem description
I am trying to install Graylog collector sidecar using collector-sidecar-0.1.4.tar.gz but I am unable to do the setup.

Also I couldn’t find any reference documentation related to this setup and I am trying to do custom installation out of it.

When I untar the collector-sidecar-0.1.4.tar.gz file I am getting the graylog-collector-sidecar.exe file in the path (~/collector-sidecar/0.1.4/windows/amd64) How do I setup the graylog collector sidecar with the .exe?

I just execute the .exe in powershell and I got the following response,

```
time="2017-12-21T16:48:48Z" level=info msg="collector-id file doesn't exist, generating a new one"
time="2017-12-21T16:48:48Z" level=info msg="Using collector-id: 273f5f1e-7868-43c7-bfd5-530a66156b96"
time="2017-12-21T16:48:48Z" level=info msg="Fetching configurations tagged by: [windows iis]"
time="2017-12-21T16:48:50Z" level=info msg="Starting signal distributor"
time="2017-12-21T16:48:50Z" level=info msg="[winlogbeat] Starting (exec driver)"
time="2017-12-21T16:48:50Z" level=info msg="[filebeat] Starting (exec driver)"
time="2017-12-21T16:48:51Z" level=error msg="[filebeat] Backend finished unexpectedly, trying to restart 1/3."
time="2017-12-21T16:48:51Z" level=info msg="[filebeat] Stopping"
time="2017-12-21T16:48:51Z" level=error msg="[winlogbeat] Backend finished unexpectedly, trying to restart 1/3."
time="2017-12-21T16:48:51Z" level=info msg="[winlogbeat] Stopping"
time="2017-12-21T16:48:53Z" level=info msg="[filebeat] Starting (exec driver)"
time="2017-12-21T16:48:53Z" level=info msg="[winlogbeat] Starting (exec driver)"
time="2017-12-21T16:48:54Z" level=error msg="[filebeat] Backend finished unexpectedly, trying to restart 2/3."
time="2017-12-21T16:48:54Z" level=info msg="[filebeat] Stopping"
time="2017-12-21T16:48:54Z" level=error msg="[winlogbeat] Backend finished unexpectedly, trying to restart 2/3."
time="2017-12-21T16:48:54Z" level=info msg="[winlogbeat] Stopping"
time="2017-12-21T16:48:56Z" level=info msg="[filebeat] Starting (exec driver)"
time="2017-12-21T16:48:56Z" level=info msg="[winlogbeat] Starting (exec driver)"
time="2017-12-21T16:48:57Z" level=error msg="[filebeat] Backend finished unexpectedly, trying to restart 3/3."
time="2017-12-21T16:48:57Z" level=info msg="[filebeat] Stopping"
time="2017-12-21T16:48:57Z" level=error msg="[winlogbeat] Backend finished unexpectedly, trying to restart 3/3."
time="2017-12-21T16:48:57Z" level=info msg="[winlogbeat] Stopping"
time="2017-12-21T16:48:59Z" level=info msg="[filebeat] Starting (exec driver)"
time="2017-12-21T16:48:59Z" level=info msg="[winlogbeat] Starting (exec driver)"
```
But the files are installed in the default path.

Is it possible in the collector-sidecar-0.1.4.tar.gz?

### Steps to reproduce the problem
1. Download the collector-sidecar-0.1.4.tar.gz on windows host.
2. Try to install the collector sidecar in the specific directory.
 
### Environment

* Sidecar Version: 0.1.4
* Graylog Version: 2.3.0
* Operating System: Windows 2008 R2
* Elasticsearch Version: 5.6.4
* MongoDB Version: v3.2.17

**Comment by jalogisch** [comment]
Just follow the Documentation: http://docs.graylog.org/en/2.4/pages/collector_sidecar.html#configuration

- place the .exe where ever you want
- run it the the `-c your_custome_configuration.yml` 

In that custome configuration you are able to define all locations yourself.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
