### ISSUE TITLE
nxlogs fillung up the harddrive

### ISSUE THREAD

**Issue by mrfreezer** [Graylog2/collector-sidecar#22]
### Problem description

nxlogs fill up your harddrive pretty quick with 2016-05-26 12:11:04 ERROR failed to open directory: /var/www/xxxxx: Permission denied entries when using a recursive file-input

### Steps to reproduce the problem

define a collector entry with a wildcard-entry (/var/www/*.log) and enable recursion.

if nxlog can't access this path it puts an error into nxlog as well as in nxlog_stderr.log.

if you do this with some larger structure this can lead to logfiles using 60gb within 24 hours. so even logrotation doesnt help you much.

even if this is basically my own mistake it shouldnt break the system by filling its harddisks...

### Environment

* Sidecar Version: 0.0.7
* Graylog Version: 2.0.1
* Operating System: ubuntu 14.04

**Comment by mariussturm** [comment]
Hi,
thanks for the feedback!
So the reason for writing this log is something we can't influence much. But the size of the stdout file should be limited. I will check what we can do there.

**Comment by mrfreezer** [comment]
welcome.
maybe its somehow possible to make nxlog rotate its logfiles on size additionally to the daily base und add this part of the code to the default-snippet?!

**Comment by mariussturm** [comment]
This is fixed with d5a2c04640b6c65d5ad6ad9941308a81e1779c83
You can now configure a time in seconds the Sidecar will rotate the *_stderr and *_stdout logs. With log_max_age you can set a time where old log files will be deleted after.
