### ISSUE TITLE
Use hostname as node_id in default configuration

### ISSUE THREAD

**Issue by bernd** [Graylog2/collector-sidecar#226]
### Problem description

The default configuration in the sidecar packages sets a node id:
```
node_id: graylog-collector-sidecar
```

If the user forgets to change this setting, all sidecars in the Graylog UI will have the same name. This is confusing. Since we are falling back to the hostname if `node_id` is not set anyway, I think we can remove the default setting so every sidecar defaults to the hostname.

### Environment

* Sidecar Version: 0.1.5

**Comment by mariussturm** [comment]
Sounds good to me, see PR #227
