### ISSUE TITLE
Enable TLS with Nxlog

### ISSUE THREAD

**Issue by dannyz29** [Graylog2/collector-sidecar#23]
### Problem description
I'm trying to setup collector sidecar with a nxlog backend to ship logs using TLS.

I've enabled TLS on my TCP GELF input, specifying the cert and private key. I then went on to configure the collector, only to find out that there are no TLS settings on the collector config. 
nxlog.log on the client show the following error: "ERROR om_tcp detected a connection error;Connection reset by peer".

Am I missing something? Do I need to write a custom nxlog snippet to enable the ssl module?
Here is an example config just to make my question clear:  #https://www.loggly.com/docs/nxlog-tls-configuration/

### Steps to reproduce the problem

1. Enable TLS on a GELF TCP input
2. Setup client OS with collector sidecar and nxlog backend
3. Configure collector in Graylog GUI (system\collectors --> collectors)
4. I used a nxlog file input and a TCP GELF ouput.
5. Go to the client, wait for the sidecar to apply new collector config and watch nxlog.log.

### Environment

* Sidecar Version: 0.0.8
* Graylog Version: 2.0.1
* Operating System: centos 6

**Comment by mariussturm** [comment]
We have added a nxlog-gelf-tls output in the master branch of the collector plugin: https://github.com/Graylog2/graylog-plugin-collector
You can build it and replace the default version of the plugin or wait till 2.1 where the new version will be included.

**Comment by dannyz29** [comment]
Thanks that's very helpful. I'll wait for the new version.
