### ISSUE TITLE
Log collection time error

### ISSUE THREAD

**Issue by xutao3653** [Graylog2/collector-sidecar#231]
### Problem description
When logs are sent to graylog, they are not sorted according to time, but have errors.
### Steps to reproduce the problem

1. look
![graylog_time](https://user-images.githubusercontent.com/6148257/38787874-36c80b44-4163-11e8-91fa-174e90b57f44.png)

who can help me,thanks very mach!!!
### Environment

* Sidecar Version:collector-sidecar-0.1.4-1.x86_64
* Graylog Version:Graylog 2.4.3+2c41897 
* Operating System:Centos7
* Elasticsearch Version:elasticsearch-5.6.3
* MongoDB Version:

**Comment by joschi** [comment]
@xutao3653 Which log collector are you using (please include the exact version and the complete configuration) and are you extracting the timestamp from the text message correctly?

**Comment by xutao3653** [comment]
@joschi thank you for answer.
Sidecar Version:collector-sidecar-0.1.4-1.x86_64
i use filebeat
![filebeat](https://user-images.githubusercontent.com/6148257/38799244-83b1bba2-4196-11e8-9673-4f32f47a45a7.png)

Timestamps are sorted correctly in source logs, but they are wrong after collecting graylog.

**Comment by xutao3653** [comment]
@joschi 
and Concurrency：
In 22,323 / Out 21,558 msg/s

3 nodes for graylog
6 nodes for es

**Comment by joschi** [comment]
@xutao3653 Filebeat only collects the raw text files but doesn't parse anything.

So the timestamps you see in the "timestamp" field in Graylog is the time when Filebeat read the log message but not the timestamp inside your log messages.

If you want to use the timestamps from your log messages, you'll have to use extractors or pipeline rules to extract those and set the "timestamp" field accordingly.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by xutao3653** [comment]
@joschi I see what you mean, but when log is collected to graylog, it doesn't follow the sorting in source log, which is the key of the problem.

Thank you!
