### ISSUE TITLE
NODE_ID option on command line isn't working for collector sidecar 1.5-1

### ISSUE THREAD

**Issue by MiddleGeorgiaState** [Graylog2/collector-sidecar#233]
### Problem description
NODE_ID option on command line isn't working for collector sidecar 1.5-1. I've even tried leaving it off the command line to get it to set it to hostname. That doesn't work either. Setting it to "" also doesn't work. The id's are all set to graylog-collector-sidecar in Graylog.

### Steps to reproduce the problem
1. ... Run the installation with this command line
collector_sidecar_installer_0.1.5-1 /S -SERVERURL=https://fqdn:9000/api -NODE_ID="servername" -TAGS="windows" -NXLOG_ENABLED=true -WINLOGBEAT_ENABLED=false -FILEBEAT_ENABLED=false

2. ... C:\Program Files\Graylog\collector_sidecar.yml looks like this

server_url: https://fqdn:9000/api 
update_interval: 10
tls_skip_verify: false
send_status: true
list_log_files:
node_id: graylog-collector-sidecar
collector_id: file:C:\Program Files\graylog\collector-sidecar\collector-id
cache_path: C:\Program Files\graylog\collector-sidecar\cache
log_path: C:\Program Files\graylog\collector-sidecar\logs
log_rotation_time: 86400
log_max_age: 604800
tags: [windows]
backends:
    - name: nxlog
      enabled: true
      binary_path: C:\Program Files (x86)\nxlog\nxlog.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\nxlog.conf
    - name: winlogbeat
      enabled: false
      binary_path: C:\Program Files\graylog\collector-sidecar\winlogbeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml
    - name: filebeat
      enabled: false
      binary_path: C:\Program Files\graylog\collector-sidecar\filebeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\filebeat.yml

### Environment

* Sidecar Version:1.5-1
* Graylog Version: v2.4.4+4659dbe
* Operating System: Windows Server 2012 R2 and Windows Server 2008 R2
* Elasticsearch Version: not sure
* MongoDB Version: not sure

**Comment by MiddleGeorgiaState** [comment]
NODEID works. The documentation at http://docs.graylog.org/en/2.4/pages/collector_sidecar.html says to use NODE_ID. 

This example works:
collector_sidecar_installer_0.1.5-1 /S -serverurl=https://fqdn:9000/api -TAGS="windows" -NODEID="%COMPUTERNAME%" -NXLOG_ENABLED=true -WINLOGBEAT_ENABLED=false -FILEBEAT_ENABLED=false

Also, the documentation says NODE_ID is the "Name of the Sidecar instance, will also show up in the web interface. Hostname will be used if not set." If not set or set to "", "graylog-collector-sidecar" is what is actually used in this release. Using hostname as default would be better.

**Comment by joschi** [comment]
@MiddleGeorgiaState Thanks for reporting this!

The `node_id` setting in the YAML configuration file and the `NODEID` command line parameter are different things.

This being said, the official documentation should include an explanation of the command line parameters (like the README does: https://github.com/Graylog2/collector-sidecar/blob/0.1.5/README.md#installation) and of the configuration settings in the YAML configuration file.

**Comment by mdobson90** [comment]
I found it was easier to leave the default settings for the sidecar .yml config file as unchanged from the initial install, then use a simple script to replace the yml file with a configured one. 
Assuming you're wanting to use the %HOSTNAME% variable, just leave NODEID blank in the "configured" yml file you intend to copy over, set the SERVER URL and Agent Tags to whichever tag-group you want and replace the file. There aren't any unique id's or anything in this yml file, unlike the winlogbeat ymls.

**Comment by mpfz0r** [comment]
This should be fixed with: https://github.com/Graylog2/collector-sidecar/issues/339

Closing
