### ISSUE TITLE
Shipping forwarded events from Windows Event Forwarding host fails

### ISSUE THREAD

**Issue by harmane** [Graylog2/collector-sidecar#235]
### Problem description

WEF set up on W2K12R2 host with subscriptions to Forwarded Events log. Shipping to Graylog fails when created beat uses `Forwarded Events` as Windows Event. Setting WE's to `Application`, `Security` and/or `System` works without issue. Confirmed `Forwarded Events` winlog exists.
### Steps to reproduce the problem

1. Create input beat of winlogbeat type with Windows Events as `[{'name':'Forwarded Events'}]`
2. Restart collector
3. Observe on WEF host in winlogbeat log:

`2018-06-19T11:00:50-04:00 INFO winlogbeat start running.`
`2018-06-19T11:00:50-04:00 ERR  Error: The service process could not connect to the service controller.`
`2018-06-19T11:00:50-04:00 WARN EventLog[Forwarded Events] Open() error. No events will be read 
        from this source. The specified channel could not be found. Check channel configuration.`
`2018-06-19T11:00:50-04:00 INFO Uptime: 50.0031ms`
`2018-06-19T11:00:50-04:00 INFO winlogbeat stopped.`

### Environment

* Sidecar Version: 1.6-1
* Graylog Version: 2.4.5+8e18e6a
* Operating System: W2K12R2

**Comment by joschi** [comment]
@harmane Please post the complete configuration of the Graylog Collector Sidecar, the generated Winlogbeat configuration, and the configuration/configuration snippets you've created in Graylog.

**Comment by harmane** [comment]
I've not created any snippets in Graylog, just configured an output beat (winlogbeat) for my remote host and an input beat (windows-event-log) that uses said output beat with configuration tags that match gcs config. Very simple setup.


# generated winlogbeat.yml

fields:
  collector_node_id: gcs-winevt
  gl2_source_collector: 03525ac3-677d-4b1f-b483-95c3577df17a
output:
  logstash:
    hosts:
    - remote-host:5044
path:
  data: C:\Program Files\graylog\collector-sidecar\cache\winlogbeat\data
  logs: C:\Program Files\graylog\collector-sidecar\logs
tags:
- windows
- iis
winlogbeat:
  event_logs:
  - name: Forwarded Events


# collector_sidecar.yml:

server_url: http://remote-host:9000/api 
update_interval: 10
tls_skip_verify: true
send_status: true
list_log_files:
node_id: gcs-winevt
collector_id: file:C:\Program Files\graylog\collector-sidecar\collector-id
cache_path: C:\Program Files\graylog\collector-sidecar\cache
log_path: C:\Program Files\graylog\collector-sidecar\logs
log_rotation_time: 86400
log_max_age: 604800
tags: [windows, iis]
backends:
    - name: nxlog
      enabled: false
      binary_path: C:\Program Files (x86)\nxlog\nxlog.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\nxlog.conf
    - name: winlogbeat
      enabled: true
      binary_path: C:\Program Files\graylog\collector-sidecar\winlogbeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml
    - name: filebeat
      enabled: false
      binary_path: C:\Program Files\graylog\collector-sidecar\filebeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\filebeat.yml

**Comment by joschi** [comment]
Are you sure that the name is "Forwarded Events" (with a space) and not "ForwardedEvents" (without space)?

What's the output of the following Powershell command?
(https://www.elastic.co/guide/en/beats/winlogbeat/5.6/configuration-winlogbeat-options.html#configuration-winlogbeat-options-event_logs-name)
```text
C:\> Get-WinEvent -ListLog * | Format-List -Property LogName
```

Have you read about the [`event_logs.forwarded`](https://www.elastic.co/guide/en/beats/winlogbeat/5.6/configuration-winlogbeat-options.html#_event_logs_forwarded) setting?

**Comment by harmane** [comment]
That was it. I was under the impression it was similar to winlogbeat config for ELK stack which uses the logical name (Forwarded Events) as opposed to channel name. Thank you.

Is there any way to import archived event logs as well ie Archive-ForwardedEvents-[DATE]?

**Comment by joschi** [comment]
> Is there any way to import archived event logs as well ie Archive-ForwardedEvents-[DATE]?

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
