### ISSUE TITLE
"static build" filebeat in rpm packages should "strip -s" to reduce size

### ISSUE THREAD

**Issue by lxf1992521** [Graylog2/collector-sidecar#241]
The "filebeat" in rpm packages is too huge to download by yum when dealing with lots of machines.

After stripped "filebeat" by command "strip -s", the size from 50M reduce to 26M

**Comment by joschi** [comment]
@lxf1992521 We're shipping the pristine Filebeat binary so that bug reports against any shipped agent won't be tainted.

If you want the binary size of Filebeat to be reduced by stripping debug symbols, please file a bug report at https://github.com/elastic/beats/issues.
