### ISSUE TITLE
Crash on Launch on Server 2016

### ISSUE THREAD

**Issue by Chirishman** [Graylog2/collector-sidecar#246]
### Problem description

Alpha crashes on launch on Server 2016

### Steps to reproduce the problem

1. Install collector-sidecar on Server 2016
1. Install the service and attempt to start it

### Environment

* Sidecar Version: 1.0.0-alpha.1
* Graylog Version:
* Operating System: Windows Server 2016 - Version: 10.0.14393 - Build: 14393
* Elasticsearch Version:
* MongoDB Version:

**Comment by bernd** [comment]
@Chirishman Are there any messages during startup/crash? If so, please add them to this issue. Thank you!

**Comment by jalogisch** [comment]
as we did not get any feedback on this, i'll close it. 

@Chirishman if you can add more details, please reopen.
