### ISSUE TITLE
server_url does not use path

### ISSUE THREAD

**Issue by truthsolo** [Graylog2/collector-sidecar#25]
### Problem description

Any trailing path in collector-sidecar's server_url is ignored.  This prevents the use of a single port for Graylog Server web and API services on a proxy frontend.

### Steps to reproduce the problem

1. Proxy web and API requests to Graylog Server through a single port, with the API available at "/api" (set with web_endpoint_uri in graylog-server).
2. Set the server_url for collector-sidecar to graylog-server's web_endpoint_uri (e.g., https://wat.tld/api)
3. collector-sidecar will send GET and PUT requests to https://wat.tld/ instead of https://wat.tld/api/.

### Environment

* Sidecar Version: 0.0.8-1
* Graylog Version: 2.0.2-1
* Operating System: CentOS 7 x86_64
* Elasticsearch Version: 2.3.3-1
* MongoDB Version: 3.2.6-1

**Comment by mariussturm** [comment]
Thanks for the feedback! This issue is fixed through d1110ff1bf130cdb7c5700ccc9a788cbeef58c48 and should be part of the next release.
