### ISSUE TITLE
Mismatch between installation and log/cache directories on windows

### ISSUE THREAD

**Issue by bernd** [Graylog2/collector-sidecar#257]
### Problem description

The windows installer installs the sidecar files into `C:\Program Files (x86)` or `C:\Program Files` depending on the architecture.

https://github.com/Graylog2/collector-sidecar/blob/67efefc73b800c42ef58d0efc4751b758b9b6342/dist/recipe.nsi#L83-L92

In our go code and the example configurations we are always using `C:\Program Files`. As far as I can see, this means we are writing files into two different directories. Installation files into `C:\Program Files (x86)` and generated configs, logs and cache data into `C:\Program Files`.

https://github.com/Graylog2/collector-sidecar/blob/67efefc73b800c42ef58d0efc4751b758b9b6342/sidecar-windows-example.yml#L19

https://github.com/Graylog2/collector-sidecar/blob/67efefc73b800c42ef58d0efc4751b758b9b6342/sidecar-windows-example.yml#L52-L58

https://github.com/Graylog2/collector-sidecar/blob/67efefc73b800c42ef58d0efc4751b758b9b6342/context/context.go#L87

https://github.com/Graylog2/collector-sidecar/blob/67efefc73b800c42ef58d0efc4751b758b9b6342/main.go#L52

In the example config we should probably add a placeholder for the installation directory that gets replaced by the windows installer. (like we do for other values) For the default values in the go code, we can probably detect the architecture and use the correct directory.

### Environment

* Sidecar Version: 1.0.0-alpha.2 (rev 67efefc)

**Comment by mariussturm** [comment]
Since we ship both 32bit and 64bit binaries the installation path should always be `C:\\Program Files\`. The code in question is just using the right system variable for the platform. Were you able to install the Sidecar in `C:\\Program Files(x86)\` in some combination? That would be a bug then, but I couldn't reproduce that case.
