### ISSUE TITLE
Reflect latest changes in the collector default template

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/collector-sidecar#267]
Latest path changes should be reflected in the default template for each collector, see

https://github.com/Graylog2/collector-sidecar/commit/f15144a878708ef3ef6ff04bacb2cd4c425df1a4
and 
https://github.com/Graylog2/collector-sidecar/pull/258/commits/ce688f3da6ee962bf5fdbc990dab205f1793b4a2

**Comment by mpfz0r** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/pull/5104
