### ISSUE TITLE
syntax inconsistency  @ multiline regex

### ISSUE THREAD

**Issue by mrfreezer** [Graylog2/collector-sidecar#27]
### Problem description

while other regex' are noted without the surrounding slashes the multiline regex needs the slashes since nxlog wants them

### Steps to reproduce the problem

define collector configuration
define output
define collector input using nxfile input
enable multiline
add a regex of your choice (without slashes)
save the input

examine the nxlog-logfile (usually /var/log/graylog/collector-sidecar/nxlog.log) for something like

2016-06-14 15:24:44 ERROR couldn't parse expression at line 11, character 14 in /etc/graylog/collector-sidecar/generated/nxlog.conf;syntax error, unexpected ^, expecting $end
2016-06-14 15:24:44 ERROR invalid expression in 'HeaderLine' at /etc/graylog/collector-sidecar/generated/nxlog.conf:11

as soon as you enclose the regex in slashes it works. but this is somewhat inconsistent to the other regex's used inside graylog. maybe the collector sidecar should do this for the user or there could at least be a hint inside the webinterface.

### Environment

* Sidecar Version: 0.0.7 / 0.0.8
* Graylog Version: 2.0.1
* Operating System: Ubuntu 14.04

**Comment by mariussturm** [comment]
Fixed by 0d4397199e03ba0f6686dd5aff21fa7a31fa3d13
