### ISSUE TITLE
Alpha version not working on non 3.0 Graylog

### ISSUE THREAD

**Issue by webtroter** [Graylog2/collector-sidecar#270]
### Problem description
The warning that alpha release doesn't work on <2.x Graylog is not present on the recent releases.

Can you please add it in the future?

![inkedscreenshot_2018-08-03 graylog2 collector-sidecar_li](https://user-images.githubusercontent.com/8386808/43659391-e7681248-9729-11e8-9caa-e33fc2b7473d.jpg)

### Steps to reproduce the problem

1. Try to download a release

**Comment by mariussturm** [comment]
I have added the warning to the releases where it was missing.
