### ISSUE TITLE
side car collector and nxlog

### ISSUE THREAD

**Issue by ELmane** [Graylog2/collector-sidecar#28]
### Problem description
can't use nxlog buffer when using collector side car

### Environment

* Sidecar Version:  collector-sidecar-0.0.7-1.i386.rpm
* Graylog OVA Version: v2.0.2
* Operating System: centos

**Comment by mariussturm** [comment]
For the record: to fix this, a more flexible routing configuration is needed. While the usually route looks like `input->output` a buffered route would look like `input->buffer->output`

**Comment by ELmane** [comment]
are you going to include this in the future version of graylog ???

**Comment by mariussturm** [comment]
I think it's a good idea to have buffers in place to not lose messages during a reconnect. Could take a while but post Graylog 2.1 this will be build, yes.

**Comment by mariussturm** [comment]
A simple version of this will be in 2.1. There is now an option to enable a 16MB ram buffer for each nxlog output.
