### ISSUE TITLE
Bundled filebeat has a memory leak

### ISSUE THREAD

**Issue by dmuntean** [Graylog2/collector-sidecar#283]
### Problem description
Bundled filebeat has a memory leak (https://github.com/elastic/beats/issues/6797). This was fixed in version 6.3.0.

The issue appears when filebeat is configured to monitor files that it doesn't have permissions to open. More information via the link to the issue.

Could you please update bundled filebeat to the latest 6.x ?

### Steps to reproduce the problem

1. Setup collector to monitor files that it doesn't have permissions to open
2. Filebeat starts leaking memory

### Environment

* Sidecar Version: 0.1.6-1
* Graylog Version: 2.4.6-1
* Operating System: Ubuntu 16.04.5
* Elasticsearch Version: N/A
* MongoDB Version: N/A

**Comment by mpfz0r** [comment]
Fixed in Sidecar 0.1.7
