### ISSUE TITLE
Default winlogbeat collector Executable Path is wrong

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/collector-sidecar#289]
### Problem description

The default install location is ``C:\Program Files\Graylog\sidecar\winlogbeat.exe``

The GUI default however is ``C:\Program Files\graylog\collector-sidecar\winlogbeat.exe``

I guess the same applies for the Configuration Path:  ``collector-sidecar`` vs ``sidecar``
### Environment

* Sidecar Version: 1.0

**Comment by edmundoa** [comment]
I guess this is part of the renaming of entities we did, and we should adapt the web interface in this case to show the correct default values. @mariussturm what do you think?

**Comment by mariussturm** [comment]
Yes, make sense to me!
