### ISSUE TITLE
Possible for generated Output to use hostname() rather than hostname_fqdn() for Hostname?

### ISSUE THREAD

**Issue by stepkirk** [Graylog2/collector-sidecar#29]
### Problem description
Using Graylog Collector Sidecar to configure NXLog on a CentOS 6.5 host.
Here is the resulting generated output in /etc/graylog/collector-sidecar/generated/nxlog.conf

<Output 57605344ed60c703b0fa7290>
        Module om_tcp
        Host scmgraylog-server.ghx.com
        Port 12201
        OutputType  GELF_TCP
        Exec $short_message = $raw_event; # Avoids truncation of the short_message field.
        Exec $gl2_source_collector = '6f145fef-5841-49ad-8b36-80c4a69a1568';
        Exec $Hostname = hostname_fqdn();
</Output>

Unfortunately, the Hostname gets set to localhost.localdomain on this host which makes searching by source in Graylog a little difficult.  I think if $Hostname could be set to hostname() rather than hostname_fqdn() in the above generated file, the problem would be solved.  Even if hostname_fqdn() returned the "real" FQDN of this host, I would rather have the option to set to the shortname.

Is this possible?  Something I can fix with a Snippet? 

### Environment

* Sidecar Version: 0.0.8
* Graylog Version: 2.0.2
* Operating System: CentOS 6.5

Thanks.

**Comment by mariussturm** [comment]
Hi,
hostname_fqdn() has already a build-in fallback to hostname() when there is no dns name available. That's why we hard wired it into the configuration. So I think the hostname configuration for that particular node is pretty broken. It is providing a dns name that resolves to 'localhost.localdomain'. Is it not possible to setup a proper hostname? This is needed for other services aswell.

**Comment by stepkirk** [comment]
Thanks for the feedback Marius.

You are correct that the host could have done a better job of figuring out its FQDN.  I fixed that issue by modifying /etc/nsswitch.conf to query dns before looking in the local /etc/hosts files which is where it was getting the localhost.localdomain name from.

Still, it would be nice to have the option to choose the shortname over the FQDN for the source in Graylog.  This would match the shortnames that get pulled from the syslog messages that get pushed into Graylog from our syslog-ng servers.

There is probably a way to massage the FQDN down to a shortname using an extractor but I was hoping to have the option to "fix" it on the sending side.

Thanks again for the reply.

**Comment by mariussturm** [comment]
Closing this for now, I think there will be some improvements when #26 is implemented.
