### ISSUE TITLE
Global Static Fields 

### ISSUE THREAD

**Issue by schwatvogel** [Graylog2/collector-sidecar#30]
### Adding Fields to systems not only Input Files
Need to add a Static Field to a Host, not only a Input 

### Steps to reproduce
At the moment you would have to add the Field to every InputFile you define for a Host, (eg. environment=development)
tedious in large environments with multiple Microservices per Host.

### Suggestions

- Same functionality as in `fileInputsToString()` for `outputsToString()` So you could add "global" Fields
- Automatically add the tags from sidecar.yml as static fields

### Environment

* Sidecar Version: 0.8
* Graylog Version: 2.0.2 (4da1379)
* Operating System: Ubuntu 14.04

**Comment by mariussturm** [comment]
I have added the same `Additional Fields` functionality from the Inputs to the Outputs. In this way it's not fully global but at least you can add fields for a complete configuration set: e602f4566c7586ae490e42fb2a1860096060fc3e
