### ISSUE TITLE
[feature request] let sidecar support kafka buffer

### ISSUE THREAD

**Issue by xuziheng1002** [Graylog2/collector-sidecar#305]
We used graylog to collect logs in production environment , but Graylog-Input became a performance bottleneck,  so we wanted to use Kafka for buffer, and hoped that sidecar would support output to Kafka

**Comment by jalogisch** [comment]
I'm closing this issue, as it is duplicating https://github.com/Graylog2/graylog2-server/issues/5254. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
