### ISSUE TITLE
Supervise Backend Services

### ISSUE THREAD

**Issue by schwatvogel** [Graylog2/collector-sidecar#31]
### Problem description
Having the backend process crash or beeing killed is not deteced by the sidecar service. 
Leading to Lost logs

### Steps to reproduce the problem

1. start sidecar service
2. stop backendprocess (`killall nxlog`)

### Environment

* Sidecar Version: 0.8
* Graylog Version: 2.0.2 (4da1379)
* Operating System: Ubuntu 14.04

**Comment by mariussturm** [comment]
Fixed through e7e77b0e5d68d2d5ffe47c085278e9fe9f548afc
