### ISSUE TITLE
Greylog sidecar problem with getting hosts from web interface

### ISSUE THREAD

**Issue by lundbergaj** [Graylog2/collector-sidecar#314]
I have setup a graylog server, and want to get windows logs, but am having trouble with the configuration. The generated winlogbeat.yml uses a localhost:5044 address. It's my understanding that it gets the address from my graylog server, from the collector configuration for the matching Beats Output. The winlogbeat is collecting logs, just doesn't send them to the graylog server. If I change the winlogbeat.yml to point to my server, it works for 10 minutes, then overwrites the address to point back to localhost:5044.

### Steps to reproduce the problem

I already had graylog installed and working usuing rsyslog on Linux type machines, but also need to log some Windows 7 machines. 

On the windows machines I add
192.168.3.210 graylog.equinox
to my hosts file.
I then run the graylog collector sidecar install as an administrator (I was using v0.1.6). I use the name Conference for the machine in question. I was just using winlogbeat, and not filebeat, so I edit the collector_sidecar.yml and
change the filebeat setting to FALSE.
To generate a winlogbeat.yml file, I execute the graylog_collector_sidecar program as an administrator.

I then go to graylog.equinox/api in a browser window and under system/collectors
add a collector for the new machine, and define winlogbeat output then input.
Do this on the windows machine to collect logs from. For the output, I set the hosts to ['192.168.3.210:5044'].

I also start the graylog collecter service. Winlogbeat does collect logs, and puts them into directories as specificed by the graylog collector yml. If I edit the winlogbeat.yml file to point to 192.168.3.210 instead of localhost, it does send the logs as desiredm but after 10 minutes, it updates the winlogbeat.yml file and stops sending logs.

So, I seem to be misunderatnding how to instruct the sidecar where the logs should go, or somehow the collector isn't able to get my instructions from the web interface.

What log or debug information should I look at next?

### Environment

Sidecar version 0.1.6
Graylog version 2.4.6
Windows 7 on computer being logged
Ubuntu 16.01.1 on Graylog server
Elastisearch version 5.6.13
MongoDB version 2.6.10

**Comment by mpfz0r** [comment]
Hi,

it seems that you did not configure the beats collector output.
(The default value there is `localhost:5044`)

Also did you assign tags to your configuration?

Could you retrace your steps following this guide and make sure everything is correct?
http://docs.graylog.org/en/2.4/pages/collector_sidecar.html#step-by-step-guide

**Comment by jalogisch** [comment]
This issue is closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
