### ISSUE TITLE
[feature request] Manage processors and routes on nxlog backend

### ISSUE THREAD

**Issue by juanjo-s2** [Graylog2/collector-sidecar#316]
### Problem description
Currently we are using processors, but there is no way to manage them or to use them in a route from collector configuration.

One solution could be adding a section for processors in the collector configuration management page, and other to create the routes, where you choose an Input, none or more processors, and an Output, removing the "Forward to" field on the Input configuration.

### Steps to reproduce the problem

1. Try to define processors and use them in routes

### Environment

* Sidecar Version: 2.2.2
* Graylog Version: 2.2.2+691b4b7
* Operating System: CentOS 7
* Elasticsearch Version: 2.2
* MongoDB Version: N/A

**Comment by mariussturm** [comment]
Hi, thanks for the feedback!
In the upcoming 3.0 release you can edit the configuration file directly so this should be no problem anymore.
