### ISSUE TITLE
Windows service handling improvements

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/collector-sidecar#319]
We need to think about how users are supposed to upgrade their sidecar to the
new version.

Right now a user cannot simply install the new sidecar (1.0) over an existing
older installation.
One problem is that the windows `service name` got changed, but not the 
`Display name`.
That's why the new sidecar is not able to register itself as a service,
nor is it able to uninstall the old sidecar's service.

There are probably more issues, we can add here...

**Comment by bernd** [comment]
@mpfz0r Can we change the `Display name`?

**Comment by mpfz0r** [comment]
> @mpfz0r Can we change the `Display name`?

I think that would improve things slightly.
However, I just noticed the same problem if you rename a collector:
```
time="2018-12-13T05:17:37-08:00" level=info msg="Adding process runner for: nxlog-windows-old" 
time="2018-12-13T05:17:37-08:00" level=info msg="[nxlog-windows-old] Configuration change detected, rewriting configuration file." 
time="2018-12-13T05:17:37-08:00" level=error msg="[nxlog-windows-old] Can't get status of service graylog-collector-nxlog-windows-old cause it doesn't exist: The specified service does not exist as an installed service." 
time="2018-12-13T05:17:37-08:00" level=error msg="[nxlog-windows-old] Failed to install service: The name is already in use as either a service name or a service display name." 
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x52c459]
```
