### ISSUE TITLE
Show Messages from collector not working

### ISSUE THREAD

**Issue by jcspino** [Graylog2/collector-sidecar#32]
### Problem description
On some of my collectors the "Show Messages" button that then querys the collector ID returns to resutls. I can server for the server the collector is installed on as the source and I see messages so I know the collector is working. I am using the NXLog backend and there seems to be no pattern bewteen the servers where the command works and where it doesnt. I cannot find any errors/messages on either server or client indicating a problem. 

### Steps to reproduce the problem

1. Install graylog collector sidecarwith nxlog as backend
2. send in logs and then find that you cannot view logs by collector ID. 

### Environment

* Sidecar Version: 0.8
* Graylog Version: 2.0.2
* Operating System: windows server 2012 (sidecar)/ CENTOS7 (Graylog)
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2.6

**Comment by edmundoa** [comment]
Hi,

I am sorry, but I don't really understand the issue you are describing. When you write 
> On some of my collectors the "Show Messages" button that then querys the collector ID returns to resutls.

Do you mean that when you click on "Show messages" for a collector the search displays no messages for it?

If that's the case, would you be so kind as to share with us the URL generated when you click on "Show messages" for the collector?

Thank you!

**Comment by mariussturm** [comment]
And could you please also include the generated nxlog configuration?

**Comment by jcspino** [comment]
this was user error, my apologizes!
