### ISSUE TITLE
Cannot input log to remote

### ISSUE THREAD

**Issue by appop** [Graylog2/collector-sidecar#33]
### Steps to reproduce the problem

1.sudo nxlog -v -f /etc/graylog/collector-sidecar/generated/nxlog.conf
2016-06-28 08:15:56 INFO configuration OK
2.tail -f /var/log/messages
Jun 28 08:13:46 M3 /usr/bin/graylog-collector-sidecar[17473]: time="2016-06-28T08:13:46Z" level=info msg="[RequestConfiguration] No configuration found for configured tags!"
Jun 28 08:13:56 M3 /usr/bin/graylog-collector-sidecar[17473]: time="2016-06-28T08:13:56Z" level=info msg="[RequestConfiguration] No configuration found for configured tags!"
Jun 28 08:14:06 M3 /usr/bin/graylog-collector-sidecar[17473]: time="2016-06-28T08:14:06Z" level=info msg="[RequestConfiguration] No configuration found for configured tags!"
Jun 28 08:14:16 M3 /usr/bin/graylog-collector-sidecar[17473]: time="2016-06-28T08:14:16Z" level=info msg="[RequestConfiguration] No configuration found for configured tags!"
Jun 28 08:14:26 M3 /usr/bin/graylog-collector-sidecar[17473]: time="2016-06-28T08:14:26Z" level=info msg="[RequestConfiguration] No configuration found for configured tags!"
Jun 28 08:14:36 M3 /usr/bin/graylog-collector-sidecar[17473]: time="2016-06-28T08:14:36Z" level=info msg="[RequestConfiguration] No configuration found for configured tags!"
Jun 28 08:14:46 M3 /usr/bin/graylog-collector-sidecar[17473]: time="2016-06-28T08:14:46Z" level=info msg="[RequestConfiguration] No configuration found for configured tags!"
3.[root@M3 neal]$cat /etc/graylog/collector-sidecar/collector_sidecar.yml
server_url: http://172.15.5.174:12900
tls_skip_verify: false
node_id: graylog-collector-sidecar
collector_id: file:/etc/graylog/collector-sidecar/collector-id
tags:
    - linux
    - apache
log_path: /var/log/graylog/collector-sidecar
update_interval: 10
backends:
    - name: nxlog
      enabled: true
      binary_path: /usr/bin/nxlog
      configuration_path: /etc/graylog/collector-sidecar/generated/nxlog.conf

4.cat /etc/graylog/collector-sidecar/generated/nxlog.conf
########################################
# Global directives                    #
########################################
User root
Group root

LogFile /var/log/nxlog/nxlog.log
LogLevel INFO

########################################
# Modules                              #
########################################
<Extension gelf>
    Module      xm_gelf
</Extension>
<Input in>
        Module  im_file
        File    "/var/log/messages"
</Input>
<Output out>
    Module      om_udp
    Host        172.31.5.174
    Port        12202
    OutputType  GELF
</Output>
<Route 1>
    Path        in => out
</Route>

### Environment

* Sidecar Version:
Graylog Collector Sidecar version 0.0.8 (amd64)
* Graylog Version:
2.03
* Operating System:
Amazon Linux AMI release 2014.09
* Elasticsearch Version:

* MongoDB Version:
3.2

**Comment by mariussturm** [comment]
The Sidecar is generating a configuration file for nxlog please dont use the example configuration from nxlog. Just make the directory  /etc/graylog/collector-sidecar/generated writeable for the sidecar user. Then go to the Graylog web UI and create a file input under `System -> Collectors -> Manage configurations` and apply a tag that matches a tag from your sidecar configuration (in your case `linux` or `apache`)
