### ISSUE TITLE
 Does sidecar now have versions that support graylog 2.5.1?

### ISSUE THREAD

**Issue by linux0x5c** [Graylog2/collector-sidecar#333]
Does sidecar now have versions that support graylog 2.5.1?

**Comment by mariussturm** [comment]
Hi,
you can still use the current stable 0.1.7 for Graylog server 2.5.x. Once 3.0 is released you have to switch to Sidecar 1.x.

**Comment by linux0x5c** [comment]
okay,thanks

**Comment by mpfz0r** [comment]
> Hi,
> you can still use the current stable 0.1.7 for Graylog server 2.5.x. Once 3.0 is released you have to switch to Sidecar 1.x.

Just a minor correction to what marius said: only graylog >= 2.5.1 will support 0.1.7 or older.
And in 3.0 you'll have the choice between Sidecar 1.x and 0.1.x.
However, we're gonna retire support for 0.1.x at some point in the future.
