### ISSUE TITLE
Remove metrics variables from template engine

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/collector-sidecar#338]
### Problem description
If a Sidecar doesn't send metric information but a configuration with e.g. `${sidecar.load1}` is assigned, the template generation is failing. Because of the disabled status informations the user doesn't get any feedback about the failed template. We should remove all metric variables from the template context as there are no real world use-cases yet.

### Steps to reproduce the problem
`send_status: false`
+
 `${sidecar.load1}` in an active template

### Environment

* Sidecar Version: 1.0.0-rc.1
* Graylog Version: 3.0.0-rc.1

**Comment by bernd** [comment]
We need to keep backwards compatibility in mind. What happens if a user is using one of the removed variables in their templates?

**Comment by deeshe** [comment]
@mariussturm It should be fixed for 3.0 because it would be difficult to fix it afterwards because of  backwards compatibility.
