### ISSUE TITLE
Nodename defaut on windows should be the hostname

### ISSUE THREAD

**Issue by jothoma1** [Graylog2/collector-sidecar#339]
### Problem description
When installing the sidecar without -NODENAME on windows the default value is 'graylog-sidecar'
It should be the hostname of the server as if we make multiples instances we have a lot of 'graylog-sidecar'.

### Steps to reproduce the problem

1. Install the sidecar on windows with silent switch
2. c:\sidecar.exe /S -SERVERURL=http://x.x.x.x:9000/api -TAGS="windows" -APITOKEN=mytoken -NXLOG_ENABLED=true -FILEBEAT_ENABLED=false -WINLOGBEAT_ENABLED=false

### Environment

* Sidecar Version: 1.0.0-rc.1
* Graylog Version: 3.0 rc1
* Operating System: Windows 2019
* Elasticsearch Version: 6.5
* MongoDB Version:

**Comment by TheJCamping** [comment]
I made request to change this behavior in #346 . The Jenkins build failed, so I probably did something wrong, but ill wait for a dev who has access to tell me what I did wrong.
