### ISSUE TITLE
Applying filebeat config to sidecar client fails validation

### ISSUE THREAD

**Issue by kurowskydb** [Graylog2/collector-sidecar#345]
### Problem description
After applying a filebeat configuration to Sidecar client the client generates the following error:
`Feb 15 11:08:52 sidecarprdr02.estes.us.dom graylog-sidecar[61238]: time="2019-02-15T11:08:52-05:00" level=error msg="[filebeat] Couldn't start validation command: fork/exec /usr/share/filebeat/bin/filebeat: no such file or directory"`
And remains in failed state.

There error is correct, the directory does not exist.  I can't locate where the path is referenced from.

### Steps to reproduce the problem

1. Apply filebeat configuration to sidecar client.

### Environment

* Sidecar Version:  graylog-sidecar-1.0.0-1.x86_64.rpm
* Graylog Version:  v3.0.0+db6cf59
* Operating System:  Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Elasticsearch Version:  5.6.14
* MongoDB Version:  v4.0.6

![image](https://user-images.githubusercontent.com/11399008/52869558-e81f0f00-3113-11e9-8c40-c70f0cd45c92.png)

![image](https://user-images.githubusercontent.com/11399008/52869842-932fc880-3114-11e9-9344-2e1977ce572f.png)

**Comment by mpfz0r** [comment]
The path comes from our predefined filebeat collector. see http://docs.graylog.org/en/3.0/pages/sidecar.html#creating-a-new-log-collector

Did you install the official filebeat package from elastic?
It should be there.

**Comment by kurowskydb** [comment]
No, I installed the graylog 1.0 sidecar 
    * graylog-sidecar-1.0.0-1.x86_64.rpm

**Comment by kurowskydb** [comment]
Oh... I see.  Thought beats was included in sidecar.   That might explain it.
Closing....  :/
