### ISSUE TITLE
Filebeat installation error with graylog-sidecar in Ubuntu machine

### ISSUE THREAD

**Issue by LuisFFFerreira** [Graylog2/collector-sidecar#348]
### Problem description

We have installed collector-sidecar version 1.0.0 to get the logs from an ubuntu machine 18.04 and graylog server 3.0. The issue that I am facing is when we upload the filebeat configuration its returned a failing error that the ubuntu machine cannot start validation command: fork/exec /usr/share/filebeat/bin/filebeat: no such file or directory.

After some troubleshooting we discovered that filebeat is not being installed with graylog-sidecar, to test this we installed "filebeat-6.6.1-amd64.deb" package and the error disapears and everything goes back to normal.

### Steps to reproduce the problem

1. Graylog-Sidecar installation as usual;
![img1](https://user-images.githubusercontent.com/22391890/53247735-0fde1c00-36ac-11e9-8200-8a4268dfb9ab.png)

2. Only configured server_url and server_api_token on sidecar.yml file;
![img2](https://user-images.githubusercontent.com/22391890/53247803-2e441780-36ac-11e9-99f5-efa4cff34a99.png)

3. Graylog-sidecar appears to be running ok;
![img3](https://user-images.githubusercontent.com/22391890/53247876-487df580-36ac-11e9-8ee0-d48c147edf33.png)

4. Client machine appears as "running" on graylog web interface;
![img4](https://user-images.githubusercontent.com/22391890/53247933-6fd4c280-36ac-11e9-9977-2e328f81a26c.png)

5. Configured filebeat as default with changes only of host IP;
![img5](https://user-images.githubusercontent.com/22391890/53248010-a0b4f780-36ac-11e9-946a-2b14d1af4283.png)

6. Configuration was added to client machine and failed;
![img6](https://user-images.githubusercontent.com/22391890/53248058-c04c2000-36ac-11e9-808a-4d7e3fe1b6c8.png)

7. Graylog-sidecar on client machine with error (yellow lines);
![img7](https://user-images.githubusercontent.com/22391890/53248157-f7bacc80-36ac-11e9-8433-97a6c895cb1f.png)

8. We can see the same error on graylog logs;
![img8](https://user-images.githubusercontent.com/22391890/53248223-1faa3000-36ad-11e9-9ad4-f80b7d6fe77e.png)

9. We can see that filebeat is not installed with graylog-sidecar, the only file with "filebeat" as name is filebeat.conf in /var/lib/graylog-sidecar/generated;
![img9](https://user-images.githubusercontent.com/22391890/53248325-5e3fea80-36ad-11e9-81c9-6db2a1670b8d.png)

10. We can see that filebeat.conf is uploaded to the client with no problems.
![img10](https://user-images.githubusercontent.com/22391890/53248414-90e9e300-36ad-11e9-808a-ee84fd9de4c9.png)

### Environment

* Sidecar 1.0.0:
* Graylog 3.0:
* Operating System Ubuntu 18.04:
* Elasticsearch Version 6.6.1:
* MongoDB Version 4.0.6:

**Comment by mpfz0r** [comment]
First of all, thank you for your detailed bug report :+1: 

In your screenshot at step 7 you can see that the sidecar fails to find the filebeat binary.

Please see:  http://docs.graylog.org/en/3.0/pages/sidecar.html#install-new-sidecar
> Note: In case you were using filebeat on Linux, please make sure to also install the official collector package, 
> since the filebeat binary is not part of the Sidecar package anymore.

And http://docs.graylog.org/en/3.0/pages/sidecar.html#beats-on-linux  in addition

**Comment by LuisFFFerreira** [comment]
Thank you for your fast response.

In fact, as i mentioned on the description of the problem, installing filebeat ("filebeat-6.6.1-amd64.deb") downloaded from the official website has made the problem disapear. Now i understand why.

Best regards. Keep the great work.
