### ISSUE TITLE
Missing version number in executable

### ISSUE THREAD

**Issue by DigitalJanitor** [Graylog2/collector-sidecar#359]
We use revision detection for install/upgrading and it looks like the latest release made it out without any file version information. (Installer and uninstaller both show proper versions)

TL;DR: graylog-sidecar.exe is missing File version, Product Name, Product version, Copyright and language.

### Steps to reproduce the problem
1. ... Upgrade to 1.0.1.1

**Comment by mpfz0r** [comment]
I can confirm that. However, the 0.1.8 .exe does not contain any version information either.
So I'm assuming that we never provided this.

**Comment by malcyon** [comment]
The installer EXE has the version information, but the `graylog-sidecar` executable itself does not. 

![image](https://user-images.githubusercontent.com/13503567/143121943-eced4d09-4418-429f-97b7-d6c7e3417969.png)

![image](https://user-images.githubusercontent.com/13503567/143123276-bcc166a8-d5cf-4874-b11b-babb2fc58e80.png)
