### ISSUE TITLE
Multiple tags per collector break nxlog configuration

### ISSUE THREAD

**Issue by pasmon** [Graylog2/collector-sidecar#36]
### Problem description
Using multiple tags, e.g. one for logging a generic CentOS log files and another for logging Nginx logs doesn't work:

> Jul 01 10:31:07 i-4cd9dfbf graylog-collector-sidecar[17877]: time="2016-07-01T10:31:07+03:00" level=error msg="[nxlog] Error during configuration validation: exit status 1"
> Jul 01 10:31:07 i-4cd9dfbf graylog-collector-sidecar[17877]: time="2016-07-01T10:31:07+03:00" level=info msg="[nxlog] Collector configuration file is not valid, waiting for update..."

Nxlog itself does seem to think that configuration is OK:
> [root@i-4cd9dfbf-goserver ~]# nxlog -v -f /etc/graylog/collector-sidecar/generated/nxlog.conf
2016-07-01 10:41:44 INFO configuration OK

Deleting either one of the configurations having a tag defined gets logging working again. Am I configuring the tags somehow incorrectly, each different tag I have is configured only in their own configuration - so each configuration has only one tag?

Attached the nxlog.conf from both cases, one configuration and one tag, and 2 configurations with one tag in each.
[nxlog_one_tag.conf.txt](https://github.com/Graylog2/collector-sidecar/files/343046/nxlog_one_tag.conf.txt)
[nxlog_multiple_tags.conf.txt](https://github.com/Graylog2/collector-sidecar/files/343047/nxlog_multiple_tags.conf.txt)

### Steps to reproduce the problem

1. Define 2 tags in collector_sidecar.yml
2. Create 2 configurations in Graylog, each having one the tags defined in step 1
3. Logging doesn't work since sidecar thinks the Nxlog configuration is broken although Nxlog's own validation says the config is OK (there is some duplicated config options in the config file when multiple configurations/tags is setup)

### Environment

* Sidecar Version: 0.0.8
* Graylog Version: 2.0.3
* Operating System: CentOS 7.2
* Elasticsearch Version: 2.3.3
* MongoDB Version: 2.6.12

**Comment by mariussturm** [comment]
Hi,
when you create a second configuration the nxlog-default snippet is also created a second time. Is nxlog still failing when you delete that second default snippet?

**Comment by pasmon** [comment]
That does it! I configured the generic configuration applied to all sidecar clients to have the nxlog-default snippet and removed it from all the additional configurations, now the configuration validation and logging works.

Thanks @mariussturm !

I think sidecar should still somehow notice this kind of situation and not put duplicate data to the nxlog.conf file?

**Comment by mariussturm** [comment]
Should be fixed in 0.0.9 25d285073f1ad37c2681b7d98f340e050dba6acc
