### ISSUE TITLE
Failed to update the created service: Access is denied." 

### ISSUE THREAD

**Issue by traithon9x** [Graylog2/collector-sidecar#361]
### Problem description
I have a problem. when I installed and start service slidecars I can't running copy config file in graylog server to nxlog. collector installed in windows server 2012 R2.

here is logs file in sidecars
`time="2019-04-22T10:14:05+07:00" level=info msg="Starting signal distributor" 
time="2019-04-22T10:14:15+07:00" level=info msg="No configurations assigned to this instance. Skipping configuration request." 
time="2019-04-22T10:14:35+07:00" level=info msg="Adding process runner for: nxlog" 
time="2019-04-22T10:14:35+07:00" level=info msg="[nxlog] Configuration change detected, rewriting configuration file." 
time="2019-04-22T10:14:37+07:00" level=error msg="[nxlog] Failed to update the created service: Access is denied." 
time="2019-04-22T10:14:37+07:00" level=info msg="[nxlog] Starting (svc driver)" 
`
when I checked logs on the windows event I find error event id 4098.
detail : 
`The computer 'RpcEptMapper' preference item in the 'Default Domain Policy {31B2F340-016D-11D2-945F-00C04FB984F9}' Group Policy Object did not apply because it failed with error code '0x80070005 Access is denied.' This error was suppressed.`
and 
`The computer 'Administrator (built-in)' preference item in the 'Default Domain Policy {31B2F340-016D-11D2-945F-00C04FB984F9}' Group Policy Object did not apply because it failed with error code '0x800706ba The RPC server is unavailable.' This error was suppressed.`

can you help me ?
### Steps to reproduce the problem

1. ...

### Environment

* Sidecar Version: 1.0.1
* Graylog Version: 3.0
* Operating System: 
* Elasticsearch Version: 5.x
* MongoDB Version: lastest

**Comment by florianvolle** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
