### ISSUE TITLE
feature log collector sidecar nxlog.conf  Include %ROOT%\conf\include\\*.conf

### ISSUE THREAD

**Issue by dio99** [Graylog2/collector-sidecar#362]
I would like to have the option in nxlog to be able to load diffrent confs from include dir 
managed in sidecars 
this is due to u can have a standanrd system.conf for all servers and then add like SQL.conf or dhcp.conf to include dir 
## Load the nxlog configs
Include %ROOT%\conf\include\\*.conf

// Anders

### Problem description
no problem
### Steps to reproduce the problem

1. ...

### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
* Elasticsearch Version:
* MongoDB Version:

**Comment by jalogisch** [comment]
he @dio99 

I do not have nxlog available, but could you not just write that into the configuration you push over? Did you tried this with the latest release?

**Comment by dio99** [comment]
yes i can have all in one config file but the benefit of using include dir is that u can have a default one like system.conf and the u push or send another called dhcp.conf or SQL.conf that will not interfere in in default and break system.conf if u misstype or similar. i dont see how u can add that in sidecar ?

one other thing that can be  good is to be able to have is the certs in sidecar so u can deploy them also.. 

// Anders

**Comment by jalogisch** [comment]
@dio99 have you seen the new sidecar? You can write the configuration of NXLOG direct and no need of having it abstracted away in a UI. So you can just include 

```
Include %ROOT%\conf\include\*.conf
```

in the configuration that is written to the sidecar.

Would you mind to create a seperate feature request to handle certificates for the collectors managed by sidecar?

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
