### ISSUE TITLE
problem with collector_binaries_whitelist

### ISSUE THREAD

**Issue by lschroth** [Graylog2/collector-sidecar#363]
### Problem description
Error when collector_binaries_whitelist path for 32bit windows version of nxlog.

32bit Windows installs all programs in the c:\program files\ directory.  I have updated the collector_binaries_whitelist to include c:\program files directory, but when starting sidecar in debug mode, I get the following error.

[nxlog_32bit] Couldn’t execute
collector C:\Program Files\nxlog\nxlog.exe, binary path is not included in `
collector_binaries_whitelist’ config option."the c:\program files director.  When starting the sidecar program with an updated collector_binaries_whitelist, an error is returned of 

``
### Steps to reproduce the problem

1. install a collector program in the c:\program files directory
2. update the configuration & whitelist to reference the new path
3 . start sidecar in debug mode and you get an error of 

### Environment

* Sidecar Version: 1.0.1
* Graylog Version: Graylog 3.0.1+de74b68  
* Operating System: ubuntu
* Elasticsearch Version: 5.6.14
* MongoDB Version:

**Comment by lschroth** [comment]
[sidecar.yml.txt](https://github.com/Graylog2/collector-sidecar/files/3129303/sidecar.yml.txt)
[sidecar.log](https://github.com/Graylog2/collector-sidecar/files/3129304/sidecar.log)

**Comment by mpfz0r** [comment]
How did you configure the executable path for your collector?
It looks like you picked `C:\\Program Files\\nxlog\\nxlog.exe` while it should be `C:\Program Files\nxlog\nxlog.exe`

Only the sidecar.yml needs the path with two backslashes.

**Comment by lschroth** [comment]
Yes, I did.  Here is what I have for the configuration below.

`
define ROOT C:\Program Files\nxlog

Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%ROOT%\data\nxlog.log', 7);
     </Schedule>
</Extension>


<Extension gelfExt>
  Module xm_gelf
  # Avoid truncation of the short_message field to 64 characters.
  ShortMessageLength 65536
</Extension>

<Input eventlog>
        Module im_msvistalog
        PollInterval 1
        SavePos True
        ReadFromLast True
        
        #Channel System
        #<QueryXML>
        #  <QueryList>
        #   <Query Id='1'>
        #    <Select Path='Security'>*[System/Level=4]</Select>
        #    </Query>
        #  </QueryList>
        #</QueryXML>
</Input>


<Output gelf>
	Module om_tcp
	Host 17x.xxx.xxx.xxx
	Port 12201
	OutputType  GELF_TCP
	<Exec>
	  # These fields are needed for Graylog
	  $gl2_source_collector = '${sidecar.nodeId}';
	  $collector_node_id = '${sidecar.nodeName}';
	</Exec>
</Output>


<Route route-1>
  Path eventlog => gelf
</Route>

`

**Comment by lschroth** [comment]
[nxlog.conf.txt](https://github.com/Graylog2/collector-sidecar/files/3133156/nxlog.conf.txt)

Attached is my nxlog.conf

**Comment by mpfz0r** [comment]
Just to be clear, I was talking about the `Executable Path` setting for your collector:

![image](https://user-images.githubusercontent.com/3034831/57064315-329d3a00-6cc6-11e9-8b43-cf82567327d3.png)

How did you configure that?

**Comment by lschroth** [comment]
yes, I created a unique collector profile (nxlog_32bit) and set the executable to "C:\Program Files\nxlog\nxlog.exe"

![Capture](https://user-images.githubusercontent.com/17602189/57083642-7ee47c00-6cbe-11e9-9104-b35da3d43548.PNG)

**Comment by mpfz0r** [comment]
Ok, thanks. However, the nxlog.conf should be irrelevant for this error.
The sidecar won't even try to start nxlog if it's not within the whitelist.

I think I've found the error in your sidecar.yml:

```
Collector_binaries_whitelist: [ 'C:\\Program Files\\nxlog\\nxlog.exe' ]
```
It should be `collector_binaries_whitelist` not `Collector_binaries_whitelist` (no capital C at the beginning)

**Comment by lschroth** [comment]
Sorry, that was just left over from testing different setups in the file.  The error is the same with the field updated.

**Comment by mpfz0r** [comment]
Two more things that might cause trouble.
1.) You quoted the path with single quotes. But then kept the double backslash.
This is only needed when using double quotes. 
2.) Apparently the golang path matching in Windows is case sensitive. Make sure to get
your capitalization correct.

`collector_binaries_whitelist: [ "C:\\Program Files\\nxlog\\nxlog.exe" ]`

**Comment by lschroth** [comment]
That worked.  I ended up with collector_binaries_whitelist: [ "C:\\Program Files\\nxlog\\nxlog.exe" ] to make it work.

I would suggest adding that path to the default for 32 bit machines...
