### ISSUE TITLE
Add containter log collect and host log collect  through collector-sidecar

### ISSUE THREAD

**Issue by xuanyuanaosheng** [Graylog2/collector-sidecar#367]
With the development of docker and  k8s，to find  a way to collect host logs and docker containter log are importtant.   Just like : https://github.com/Graylog2/collector-sidecar/issues/196

The  possible way to solve this is  https://github.com/AliyunContainerService/log-pilot 

can you consider  this ?

**Comment by jalogisch** [comment]
With the current release of the sidecar you are able to declare and configure your own collectors.
I did not looked into the linked project but if that can be started in the foreground via sidecar you can integrate this on your own.

**Comment by florianvolle** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).
 
Thank you!
