### ISSUE TITLE
Graylog Sidecar available in Chocolatey Repo

### ISSUE THREAD

**Issue by juaromu** [Graylog2/collector-sidecar#370]
### Problem description
Publish Graylog Sidecar (Windows Collector) on Chocolatey Repo so that it'd be available for automated deployments (Ansible, for instance).

### Steps to reproduce the problem

1. N/A

### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
Microsoft Windows
* Elasticsearch Version:
* MongoDB Version:

**Comment by juju2112** [comment]
The Chocolatey package for graylog-sidecar is currently awaiting approval by the Chocolatey moderators.

**Comment by juju2112** [comment]
Alright, the package has been approved by the Chocolatey moderators. 

https://chocolatey.org/packages/graylog-sidecar
