### ISSUE TITLE
Make the list of scanned hard drives configurable (Windows/Sigar)

### ISSUE THREAD

**Issue by ntimo** [Graylog2/collector-sidecar#371]
### Problem description
We are running Graylog collector sidecar on Windows Server 2016 using a app user. This app user tries to mount Volume D, which is a disk drive.
![Sidecar Windows Error](https://user-images.githubusercontent.com/6145026/60595375-2c4f3b00-9da7-11e9-94ff-5d7271b5874d.PNG)

### Steps to reproduce the problem

1. Install Graylog Sidecar 1.0.1 and run it with a app user, with Admin privileges
2. Check the Windows Event logs (Applications and Service Logs -> Microsoft -> Windows -> Kernal-IO -> Operational )

### Environment

* Sidecar Version: 1.0.1
* Graylog Version: 3.0.2
* Operating System: Windows Server 2016

**Comment by mariussturm** [comment]
You can view some system stats for each Sidecar host in the Graylog interface. E.g. disk drive with above 75%. For that the Sidecar needs to go through the list of available disks. If you don't want that you can disable `send_status` in the Sidecar configuration.

**Comment by ntimo** [comment]
Thats a useful feature, and we would like to continue to use it. But why does it have to check the disk usage of a disk(dvd) drive? Is there some way to exlucde these kind of devices from the scan?

**Comment by mariussturm** [comment]
I think only A: and B: are reserved for floppy drives. The others can be hard drives or not, the software doesn't know it upfront. Yeah we could make that configurable if that helps.

**Comment by ntimo** [comment]
I think having a config option for that would be very nice.

**Comment by mariussturm** [comment]
I don't know when we find the time for it but I change this issue to a feature request.

**Comment by dm-bo** [comment]
@mariussturm very annoying issue. I guess, people who using Graylog do read the logs, and they unhappy to see lots of useless messages from sidecar there. Is there any option to disable disks scanninng? Can admin replace "CDEFGHIJKLMNOPQRSTUVWXYZ" with "" in sigar config somehow? Collector status is useful, but disks status is not.
