### ISSUE TITLE
Sidecar cannot be configured for Darwin

### ISSUE THREAD

**Issue by username-rand** [Graylog2/collector-sidecar#377]
### Problem description
Sidecar cannot be configured for Darwin with Linux nxlog collector

### Steps to reproduce the problem

Running Graylog 3.1 on Mac OS X 10.14.5. Previously ran 2.5.1 and 3.0.1 with the Legacy collector configured to use nxlog. Recently upgraded to Graylog 3.1.0 and have been unable to figure out how to configure the Sidecar version 1.1.0 for a Darwin collector (nxlog). The OS choices are Linux and Windows. I can set up a Linux collector but when I try to assign it to the Sidecar, it informs me that there are no Darwin collectors available. I currently have the Legacy collector running (version 0.1.8), but would rather switch to the current technology. Anyone have any advice? Is it possible?

### Environment

* Sidecar Version: 1.1.0
* Graylog Version: 3.1.0
* Operating System: Mac OS X 10.14.5
* Elasticsearch Version: 6.5.4
* MongoDB Version: 4.0.4_1

**Comment by mpfz0r** [comment]
Thank you for your report.
This is indeed a bug / missing feature.
We just recently built a sidecar for Darwin and FreeBSD, but forgot to take the server into account here.

Basically there's two ways we could go:
 - Change the `Linux` definition to a more generic  `Unix` and handle Darwin and FreeBSD equally
or 
 - Add new OS categories for them

**Comment by mariussturm** [comment]
I think it would make sense to create new OS categories. Given that we might support more OS specific service managers like SystemD for Linux or launchctl for OSX in the future. it would be nice to filter those in the UI based on the OS selection.

**Comment by guard43ru** [comment]
Hello, can't configure sidecar on macOS (installed via brew)
I can't create new log collector (no needed OS) and I can't use Linux collector. (No collectors compatible with Darwin)

<details>
  <summary>Screenshots</summary>

![new_collector](https://user-images.githubusercontent.com/10044200/129381357-11bfce8d-7c6e-4342-8d5e-04e2356a450e.png)

![configuration](https://user-images.githubusercontent.com/10044200/129381354-c8dee20f-578e-48af-b5ae-90fe4126aa45.png)

![sidecar](https://user-images.githubusercontent.com/10044200/129381347-2ea40afb-867a-48f0-b34a-222c05a40555.png)

</details>

Graylog 4.1.3
Sidecar 1.1.0

**Comment by username-rand** [comment]
I have a solution if you can build the sidecar on Mac OS X.  It requires a one line change to make sidecar think it is running on linux.  Works with nxlog.  I’ll have to go find my change and will post it.

**Comment by username-rand** [comment]
Still looking for the code change, however, it is a binary for Mac OS X which works with Big Sur and Graylog Version 
4.0.6 and nxlog version ce-2.2.8.1248.  Maybe this will help until I can find and post the change.  It makes Graylog think it is a linux version of sidecar.  This is the binary for sidecars version 1.1.0.  I haven't recently looked to see if there is a new one.

Rand

[graylog-sidecar-MacOSX.zip](https://github.com/Graylog2/collector-sidecar/files/6983738/graylog-sidecar-MacOSX.zip)

**Comment by username-rand** [comment]
Hey Guard43ru ,

Tried to get the developers to fix this back inn 2019 but no luck as far as I know.

Here is my readme for what to change and how to make it.  Note that this is not a permanent solution.  It forces the program to think it is running on linux, so developers will still have to come up with a fix.  You have to have "go" installed and working and the GOPATH will be dependent on your go installation.  Maybe the developers will see this.
----------------------------
git clone https://github.com/Graylog2/collector-sidecar.git
Make sure directory is "collector-sidecar" for the build.
Then in collector-sidecar

Change common/helper.go
add
  osRunes = []rune("Linux")
in GetSystemName for force Linux for Graylog2

set environment variable GOPATH=/Users/admin/Programs/
   glide install (if not done already)
   make build
------------------------------------------------------------

This is the function that I changed in common/helper.go to force linux.

func GetSystemName() string {
        os := runtime.GOOS
        osRunes := []rune(os)
        osRunes[0] = unicode.ToUpper(osRunes[0])
        osRunes = []rune("Linux")
        return string(osRunes)
}

Rand

**Comment by guard43ru** [comment]
It's a workaround, but I think developers can fix these on the server-side.
I just reminded of this bug, I'ts actual in the current release.

**Comment by username-rand** [comment]
They could by recognizing Darwin as an OS.  They have not however fixed this in the years since I reported the problem, which is why I did the workaround.  You might open a new bug report and reference this one.  Maybe someone will notice.
