### ISSUE TITLE
FeatureRequest: Ask for server settings and tags during Windows installer dialog

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/collector-sidecar#38]
### Problem description
To reduce the steps a user has to made till the Sidecar is ready to run, we could create a dialog in the Windows installer to ask for the most basic settings every installation needs. For most installations no further configuration would be needed.

**Comment by henrikjohansen** [comment]
Please consider adding those as command-line options for a silent installer as well :)

**Comment by mariussturm** [comment]
This will be in 0.1.0 d4c2910e9e272e038d073d8fbb23e31bf32c86ae
