### ISSUE TITLE
 [Win 2012R2 | Win 2016] Windows could not start the Graylog Sidecar service - Error 1067: The process terminated unexpectedly

### ISSUE THREAD

**Issue by veanome** [Graylog2/collector-sidecar#380]
### Problem description
When trying to start the graylog service on Windows Server 2012 R2 and 2016 I get this error:

"Windows could not start the Graylog Sidecar service on Local Computer.

Error 1067: The process terminated unexpectedly"

### Steps to reproduce the problem

1. Install nxlog and graylog-sidecar on server
2. Enter in server_url, node name, and APIToken
3. Run "C:\Program Files\graylog\sidecar\graylog-sidecar.exe" -service install & "C:\Program Files\graylog\sidecar\graylog-sidecar.exe" -service start
4. Run C:\Program Files (x86)\nxlog\nxlog -u
5. Open up services and try to start the service "Graylog Sidecar"
6. Failure - "Windows could not start the Graylog Sidecar service on Local Computer. Error 1067: The process terminated unexpectedly"

### Environment

* Sidecar Version: 1.0.2-1
* Graylog Version: 3.0.2
* Operating System: Graylog Server/Web - CentOS, Sidecars - Windows Server 2012 R2 and 2016
* Elasticsearch Version: 6.8.3
* MongoDB Version: 4.0.12

**Comment by jalogisch** [comment]
it might be connected to this:

https://community.graylog.org/t/new-sidecar-filebeat-failing/12476/2?u=jan

> In case anyone else is having a similar issue, there appears to be a bug in the template for filebeat on Windows, there is a missing dash (-) before the word log, which causes the config file to be invalid.

**Comment by mpfz0r** [comment]
> ### Problem description
> 
> When trying to start the graylog service on Windows Server 2012 R2 and 2016 I get this error:
> 
> "Windows could not start the Graylog Sidecar service on Local Computer.
> 
> Error 1067: The process terminated unexpectedly"
> ### Steps to reproduce the problem
> 
>     1. Install nxlog and graylog-sidecar on server
> 
>     2. Enter in server_url, node name, and APIToken
> 
>     3. Run "C:\Program Files\graylog\sidecar\graylog-sidecar.exe" -service install & "C:\Program Files\graylog\sidecar\graylog-sidecar.exe" -service start
> 
>     4. Run C:\Program Files (x86)\nxlog\nxlog -u
> 
>     5. Open up services and try to start the service "Graylog Sidecar"

That step shouldn't be necessary. Step 3 already starts the service.
Wasn't it running when you looked at the service?

> 
>     6. Failure - "Windows could not start the Graylog Sidecar service on Local Computer. Error 1067: The process terminated unexpectedly"

Check your `C:\Program Files\Graylog\sidecar\logs\sidecar.log` for errors.
