### ISSUE TITLE
Publish your debs on the graylog repo? Otherwise we get HTTP 429 from Github

### ISSUE THREAD

**Issue by Gui13** [Graylog2/collector-sidecar#382]
### Problem description

We need to download your packages from the release page of Github, which has request limitations.
When deploying graylog on a big infra, many of our hosts get rate limited (HTTP 429 error) when dowloading your releases and fail the deployment

Would it be possible to publish these on your graylog debian repositories?
This has the advantage of not needing an obscure URL, allow package signing, permits caching on our end (we have an apt-cacher-ng fronting all our debs), and also allows automatic updates (we use cron-apt).

Right now, collector-sidecar is the official, non-deprecated way of managing logs for Graylog, but it requires to fiddle with Github's distribution mechanism.

### Steps to reproduce the problem

1. Install the collector on more than a few hosts
2. Get rate limited
3. All hosts that get rate limited fail the deployment

### Environment

* Sidecar Version: 1.x
* Graylog Version: 3
* Operating System: Linux Debian
* Elasticsearch Version: 5.6
* MongoDB Version:

**Comment by Gui13** [comment]
So.. what up ?

**Comment by juju2112** [comment]
Hi @Gui13. It sounds pretty reasonable to me. @bernd, can you show me how to do this? Or comment on the feasibility?

**Comment by bernd** [comment]
@juju2112 Aye, let's talk about this. :+1:

**Comment by bernd** [comment]
Reopen because we are not done yet.

**Comment by Gui13** [comment]
I want to thank you for taking the time to do that, we were concerned about the problem because we would have had to locally mirror your packages and lose the update mechanism. Having all the debs into your official deb repo will simplify the distribution mechanism a great deal!

**Comment by juju2112** [comment]
Not a problem. I am new to this project, and this is a good opportunity for me to learn how all the repository stuff works.

**Comment by juju2112** [comment]
@Gui13 The sidecar package should be set up correctly in our repository now. Do you mind giving it a try and making sure everything works correctly?

**Comment by Gui13** [comment]
Thank you @juju2112 , I'll try to test this before the end of the week.

**Comment by Gui13** [comment]
I confirm that it works using your repo deb and apt-get install ! Thank you @juju2112 !

**Comment by juju2112** [comment]
Awesome, thanks!
