### ISSUE TITLE
Is there a limit to the number of log files for collector-sidecar tail?

### ISSUE THREAD

**Issue by WangHouLing** [Graylog2/collector-sidecar#386]
### Problem description
Hi all,
Excuse me. I am using collector-sidecar to collect log data(Filebeat backend), there will be more log files to collect.So I need to know if the collector-sidecar has a limit on the number of log files(The "paths" configuration item in filebeat.yml).  How many sub-directory files can be collected in a parent directory? What is the performance of collector-sidecar when there are a large number of files in the subdirectory?
I would very appreciate it if you can help me.

### Steps to reproduce the problem
graylog server web:
![image](https://user-images.githubusercontent.com/20981477/74505862-30455d00-4f33-11ea-85fb-9e932c0ab5f3.png)
filebeat.yml:
![image](https://user-images.githubusercontent.com/20981477/74505985-7bf80680-4f33-11ea-883c-baf1adc6f5ca.png)

### Environment

* Sidecar Version:1.5.0
* Graylog Version:2.4.3
* Operating System:Centos7
* Elasticsearch Version:5.6.8
* MongoDB Version:3.2.19

**Comment by mariussturm** [comment]
Hi,
there is no technical limitation build-in. The limit is more defined by the server capacity. Filebeat will need more CPU and Memory resources when it collects more files. But that's nothing we can affect.
