### ISSUE TITLE
Please document silent install flags for Windows

### ISSUE THREAD

**Issue by JulioQc** [Graylog2/collector-sidecar#387]
Everything is in the title. 
In [current documentation](https://docs.graylog.org/en/3.2/pages/sidecar.html#windows) I can only see a single example for Windows...

> Or in silent mode with:
> $ graylog_sidecar_installer_1.0.0-1.exe /S -SERVERURL=http://10.0.2.2:9000/api -APITOKEN=yourapitoken

Flags seem to be demanded in other "issues" I can see here but no proper documentation doesn't help to know which work and which don't. I can reverse engineer it using some win32 tools but documentation would spare me this trouble. 

Overall, this would greatly help to have it documented so sysadmins can have the collector push silently. 

Thank you!

**Comment by mariussturm** [comment]
What flag do you mean is missing? The silent flag is here: http://docs.graylog.org/en/latest/pages/sidecar.html#windows

**Comment by JulioQc** [comment]
> What flag do you mean is missing? The silent flag is here: http://docs.graylog.org/en/latest/pages/sidecar.html#windows

Silent is there, found SERVERURL in new doc (link provided), found there's also a TAGS flag in 2.5 doc and I was hoping or a flag for the node_id (which could be NODEID) which would be nice. Flag for other settings of the .yml would be a nice plus as well.

**Comment by mpfz0r** [comment]
> edit: from testing, the assumed NODEID flag worked!

That can't be right. The only supported flags are:
https://github.com/Graylog2/collector-sidecar/blob/master/dist/recipe.nsi#L181-L186

**Comment by mpfz0r** [comment]
What would be useful is a `/H` help switch in the installer that shows all options

**Comment by JulioQc** [comment]
> > edit: from testing, the assumed NODEID flag worked!
> 
> That can't be right. The only supported flags are:
> https://github.com/Graylog2/collector-sidecar/blob/master/dist/recipe.nsi#L181-L186

Scripted deployment over my infra using that flag so you can trust me when I say it works. But I understand your confusion from the code you quote, so am I!

**Comment by mpfz0r** [comment]
Could that be because the node-id was already persisted in the node-id file from a previous install?

**Comment by JulioQc** [comment]
Mixed deployment, some upgrade, some new installations, so I would say possibly not the explanation :(
