### ISSUE TITLE
Graylog Sidecar reports "unable to map property tags"

### ISSUE THREAD

**Issue by jfarr2008** [Graylog2/collector-sidecar#39]
### Problem description
I'm using nxlog and I've installed the graylog sidecar.  I'm manually starting it with my configuration file so I can monitor it.  Just after reporting that nxlog is starting it gives a 400 error related to the property tags.

### Steps to reproduce the problem
1. Install nxlog
2. Install sidecar
3. Configure sidecar per graylog docs.
4. Manually start sidecar in the foreground so I can monitor
5. Results in error

yml config below:
[collector_sidecar.txt](https://github.com/Graylog2/collector-sidecar/files/369055/collector_sidecar.txt)

screenshot of error:
![sidecar_error](https://cloud.githubusercontent.com/assets/20517259/16915602/167596a4-4cbe-11e6-9db8-90d6bac6fa81.PNG)

### Environment
* Sidecar Version: 0.9-alpha-1
* Graylog Version: 2.0.3
* Operating System: Centos 6.8 x64 
* Elasticsearch Version: 2.3.4-1
* MongoDB Version: 3.2.8-1

**Comment by mariussturm** [comment]
Thanks for the report, this should be fixed in 0.0.9-alpha.2

**Comment by jfarr2008** [comment]
Confirmed working on my end.  Thanks all!

**Comment by ReK42** [comment]
I have this same issue on 0.0.9-beta.1 running of Windows Server 2012 R2. It's pulling down the config, running nxlog and the server is receiving eventlog messages but the collector isn't visible under System/Collectors on the web interface.

**Comment by mariussturm** [comment]
@ReK42 please make sure that you actually call beta.1, the installation path was fixed to C:\Program Files instead of C:\Program Files(x86). Maybe you are still using the old version without noticing.

**Comment by ReK42** [comment]
@mariussturm This host has never had a previous version installed, beta 1 is the only copy on it.

**Comment by mariussturm** [comment]
@ReK42 just double checked this. You have to disable the features that are not supported by the graylog-collector plugin that ships with 2.0.3. Those are:

```
send_status: false
list_log_files:
```

**Comment by ReK42** [comment]
Alright, thank you.
