### ISSUE TITLE
Couldn't open nxlog service

### ISSUE THREAD

**Issue by junior466** [Graylog2/collector-sidecar#390]
### Environment

* Sidecar Version: 1.0.2
* Graylog Version: 3.2.4
* Operating System: Linux (Ubuntu 18.04)

Followed the instructions on documentation to ship Windows logs to Graylog using Nxlog but keep receiving this error:

    ERROR Couldn't open nxlog service; The specified service does not exist as an installed service.  

This is my first time configuring Sidecar. Why does it seems to be asking for the service I was told to disable?

**Comment by mpfz0r** [comment]
Unlike Filebeat and WInlogBeat, NXLog is not included in the sidecar for Windows package.
You need to install it: https://docs.graylog.org/en/3.2/pages/sidecar.html#nxlog-on-windows

**Comment by junior466** [comment]
@mpfz0r I did install it on my Windows host as the instructions suggested and deactivated the service as well.

**Comment by mpfz0r** [comment]
Ok, thanks. reopening this. Gonna have to look at this later.

**Comment by mpfz0r** [comment]
> Followed the instructions on documentation to ship Windows logs to Graylog using Nxlog but keep receiving this error:
> 
> ```
> ERROR Couldn't open nxlog service; The specified service does not exist as an installed service.  
> ```

Where exactly are you seeing this error? I can't find that in our codebase.

> 
> This is my first time configuring Sidecar. Why does it seems to be asking for the service I was told to disable?

Did you configure nxlog and assigned it to your sidecar?
The docs are refering to the service that is installed by the nxlog installer itself.
That service is in the way of the one that sidecar wants to register.

**Comment by junior466** [comment]
I am seeing the error in Graylog when viewing the failing Sidecar:

![Screen Shot 2020-04-09 at 12 09 45 PM](https://user-images.githubusercontent.com/22748735/78916423-71ea1400-7a5b-11ea-81d3-dd6cc2438c74.png)


A little more background to eliminate the possibility of user error. 

I am trying to push Windows Server logs to my Graylog server running on Ubuntu. I installed the Sidecar on my Windows host following [this](https://docs.graylog.org/en/3.2/pages/sidecar.html#windows) part of the guide, [installed](https://docs.graylog.org/en/3.2/pages/sidecar.html#nxlog-on-windows) Nxlog on the Windows Host and deactivated the service. Created an Input GELF and applied the default Nxlog configuration (edited and pointed to Graylog). 

Maybe I am not doing this properly?

**Comment by junior466** [comment]
@mpfz0r Any update on this error?

**Comment by mpfz0r** [comment]
Could you share your `C:\Program Files\Graylog\sidecar/logs/sidecar.log`

**Comment by junior466** [comment]
> Could you share your `C:\Program Files\Graylog\sidecar/logs/sidecar.log`

I have already given up on it as I spent a couple weeks trying to solve it. I can assure you that it was the same message as above located in that log file.

**Comment by mpfz0r** [comment]
@junior466 sorry to hear that. 
But just for the record: Which Windows version did you try this with?

**Comment by junior466** [comment]
It was on Windows Server 2016.
