### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by jbilliau** [Graylog2/collector-sidecar#394]
### Problem description
Is sidecars maintained anymore? There are so many updates to winlogbeats and wondering if another release will ever be scheduled?

### Steps to reproduce the problem

1. ...

### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
* Elasticsearch Version:
* MongoDB Version:

**Comment by mpfz0r** [comment]
We are actually planning a 1.0.3 release quite soon.

https://github.com/Graylog2/collector-sidecar/pull/391

**Comment by mpfz0r** [comment]
1.0.3 will contain current beats packages for windows.
Is there anything else you are missing?

**Comment by therealjoshuad** [comment]
@mpfz0r thats good news, out of curiosity could someone replace the binaries with whatever version they wanted to use, or does the sidecar do any kind of hash verification or version check?

**Comment by mpfz0r** [comment]
@therealjoshuad no, you are free to replace them,
but be aware that only the upcoming graylog `3.2.5` will provide compatibility with beats > 7

see https://github.com/Graylog2/graylog2-server/pull/7879
