### ISSUE TITLE
Filebeat message rate limit or throttle

### ISSUE THREAD

**Issue by zez3** [Graylog2/collector-sidecar#395]
See https://github.com/Graylog2/graylog2-server/issues/6939

**Comment by zez3** [comment]
https://github.com/elastic/beats/issues/17775

**Comment by mpfz0r** [comment]
Thanks for your input. I think we should handle this on the server side.
graylog has the ability to throttle inputs if the journal gets to full,
it's just not trivial to implement this for the beats input :-/

**Comment by zez3** [comment]
This(throttling) already happens but does not bring much. https://docs.graylog.org/en/latest/pages/sending_data.html#input-throttling
Or you mean something else? 

My node journal is filled because of the load and speed with which the messages get from filebeat+sidecars and then the message ingress moves to the second node and so forth. Both GL nodes and the agent host are CPU skyrocketing during this initial state of ingress. 
Perhaps ES will bring a solution to their filebeat.
Should I rename this to rate limiting?

**Comment by zez3** [comment]
What works today and would aid on the agent side of the problem is to set 1 core

https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-general-options.html#_max_procs

And reported here
https://github.com/elastic/beats/issues/2789#issuecomment-253925059

**Comment by mpfz0r** [comment]
> This(throttling) already happens but does not bring much. https://docs.graylog.org/en/latest/pages/sending_data.html#input-throttling
> Or you mean something else?

That's the kind of throttling I'm referring to, yes.
It doesn't work because it's not implemented for the Beats input (yet).

**Comment by zez3** [comment]
> It doesn't work because it's not implemented for the Beats input (yet).

https://docs.graylog.org/en/latest/pages/sending_data.html#throttling-criteria
I see, it's the 3rd criteria point that would be used for this case. Still it would be nice to be able to change this value of 20k mess/sec

3.Throttling will occur if the Journal is growing in size rapidly (approximately 20k entries per second or greater).

**Comment by zez3** [comment]
Looks like Elastic fixed it. From Filebeat 7.11 onward there is a new message limit that you can set.
https://www.elastic.co/guide/en/beats/filebeat/master/rate-limit.html

**Comment by zez3** [comment]
"Events that exceed the rate limit are dropped"
