### ISSUE TITLE
Sending Windows Event Collector logs to graylog with collector-sidecar

### ISSUE THREAD

**Issue by dynamiccontent** [Graylog2/collector-sidecar#396]
Hello,
I want to setup Windows Event Collector on one machine and then from that machine send all the logs to graylog with collector-sidecar. Is this something that is possible to do?
https://docs.microsoft.com/en-us/windows/win32/wec/windows-event-collector

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
