### ISSUE TITLE
When "read since start" is unchecked it appears that "save read position" has no effect.

### ISSUE THREAD

**Issue by pray4mojo** [Graylog2/collector-sidecar#40]
### Problem description
When restarting the collector-sidecar service all monitored logs are completly resent to the graylog server when the "Read since start" checkbox is unchecked in the input section of the collector configuration whether or not you have "Save read position" checked.  

I could be mistaken on the intent, but I would assume that checking "Save read position" and unchecking "Read since start" would send the entire log file on the first run and then only send changes from there on out.

When "read since start" is unchecked it appears that "save read position" has no effect.

### Steps to reproduce the problem

In the collector configuration, inputs section.

1)Uncheck "Read since start"
2)Check "Save read position"
3)Restart the collector-sidecar service

The entire log file is sent every time the service is restarted.

### Environment

* Sidecar Version: 0.0.8
* Graylog Version: 2.0.3
* Operating System: Centos 6
* Elasticsearch Version: 2.3
* MongoDB Version: 3.2.8

**Comment by mariussturm** [comment]
Thanks for the report, could you please provide the two generated nxlog configuration files?

**Comment by pray4mojo** [comment]
Configs attached.  It appears to be updating the config correctly, but for some reason its not saving the last read position.    Does restarting the sidecar service clear the nxlog cache?

[nxlog_unchecked.conf.txt](https://github.com/Graylog2/collector-sidecar/files/372117/nxlog_unchecked.conf.txt)
[nxlog_checked.conf.txt](https://github.com/Graylog2/collector-sidecar/files/372118/nxlog_checked.conf.txt)

**Comment by mariussturm** [comment]
Did you delete the NXlog `default-snippet`? The `CacheDir` is defined in there, thats the directory where NXlog stores the file position. Also make sure that the directoy is writable by the NXlog user.

**Comment by pray4mojo** [comment]
Default snippet is below.  I added a check for the module dir since I'm running on Centos, but that's it.  If I log in as the nxlog user I'm able to write into /var/spool/collector-sidecar/nxlog

```
{{if .Linux}}
User nxlog
Group nxlog
{{if eq .LinuxPlatform "debian"}}
Moduledir /usr/lib/nxlog/modules
{{end}}
{{if eq .LinuxPlatform "redhat"}}
Moduledir /usr/libexec/nxlog/modules
{{end}}
CacheDir /var/spool/collector-sidecar/nxlog
PidFile /var/run/graylog/collector-sidecar/nxlog.pid
define LOGFILE /var/log/graylog/collector-sidecar/nxlog.log
LogFile %LOGFILE%
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%LOGFILE%', 7);
     </Schedule>
</Extension>
{{end}}
{{if .Windows}}
Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%ROOT%\data\nxlog.log', 7);
     </Schedule>
</Extension>
{{end}}
```

nxlog is running as the nxlog user
```
[root@VM-DEVELOPER-B2C-QJ5MBKT1S7YD nxlog]# ps -ef | grep collector
root     11022     1  0 13:20 pts/0    00:00:00 /usr/bin/graylog-collector-sidecar
nxlog    11062 11022  1 13:20 pts/0    00:00:04 /usr/bin/nxlog -f -c /etc/graylog/collector-sidecar/generated/nxlog.conf
```

**Comment by mariussturm** [comment]
Odd, the important line `CacheDir /var/spool/collector-sidecar/nxlog` is missing in your generated configuration.

**Comment by pray4mojo** [comment]
Looks like the conditional around the platform was stopping the linux conditional.    I reconfigured how I'm handling the collector conigs.  I removed the default snippet from the 2 I was using and created a new collector config that is just the snippet.  The generated nxlog.conf looks better now, but I'm still not getting anything written to the cachedir.  I tried pointing the cachedir to /tmp to make sure there wasn't a permissions problem in the write, but that didn't change anything.

I turned on debug logging in the config and I do get this line that says its not writing a cache file.  I'm not very familiar with what the nxlog.conf should look like.  Is there something missing that would be causing that or does this point more to an issue with nxlog?


```
2016-07-21 13:05:03 DEBUG no entries found, not writing configcache.dat
2016-07-21 13:05:03 DEBUG nxlog_shutdown() leave
2016-07-21 13:05:06 DEBUG reading config cache from /var/spool/collector-sidecar/nxlog/configcache.dat
```



[collector_sidecar.yml.txt](https://github.com/Graylog2/collector-sidecar/files/376863/collector_sidecar.yml.txt)
[nxlog.conf.txt](https://github.com/Graylog2/collector-sidecar/files/376864/nxlog.conf.txt)

**Comment by pray4mojo** [comment]
Not that it necessarily would have fixed things, but I get the same behavior on 0.9-alpha 2.

**Comment by mariussturm** [comment]
Could you try if setting the `SpoolDir` to some directory nxlog can write to fixes the issue? E.g. `SpoolDir /tmp`

**Comment by mariussturm** [comment]
Please also test version 0.0.9-alpha.3, there is a change in the way the collector is finished to give a chance to write the file position to disk.

**Comment by pray4mojo** [comment]
Setting SpoolDir to /tmp on 0.0.9-alpha.2 didn't fix the issue.

Running 0.0.9-alpha.3 fixed the issue.  configcache.dat is now being written.  

Thank you Sir!

**Comment by mariussturm** [comment]
Thank you for the report!
