### ISSUE TITLE
Please make a new release with go modules

### ISSUE THREAD

**Issue by roopakv** [Graylog2/collector-sidecar#401]
Please make a new release with go modules so that brew can be unblocked from using the old non go module way of installing tools.

https://github.com/Homebrew/homebrew-core/issues/47627

**Comment by juju2112** [comment]
@roopakv I'll take care of it!

**Comment by juju2112** [comment]
@roopakv Release [1.1.0](https://github.com/Graylog2/collector-sidecar/releases/tag/1.1.0) now has go modules included. Let me know if there are any issues with it.
