### ISSUE TITLE
sidecar log4j cve

### ISSUE THREAD

**Issue by dio99** [Graylog2/collector-sidecar#419]
Hi is the sidecar vuln for the log4j cve ? our interal scan tool indicates it
this was sidecar version 1.0.2
wounder if it will show same on 1.1

### Steps to reproduce the problem

1. ...

### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
* Elasticsearch Version:
* MongoDB Version:

**Comment by mpfz0r** [comment]
@dio99 the sidecar is written in Go and does not include a log4j library. So, no. Not vulnerable.
