### ISSUE TITLE
FileBeats configuration options

### ISSUE THREAD

**Issue by tehpanta** [Graylog2/collector-sidecar#42]
### Problem description
Inability to add "tail_files" flag to filebeats inputs in sidecar configuration.

While collecting large number of large log files that rotate hourly, after starting up the sidecar + filebeats, it burns down the whole GrayLog infrastructure. It starts to send huge amounts of data to graylog server (20k messages per second is a maximum our datastore is able to handle in testing environments, 40k on production) and causes graylog to be inaccessible untill it handles all the messages from all logfiles.

### Steps to reproduce the problem
1. Collect large amount of logfiles with large number of entries.
2. Start up sidecar + collector
3. Profit...I mean, watch the infrastructure and data store burn :)

### Environment
* Sidecar Version: 1.1.0 beta 1
* Graylog Version: 2.1.0 beta 1
* Operating System: RedHat 7
* Elasticsearch Version: 2.2.0
* MongoDB Version:  2.7

**Comment by mariussturm** [comment]
Fixed by https://github.com/Graylog2/graylog-plugin-collector/commit/1585e03fae120da01df9a6f2b46881af3d5f3b00
