### ISSUE TITLE
Windows services sometimes doesn't start after reboot

### ISSUE THREAD

**Issue by chris-y** [Graylog2/collector-sidecar#421]
### Problem description
The Windows services sometimes doesn't start after a reboot.

### Steps to reproduce the problem

1. Reboot!

### Environment

* Sidecar Version: 1.1.0

### Potential solution

I've been changing the startup type to "Automatic (delayed) from "Automatic".  This seems to resolve it in most cases.  Occasionally I still see it not starting but it is rarer.  If no better solution can be found, making this the default when the service is installed would definitely help.

I'm not getting anything in the sidecar logs to indicate what the problem is.

**Comment by l0calhost** [comment]
Can reproduce. We're seeing the issue in a higher frequency when servers are rebooted after/while patching.
