### ISSUE TITLE
Beats service won't start on Windows Server 2012.

### ISSUE THREAD

**Issue by reg1oDATA** [Graylog2/collector-sidecar#434]
### Problem description

When applying a Filebeat or Winlogbeat configuration to a Graylog Sidecar running on Windows Server 2012, the sidecar throws this error message:

**time="2022-07-28T08:00:29+02:00" level=error msg="[winlogbeat] Unable to validate configuration, timeout reached." **

Sometimes, the above error will not occur. The following error will occur instead:

**Could not start service: The service did not respond to the start or control request in a timely fashion.**

### Environment

* Sidecar Version: 1.2.0
* Graylog Version: 4.3.3
* Operating System: Windows Server 2012
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.2.21

![image](https://user-images.githubusercontent.com/108670964/181435475-dc5a6ec2-f33e-4210-9535-ec9c457ab255.png)

**Comment by patrickmann** [comment]
I think you are running into the 30 second timeout. There is already an issue to make that more flexible: Graylog2/collector-sidecar#431

**Comment by reg1oDATA** [comment]
hi @patrickmann, 
we also suspect that the problem is related to the timeout. when we start winlogbeat manually everything works as well.

**Comment by mpfz0r** [comment]
https://github.com/Graylog2/collector-sidecar/pull/436
