### ISSUE TITLE
Windows Install should use the latest available 7.x binaires for Winlogbeat and Filebeat (or if supported 8.x)

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/collector-sidecar#437]
### Problem description
The windows release for Graylog-sidecar includes the following binaries:

* filebeat, Ver 7.11.1, released February 17, 2021
* winlogbeat, Ver 7.11.1, released February 17, 2021 

Can these be updated to the latest 7.x?

Also is there a specific reason why 8.x can't be used? (hopefully this isn't too naive of a question, i've not researched this topic)

Happy to discuss further, feel free to ping me.

**Comment by boosty** [comment]
Related: https://github.com/Graylog2/collector-sidecar/issues/426

**Comment by mpfz0r** [comment]
now that we fixed the source field problem with newer beats*, we can try and look into updating
winlog and filebeat

* see https://github.com/Graylog2/graylog2-server/pull/13895

**Comment by ITJamie** [comment]
bumping this. graylog has supported the 8.x collectors since https://github.com/Graylog2/graylog2-server/pull/13895 was merged. 
the old winlogbeat in the sidecar is an issue on new windows installs
