### ISSUE TITLE
Can Graylog sidecar support collect log and send to server as GELF

### ISSUE THREAD

**Issue by Marco-Zheng** [Graylog2/collector-sidecar#438]
### Problem description

Now i use Graylog sidecar with filebeats sent log to graylog, but i want to define the tags when i send to graylog server, so that we do not need use pipeline or exactor to extract tag from log, it's very performance-intensive

### Steps to reproduce the problem

If there any method to send the log as GELF when i use Graylog sidecar collect log file and send to log server, as i know, fluent can collect log file and send as GELF, do i use Graylog sidecar control the fluent?

### Environment

* Sidecar Version: 1.2.0
* Graylog Version: 4.2
* Operating System: Linux
* Elasticsearch Version: 7.4.2
* MongoDB Version: 4.2

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
