### ISSUE TITLE
Feature Request: Customer block for input and global output

### ISSUE THREAD

**Issue by Wernervdmerwe** [Graylog2/collector-sidecar#44]
All our Graylog servers are behind a single load balancer, thus the output for every input will be one of three options.
When selecting an output for an input, might be helpful to have a drop-down with global ones with one option being 'new'?

Also, as mentioned in the Google group, having the option to add a custom snippet to a specific input will be hugely helpful in our setup. 
This encompasses mostly Exec statements, breaking up the log entry into key/value  pairs via regex and adding some custom fields.

Maybe in the output as well seeing we add some specific fields/values to the log based on app name, environment etc.

This is similar to https://github.com/Graylog2/graylog-plugin-collector/commit/be22699ef5d8c0ec6b392d297640b1b1f4c62abc, but only for sidecar

**Comment by Wernervdmerwe** [comment]
My bad, I see this was already added
https://github.com/Graylog2/collector-sidecar/issues/13

**Comment by mariussturm** [comment]
Hi Werner,
thanks for the feedback. The Exec statements can be added to a NXlog input/output in the current beta. There is an expandable text area where you can add arbitrary configuration lines. You can test it by using Graylog 2.1.0-beta.2 with Sidecar 0.0.9-beta.1.

Your use-case of the output assignment is something I dont fully get yet. Could you please elaborate a little bit more on that, maybe with a screenshot or so?

**Comment by mariussturm** [comment]
Closing this now, feel free to ping us when you have more informations.

**Comment by Wernervdmerwe** [comment]
Yip, all good. Was traveling, will check those versions out. 

Admittedly I won't be able to put them in prod until they're part of an official release, but I'll try put a dev box up with those versions. 

Thanks!
