### ISSUE TITLE
update interval > 60 causes server to be marked as inactive

### ISSUE THREAD

**Issue by chris-y** [Graylog2/collector-sidecar#446]
### Problem description

If the update_interval in the sidecar.yml file is set to a value higher than 60, Graylog marks the server as inactive after 60 seconds until the next update.

Graylog should receive the information about how often the server/sidecar sends updates and base the "inactive" flag on that.

### Steps to reproduce the problem

1. Set update_interval: 300
2. Wait about a minute
3. Server shows as inactive in the Sidecar area in Graylog until the next update

### Environment

* Sidecar Version: 1.2.0
* Graylog Version: 4.3.7
* Operating System: Windows
* Elasticsearch Version: N/A
* MongoDB Version: N/A

**Comment by chris-y** [comment]
Hi, yes that has worked, thank you. Is this documented anywhere? As it's a bit hidden away!

**Comment by thll** [comment]
I think the docs are indeed missing. I've added it to our list of documentation TODO items.
