### ISSUE TITLE
Graylog sidecar uses up all TCP ports

### ISSUE THREAD

**Issue by JohnnyGranberg** [Graylog2/collector-sidecar#45]
### Problem description
The graylog sidecar service eats up all ports, when listing ports using netstat the output is filled with:

Proto  Local Address          Foreign Address        State
TCP    x.x.x.x:52991     x.x.x.x:80       ESTABLISHED

this list continues to grow until all ports are exhausted.

The foreign address correlates with the API endpoint.

I have the same issue on all the machines i installed the Graylog Sidecar on.

### Steps to reproduce the problem

Install Graylog collector, start service, wait.

### Environment

* Sidecar Version: Graylog Collector Sidecar version 0.0.9 (0.0.9-beta.2)
* Graylog Version:  Graylog 2.0.3 (f07c170) (Oracle Corporation 1.8.0_101 on Linux 4.4.0-31-generic)
* Operating System: Windows Server 2012 R2

**Comment by mariussturm** [comment]
Hi,
do you see any error in /var/log/syslog or /var/log/graylog/collector-sidecar ?

**Comment by mariussturm** [comment]
Respectively on Windows you can run the Sidecar in a CMD window and look for errors on the console.

**Comment by JohnnyGranberg** [comment]
There was no errors in the log, this problem seems to be partially my fault, i was calling the api through our load balancer, which has the default setting of "Keep client alive" that seems to work fine for browsers, and after i disabled that setting, everything seems to work.

Normally the established connections should be reused, but the sidecar seems to be creating a new client with each request, which is fine, as long as the "server" in this case a load balancer doesnt force the connection to be kept alive.

**Comment by mariussturm** [comment]
Alright, closing this.
