### ISSUE TITLE
How do we download the sidecar installer for 1.3.0?

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/collector-sidecar#458]
### Problem description

I'm hoping to test the new tags feature with sidecar 1.3.0 but cannot find a windows installer for 1.3.0 :(

**Comment by drewmiranda-gl** [comment]
Found the issue and this is more of a github issue but can cause some confusion:
![image](https://user-images.githubusercontent.com/107503402/207975639-8da30864-94f8-4fbc-86c0-3654497079f2.png)

**Comment by bernd** [comment]
@drewmiranda-gl Thanks for the report. We had another user having the same issue. We removed the Sidecar binaries from the release page for now so the only Windows download option is the installer. We will check if there is a better way to display the downloads on the GitHub releases page.
