### ISSUE TITLE
Windows Sidecar 1.3.0 hangs on silent install

### ISSUE THREAD

**Issue by chris-y** [Graylog2/collector-sidecar#459]
### Problem description
When installing the Windows version of the sidecar silently, it hangs after installation.  This prevents automatic deployment as the process never ends.  This is an upgrade from 1.2.

```
C:\> graylog-sidecar-1.3.0-amd64.exe /S -SERVERURL=XXXXXXXXXXXXXXX -APITOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXX
time="2022-12-16T09:34:32Z" level=info msg="Using node-id: 1aa2f048-2afa-4323-8e1e-826d498526ee"
time="2022-12-16T09:34:32Z" level=info msg="No node name was configured, falling back to hostname"
time="2022-12-16T09:34:32Z" level=info msg="Starting signal distributor"
time="2022-12-16T09:34:32Z" level=info msg="[ConfigurationUpdate] update_interval: 300s"
time="2022-12-16T09:34:33Z" level=info msg="Removing stale graylog service graylog-collector-winlogbeat"
time="2022-12-16T09:34:33Z" level=info msg="Uninstalling service graylog-collector-winlogbeat"
time="2022-12-16T09:34:33Z" level=info msg="Adding process runner for: winlogbeat-62b30d079acb0e6c7715eb7d"
time="2022-12-16T09:34:34Z" level=info msg="[winlogbeat-62b30d079acb0e6c7715eb7d] Configuration change detected, rewriting configuration file."
time="2022-12-16T09:34:34Z" level=info msg="[winlogbeat-62b30d079acb0e6c7715eb7d] Starting (svc driver)"
```
Pauses here for a bit, then the next section loops continuously:
```
time="2022-12-16T09:38:53Z" level=error msg="[winlogbeat-62b30d079acb0e6c7715eb7d] Backend finished unexpectedly, sending restart signal"
time="2022-12-16T09:38:54Z" level=info msg="[winlogbeat-62b30d079acb0e6c7715eb7d] Starting (svc driver)"
time="2022-12-16T09:38:54Z" level=error msg="[winlogbeat-62b30d079acb0e6c7715eb7d] Could not start service: The service did not respond to the start or control request in a timely fashion."
time="2022-12-16T09:39:03Z" level=error msg="[winlogbeat-62b30d079acb0e6c7715eb7d] Backend finished unexpectedly, sending restart signal"
time="2022-12-16T09:39:04Z" level=info msg="[winlogbeat-62b30d079acb0e6c7715eb7d] Starting (svc driver)"
time="2022-12-16T09:39:04Z" level=error msg="[winlogbeat-62b30d079acb0e6c7715eb7d] Could not start service: The service did not respond to the start or control request in a timely fashion."
time="2022-12-16T09:39:14Z" level=error msg="[winlogbeat-62b30d079acb0e6c7715eb7d] Backend finished unexpectedly, sending restart signal"
```

The winlogbeat service does not appear to be running, although an old one is.  This is after an upgrade.
![image](https://user-images.githubusercontent.com/1818803/208070536-564a179d-2059-4acb-8674-8a817618e068.png)

### Steps to reproduce the problem

1. Run installer as in section above.

### Environment

* Sidecar Version: 1.3.0
* Graylog Version: 4.3.10
* Operating System: Windows 2022

**Comment by mpfz0r** [comment]
> `C:\> graylog-sidecar-1.3.0-amd64.exe /S -SERVERURL=XXXXXXXXXXXXXXX -APITOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXX`

are you sure you are using the installer and not the sidecar here?
It should be called `graylog_sidecar_installer_1.3.0-1.exe`

**Comment by chris-y** [comment]
I'm such an idiot!  The installer itself was hidden under "show all assets", so I didn't realise it was a different package.  All good now, thanks!

**Comment by bernd** [comment]
@chris-y Thanks for the report, and sorry for the confusion. This is easy to miss, unfortunately. We removed the Sidecar .exe binaries for now. Most people are probably interested in the installer for Windows.

We will check if there is a better way to publish the binaries to make it less confusing.
