### ISSUE TITLE
Sidecar hangs during restart

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/collector-sidecar#463]
[HS 1308449306]

### Problem description
When attempting to restart a Sidecar, the restart process hangs and gets stuck in an infinite loop if the shutdown of the sidecar takes more than 5 seconds. 

A possible source of the issue is here, where a 5 second timeout is hard-coded:
https://github.com/Graylog2/collector-sidecar/blob/1.3/daemon/exec_runner.go#L264

The problem might also be compounded by large sidecar configurations. 

### Environment

* Sidecar Version: 1.2.0
* Graylog Version: 4.3.9
* Operating System: 
* Elasticsearch Version:
* MongoDB Version:

**Comment by mpfz0r** [comment]
Fixed with #462
