### ISSUE TITLE
Document current nxlog CE millisecond precision issue with GELF output

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/collector-sidecar#47]
### Problem description
nxlog CE (as of 2.9.17) does not currently send milliseconds in the GELF `timestamp` field, so Graylog shows something like `2016-08-23 13:50:58.000`.  Without doing some special handling (e.g. we're extracting the full timestamp from the message on the Graylog side and overwriting `timestamp`) messages are out of order within a 1 second window.  It may save others some time if this limitation is mentioned in the Collector Sidecar documentation.

See:  https://nxlog.co/question/1855/gelf-timestamp-field-missing-millisecond-precision

**Comment by jalogisch** [comment]
maybe you can create a PR with this? https://github.com/Graylog2/documentation

thank you

**Comment by mariussturm** [comment]
Added in this commit: https://github.com/Graylog2/documentation/commit/96a6486ed25d1433ce18a34892cc1caa05472f70

**Comment by coffee-squirrel** [comment]
@jalogisch Normally I would, but I didn't since it's currently unclear (on my side) how involved I can get.
