### ISSUE TITLE
Graylog Sidecar does not work with redirect

### ISSUE THREAD

**Issue by chris-y** [Graylog2/collector-sidecar#473]
### Problem description
Our Graylog Cloud service has been redirected, and now no devices are communicating.

The following appears in the log of one of our Linux servers every minute or so:
```
Jul 11 13:47:28 monitoring graylog-sidecar[1291026]: time="2023-07-11T13:47:28+01:00" level=error msg="Error fetching server version invalid character '<' looking for beginning of value"
Jul 11 13:47:28 monitoring graylog-sidecar[1291026]: time="2023-07-11T13:47:28+01:00" level=error msg="[UpdateRegistration] Bad response from Graylog server: 200 OK"
```

I'm not sure if it is the sidecar or the way the redirect has been done which is causing the problem.

### Environment

* Sidecar Version: The logs are from Linux v1.3.0 but most of our devices are running Windows v1.4.0
* Graylog Version: Cloud 5.1.3

**Comment by mpfz0r** [comment]
> Our Graylog Cloud service has been redirected

what kind of redirect? the sidecar http client should follow up to 10 consecutive HTTP redirects automatically.

**Comment by chris-y** [comment]
Looks like a 302.
Curl is giving this error though:
* error:0A000152:SSL routines::unsafe legacy renegotiation disabled
* Closing connection 1
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled

**Comment by chris-y** [comment]
This has been fixed on the cloud side, so nothing to do here!
