### ISSUE TITLE
Collector-Sidecar adds unwanted code to my snippets

### ISSUE THREAD

**Issue by clintmaples** [Graylog2/collector-sidecar#48]
### Problem description
In my snippet I need to define an extension with the ShortMessageLength option. I get error messages saying the extension is already defined. Looking at the generated nxlog.conf I see the following:

```
define ROOT C:\Program Files (x86)\nxlog

<Extension gelf>
  Module xm_gelf
</Extension>
```

I can't seem to control the first 5 lines of this config file. Collector Sidecar generates it automatically. In the snippet I've written the following:
```
<Extension gelf>
  Module xm_gelf
  ShortMessageLength -1
</Extension>
```
This conflicts with the extension definition that sidecar creates automagically and generates configuration error messages in NXLOG and ignores the "ShortMessageLength -1" line

In other words my config file looks like this:

```
<Extension gelf>
  Module xm_gelf
</Extension>

Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log
LogLevel DEBUG

<Extension gelf>
  Module xm_gelf
  ShortMessageLength -1
</Extension>
```
Instead of this:
```
Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log
LogLevel DEBUG

<Extension gelf>
  Module xm_gelf
  ShortMessageLength -1
</Extension>
```
I can run nxlog on it's own and my config file works fine. The first 5 lines that graylog side adds to my config breaks it.

### Steps to reproduce the problem
Create a new collector configuration and just use a custom snippet.

### Environment

* Sidecar Version: 0.0.8 x64
* Graylog Version: Graylog 2.0.3 (f07c170) 
* Operating System: Red Hat Enterprise Linux Server release 6.8 (Santiago)
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.2.8

**Comment by mariussturm** [comment]
Hi,
right the first lines are always generated, why do you need `ShortMessageLength -1` in the first place?

**Comment by joschi** [comment]
@mariussturm I suppose for reasons related to Graylog2/graylog-plugin-collector#6 (which are fixed in the most recent version, but not in version 0.0.8 of the collector sidecar).

**Comment by mariussturm** [comment]
Then I would recommend to update (Graylog 2.1.0 and Sidecar 0.0.9 are around the corner), I dont see a good way to make this configurable in the web ui.

**Comment by clintmaples** [comment]
The log messages were being truncated at 64 characters. ShortMessageLength -1 prevents this. I did find another way to prevent this though which was to add Exec $ShortMessage = $raw_event; to the output section:
```
<Output out>
	Module om_udp
	Host 10.0.0.1
	Port 12201
	OutputType GELF
	Exec $ShortMessage = $raw_event;
</Output>
```
