### ISSUE TITLE
Windows Kompatibilität

### ISSUE THREAD

**Issue by FlorianSu** [Graylog2/collector-sidecar#496]
### Problem description
Hello,

which of the Sidecar versions is compatible with Windows Server version 2008? Do any of you here have experience?
I don't want to install it just like that.

Greetings from Germany

**Comment by sethgraylog** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) 

Thank you!
