### ISSUE TITLE
FeatureRequest: windows msi file instead of exe

### ISSUE THREAD

**Issue by matthgyver** [Graylog2/collector-sidecar#50]
Hi,
Is it possible to have windows installer file in msi format ?
It's more usefull to deploy with Active Directory.
Thank you

**Comment by mariussturm** [comment]
Hi,
we are building all packages on a Linux host and I haven't found good tooling for creating MSIs yet.
The package configurations are also open source if you like to dig into this feel free to contibute: https://github.com/Graylog2/collector-sidecar/tree/master/dist

What exactly is the problem with AD?

**Comment by joschi** [comment]
@mariussturm It's possible to rollout software with AD: https://support.microsoft.com/en-us/kb/816102

**Comment by matthgyver** [comment]
MSI format is more usefull for installation by GPO.
There is a built-in feature in gpedit to install / uninstall msi but not for exe.
Exe need a script. It's less integrated.

Unfortunately I know nothing in msi package building otherwise I would participate with pleasure.

**Comment by mariussturm** [comment]
Looked into the msi tools again and I think it's currently too much work to switch for the provided value. If someone wants to contribute that I am happy to review and test pull-requests but it's currently not on our roadmap.
