### ISSUE TITLE
Compile by source with glide having error in freebsd 10.2 amd64

### ISSUE THREAD

**Issue by skythink** [Graylog2/collector-sidecar#55]
### Problem description
```
[root@myfreebsd ~/work/src/collector-sidecar]# gmake build
go build -ldflags "-s -X github.com/Graylog2/collector-sidecar/common.GitRevision=d4c2910" -v -i -o graylog-collector-sidecar
github.com/Graylog2/collector-sidecar/vendor/github.com/cloudfoundry/gosigar
#github.com/Graylog2/collector-sidecar/vendor/github.com/cloudfoundry/gosigar
/usr/local/go/src/github.com/Graylog2/collector-sidecar/vendor/github.com/cloudfoundry/gosigar/sigar_unix.go:18: invalid operation: int64(stat.Blocks) * uint64(bsize) (mismatched types int64 and uint64)
/usr/local/go/src/github.com/Graylog2/collector-sidecar/vendor/github.com/cloudfoundry/gosigar/sigar_unix.go:19: invalid operation: int64(stat.Bfree) * uint64(bsize) (mismatched types int64 and uint64)
/usr/local/go/src/github.com/Graylog2/collector-sidecar/vendor/github.com/cloudfoundry/gosigar/sigar_unix.go:20: invalid operation: int64(stat.Bavail) * uint64(bsize) (mismatched types int64 and uint64)
/usr/local/go/src/github.com/Graylog2/collector-sidecar/vendor/github.com/cloudfoundry/gosigar/sigar_unix.go:23: stat.Free undefined (type syscall.Statfs_t has no field or method Free)
gmake: *** [Makefile:53: build] Error 2
```
### Steps to reproduce the problem

1. ... hi im try to install collector sidecar in freebsd 10.2 amd64. im success to install go1.7 and glide newer version glide-v0.12.2-freebsd-amd64.tar.gz . 
im compile using GMAKE no MAKE coz in distribution UNIX. 
when im try GMAKE BUILD i have error in above..

anyone can help me ??? 

### Environment

* Sidecar Version: ...
* Graylog Version: 2.1.0
* Operating System: Freebsd 10.2 64amd
* Elasticsearch Version: 2.4.0
* MongoDB Version: 3.2.9

**Comment by joschi** [comment]
@skythink gosigar currently doesn't support FreeBSD, so there's not much we can do about it.

Feel free to subscribe to cloudfoundry/gosigar#21 or even provide a PR for the gosigar project.

**Comment by skythink** [comment]
@joschi  thanks for reply, i think i will use another forwarder log like rsyslog to send log ... :)
