### ISSUE TITLE
Run directory not configurable (fails when non-root user)

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/collector-sidecar#58]
_From @ente187 on September 19, 2016 11:26_

Hello Mates,

i was recommented to create a GH-Issue, so here is my issue. Hope you can help me out :)
i would like to achieve an architecture like shown on the left side of this picture(because i want to use NXLog): http://docs.graylog.org/en/2.1/_images/sidecar_overview.png. I have already installed Graylog2 on my RedHat Server and now i'm currently working on the configuration of collector-sidecar. As i'm working as nonroot, i had to change several directories in configuration files of collector-sidecar and NXLog. Now to the problem: Everytime i try to start collector sidecar, i get INFO/Error- Messages: 

```
[gunge@bsul0959 bin]$ ./graylog-collector-sidecar -c /opt/ansible/sidecar/etc/graylog/collector-sidecar/collector_sidecar.yml
INFO[0000] Using collector-id: 13a3d80f-cb69-4391-8520-7a760b9b964e
INFO[0000] Fetching configurations tagged by: [linux apache syslog]
ERRO[0000] stat /var/run/graylog/collector-sidecar: no such file or directory
INFO[0000] Trying to create directory for: /var/run/graylog/collector-sidecar/nxlog.run
ERRO[0000] Not able to create directory path: /var/run/graylog/collector-sidecar
INFO[0000] Starting collector supervisor
ERRO[0010] [UpdateRegistration] Sending collector status failed. Disabling `send_status` as fallback! PUT http://127.0.0.1:12900/plugins/org.graylog.plugins.collector/collectors/13a3d80f-cb69-4391-8520-7a760b9b964e: 400 Unable to map property tags.
Known properties include: operating_system
```

 After this start procedure, a collector appears on my Graylog Web-Interface, but if i abort the start procedure, the collector disappears again. During the start procedure, it tries to create a path in /var/run/graylog/collector-sidecar but as i am not root, it can't. As a consequence, he can't create nxlog.run in that directory. I already tried to change the path to a place where i don't need root permissions, but i think there is no configuration file where i can do this. So i looked into the binary of collector-sidecar and found this:

```
func (nxc *NxConfig) ValidatePreconditions() bool {
     if runtime.GOOS == "linux" {
          if !common.IsDir("/var/run/graylog/collector-sidecar") {
                err := common.CreatePathToFile("/var/run/graylog/collector-sidecar/nxlog.run")
                if err != nil {
                     return false
                }
          }
     }
     return true
}
```
It seems, that the path is coded into the application and there is no way to configure anoter path. Do you see a solution besides getting root permissions?

Thank you in advance!

 

## Steps to Reproduce (for bugs)
Here is an example on how to configure and start collecor sidecar: 
[http://docs.graylog.org/en/2.1/pages/collector_sidecar.html](url)

## Context

Here is the collector that appears when i try to start Collector-Sidecar:
![collector](https://cloud.githubusercontent.com/assets/22288851/18630196/24bd9692-7e6b-11e6-9672-d3b42c3640ac.JPG)
This is my collector_sidecar.yml:
![collector sidecaryml](https://cloud.githubusercontent.com/assets/22288851/18630234/64e0820c-7e6b-11e6-991d-008038f9a091.JPG)
This is the NXLog conf file:
![nxlogconf](https://cloud.githubusercontent.com/assets/22288851/18630292/d1bf3814-7e6b-11e6-97d2-ce24df6d5c8d.JPG)

**Environment**

- Linux version 2.6.32-573.18.1.el6.x86_64 (mockbuild@x86-010.build.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) )
- Architecture:          x86_64
- CPU op-mode(s):        32-bit, 64-bit
- Byte Order:            Little Endian
- CPU(s):                8
- On-line CPU(s) list:   0-7
- Thread(s) per core:    1
- Core(s) per socket:    1
- Socket(s):             8
- NUMA node(s):          1
- Vendor ID:             GenuineIntel
- CPU family:            6
- Model:                 13
- Stepping:              3
- CPU MHz:               3192.306
- BogoMIPS:              6384.61
- Hypervisor vendor:     KVM
- Virtualization type:   full
- L1d cache:             32K
- L1i cache:             32K
- L2 cache:              4096K
- NUMA node0 CPU(s):     0-7

**Graylog Version:** Graylog 2.0.0
**Collector Sidecar: 0.0.9-1.x86_64
**Elasticsearch Version:** elasticsearch-2.3.2
**MongoDB Version:** v3.2.6
**Operating System:** Linux version 2.6.32-573.18.1.el6.x86_64 (mockbuild@x86-010.build.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) )
**Browser version:** IE 11.0.9600.18426

_Copied from original issue: Graylog2/graylog2-server#2850_

**Comment by mariussturm** [comment]
@ente187 thanks for the detailed report, I will look into this and try to make the PID directory configurable in the next release.

**Comment by ente187** [comment]
Thank you for your effort! @mariussturm

**Comment by jessecarbon** [comment]
I'm wondering if I'm seeing this manifest itself differently. When I run `/usr/bin/graylog-collector-sidecar` as root I'm seeing an error every few seconds, but it's not clear why:
```
$ /usr/bin/graylog-collector-sidecar
INFO[0000] Using collector-id: e3f3dce0-7c2a-4f05-9bf5-5d813de61bc4
INFO[0000] Fetching configurations tagged by: [cbserver]
INFO[0000] Starting collector supervisor
INFO[0000] [filebeat] Starting
ERRO[0010] stat true: no such file or directory
INFO[0010] [filebeat] Configuration change detected, rewriting configuration file.
INFO[0010] [filebeat] Stopping
INFO[0014] [filebeat] Starting
ERRO[0020] stat true: no such file or directory
ERRO[0030] stat true: no such file or directory
ERRO[0040] stat true: no such file or directory
ERRO[0050] stat true: no such file or directory
ERRO[0060] stat true: no such file or directory
ERRO[0070] stat true: no such file or directory
ERRO[0080] stat true: no such file or directory
ERRO[0090] stat true: no such file or directory
ERRO[0100] stat true: no such file or directory
ERRO[0110] stat true: no such file or directory
ERRO[0120] stat true: no such file or directory
ERRO[0130] stat true: no such file or directory
ERRO[0140] stat true: no such file or directory
ERRO[0150] stat true: no such file or directory
ERRO[0160] stat true: no such file or directory
ERRO[0170] stat true: no such file or directory
```

It seems like it's failing in the same place, but it's trying to stat `true` instead of a directory. I'm also running it as root, so there should be no permissions issues. I noticed this because even when running as a service, `/var/log/messages` is constantly being filled with this error. This is using the `collector-sidecar-0.0.9-1.x86_64` RPM on `CentOS release 6.7`.

Please let me know if this should be a separate bug report. Thanks!

**Comment by mariussturm** [comment]
@jessecarbon not sure where this comes from, but it has nothing to do with the issue. Did you make sure that all collectors are installed on the system that are set to `enabled: true` and that the path to the binary works? You can create a new issue if you think your configuration is correct.

**Comment by jessecarbon** [comment]
@mariussturm yeah, all the collectors that are enabled are installed, everything seems to be working properly. I'll create a new issue.

**Comment by jessecarbon** [comment]
Sorry to cloud up this closed issue, but @mariussturm I figured it out. The [default config file](https://github.com/Graylog2/collector-sidecar/blob/b408d8d7cdf5ee31d7530e2c4fc1bc1e673a82ac/collector_sidecar.yml#L5) has:
```
list_log_files:
```
I assumed this was a boolean, so I set it to true. Turns out that needs to be a directory or list of directories to send to the server.

**Comment by mariussturm** [comment]
@ente187 please install 0.1.0-alpha.2 and use the `run_path` option in the nxlog backend section to configure a changed `PIdFile` path. Also set the `PidFile` path in the `default-snippet` in the web interface.

**Comment by rafaldomeracki** [comment]
Hello,

I have made the config as you suggested and now I have **two 'PidFile' params** in the '/etc/graylog/collector-sidecar/generated/nxlog.conf'
```
# cat /etc/graylog/collector-sidecar/generated/nxlog.conf |grep -i pid
PidFile /var/run/nxlog/nxlog.pid
PidFile /var/run/graylog/collector-sidecar/nxlog.pid
```
The existence of two params are misleading.

But there is no permission entry in the '/var/log/graylog/collector-sidecar/nxlog_stderr.log' yet:
`2017-07-10 10:50:12 ERROR Couldn't remove pidfile /var/run/graylog/collector-sidecar/nxlog.pid: Permission denied`

PID number is now in '/var/run/nxlog/nxlog.pid'.

My env:
Centos 7.3 (Graylog server and remote client)
collector-sidecar-0.1.3-1.x86_64
graylog-server-2.1.3-1.noarch
