### ISSUE TITLE
Graylog2/collector-sidecar on Illumos / SmartOS

### ISSUE THREAD

**Issue by drscream** [Graylog2/collector-sidecar#64]
### Problem description

I tried to build `collector-sidecar` on my Illumos / SmartOS zone but receiving the following error. I'm not so skilled in Go so maybe it's something really trivial.

```
GOOS=solaris GOARCH=amd64 go build -ldflags "-s -X github.com/Graylog2/collector-sidecar/common.GitRevision=226e54e" -v -i -o build/0.1.0/solaris/amd64/graylog-collector-sidecar
```

Result:

```
github.com/Graylog2/collector-sidecar/common
# github.com/Graylog2/collector-sidecar/common
common/fs.go:36: undefined: log in log.Error
common/fs.go:50: undefined: log in log.Info
common/fs.go:53: undefined: log in log.Error
common/fs.go:72: undefined: log in log.Errorf
common/fs.go:86: undefined: log in log.Errorf
common/helper.go:84: undefined: log in log.Info
common/helper.go:90: undefined: log in log.Fatal
common/helper.go:96: undefined: log in log.Info
common/sigar.go:131: undefined: log in log.Debug
make: *** [Makefile:59: build-solaris] Error 2
```

### Environment

* Sidecar Version: 226e54e
* Operating System: SmartOS Zone with pkgsrc 16Q2

**Comment by joschi** [comment]
@drscream [gosigar](https://github.com/cloudfoundry/gosigar) currently doesn't support Solaris-based operating systems.

Feel free to open an issue at https://github.com/cloudfoundry/gosigar/issues

**Comment by drscream** [comment]
I would like to thank you for your answer. That's also why I've added the part from the following pull request to the source of `gosigar`: https://github.com/cloudfoundry/gosigar/pull/28

As I wrote I'm not so familiar with Go but doesn't the error reported by different files which are not connected to the `gosigar` issue?

**Comment by joschi** [comment]
@drscream You are correct. Which version of Go are you using?

**Comment by drscream** [comment]
Thanks again for your reply, I'm using the following go version:

```
go version go1.6.3 solaris/amd64
```

**Comment by mariussturm** [comment]
@drscream sorry we dont have the resources to support Solaris officially but if there are some easy changes to do to get it working we can do this of course. I think in the current case the solaris build flag is missing for some parts of the software. You can try to add 'solaris' in  this line and recompile: https://github.com/Graylog2/collector-sidecar/blob/master/common/logger_unix.go#L16

**Comment by bernd** [comment]
@drscream I created a PR for solaris support: https://github.com/Graylog2/collector-sidecar/pull/67

I tested this on the latest OmniOS with `go version go1.7 solaris/amd64`. Can you please test the PR?

Important. as @mariussturm said, we cannot provide official support for this

**Comment by bernd** [comment]
@drscream To build it you have to use the following command line: `gmake build-solaris AWK=gawk`

**Comment by mariussturm** [comment]
Closing this for now because #67 was merged into master. @drscream ping us if you need more help.
