### ISSUE TITLE
support for Beats 5.0.0?

### ISSUE THREAD

**Issue by wjrogers** [Graylog2/collector-sidecar#69]
Elastic is getting close to releasing version 5.0.0 of its products, including Beats. There are some significant improvements in Winlogbeat that we would like to use (particularly the inclusion of the structured Windows event log data as JSON in shipped messages). Unfortunately, the pre-release binaries don't work with collector-sidecar because there are several breaking changes to the format of `winlogbeat.yml`.

Does the graylog project have any plans to support the new version of Beats?

Here's the new default configuration:
https://github.com/elastic/beats/blob/master/winlogbeat/winlogbeat.yml
### Environment
- Sidecar Version: 0.10.0
- Graylog Version: 2.1.1

**Comment by mariussturm** [comment]
Yes this will come in one of the future versions of the Sidecar. Maybe not exactly with the Beats release but we will start to work on it soon.

**Comment by landonix** [comment]
Looking forward to trying sidecar when [5.0](https://www.elastic.co/blog/beats-5-0-0-released) is supported. I've tested since alpha stage and it brings many improvements with parsing Windows events.

**Comment by omercnet** [comment]
+1

**Comment by ken5scal** [comment]
+1

Awsome!

**Comment by mariussturm** [comment]
Beats 5 support is available in 0.1.0-beta.2
