### ISSUE TITLE
RPMs?

### ISSUE THREAD

**Issue by joshrp** [Graylog2/collector-sidecar#7]
I can't find any sign of RPM packages for RHEL 6/7 are they coming soon? Building from source really isn't a good option for me.

**Comment by mariussturm** [comment]
I have added a rpm to the 0.0.3 release, it's not much tested maybe you can provide some feedback here!

**Comment by joshrp** [comment]
I need to get nxlog and 2.0 server up and running before I can be sure but I've installed it and all the init scripts and config look good. Thanks for the quick turnaround!
