### ISSUE TITLE
socket: too many open files

### ISSUE THREAD

**Issue by blackwellops** [Graylog2/collector-sidecar#70]
### Problem description
I am currently getting this error from all my collectors. It occurs after a few hours of the collectors checking in successfully. Restarting the collector sidecar fixes this error. I am using a HTTP load balancer to load balance the API and web UI before two graylog-server nodes. 

```
Sep 26 15:03:49 hostname graylog-collector-sidecar: time="2016-09-26T15:03:49-05:00" level=error msg="[RequestConfiguration] Fetching configuration failed: Get http://10.10.10.10/api/plugins/org.graylog.plugins.collector/242c9f2c-9538-4cb7-a253-8a55cbfbaa38?tags=%5B%22linux%22%2C%22apache%22%5D: dial tcp 10.10.10.10:80: socket: too many open files"
```

### Environment

* Sidecar Version: 0.0.9
* Graylog Version: 2.1.1
* Operating System: Centos 7 and Windows 2012 R2
* Elasticsearch Version: 2.4.0
* MongoDB Version:  3.2.9

**Comment by mariussturm** [comment]
Looks like some component between the Sidecar and the Graylog server keeps the connection open while the Sidecar starts a fresh one to talk to the REST API. Could you please test this also with 0.1.0-alpha.1? We made a change there to re-use http connections so this should fit better to your environemnt.

**Comment by mariussturm** [comment]
Closing this for now, please re-open in case 0.1.0 is not helpful in your environment.
