### ISSUE TITLE
Error starting nxlog on Linux

### ISSUE THREAD

**Issue by lpohl** [Graylog2/collector-sidecar#71]
### Problem description
NXLog will not start because it can't open it's config file.

too much escapeing going on  "\""
strace: 
[pid 11438] open("\"/etc/graylog/collector-sidecar/generated/nxlog.conf\"", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid 11438] write(2, "Failed to open config file \"/etc"..., 107 <unfinished ...>
[pid 11439] <... read resumed> "Failed to open config file \"/etc"..., 32768) = 107

### Steps to reproduce the problem

1. Setup collector via GrayLog Webinterface (Inputs/Outputs/Tags) all that stuff...
2. Setup config for collector-sidecar nxlog backend
backends:
    - name: nxlog
      enabled: true
      binary_path: /usr/bin/nxlog
      configuration_path: /etc/graylog/collector-sidecar/generated/nxlog.conf

3. check that a working config is generated (test it on cmd, by starting nxlog with it)
# nxlog -c /etc/graylog/collector-sidecar/generated/nxlog.conf  -v
2016-09-29 17:48:30 INFO configuration OK

4. start graylog-collector-sidecar and see:
# graylog-collector-sidecar -c /etc/graylog/collector-sidecar/collector_sidecar.yml                             [816/933]
INFO[0000] Using collector-id: acb6a178-4e1f-4eab-af18-a1cc6431d8ff 
INFO[0000] Fetching configurations tagged by: [linux apache] 
INFO[0000] Starting signal distributor                  
INFO[0000] [nxlog] Starting (exec driver)               
ERRO[0000] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration! 
ERRO[0000] [nxlog] Backend crashed, trying to restart 1/3 
INFO[0005] [nxlog] Starting (exec driver)               
ERRO[0005] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration! 
ERRO[0005] [nxlog] Backend crashed, trying to restart 2/3 
INFO[0010] [nxlog] Configuration change detected, rewriting configuration file. 
INFO[0010] [nxlog] Stopping                             
INFO[0010] [nxlog] Starting (exec driver)               
ERRO[0010] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration! 
ERRO[0010] [nxlog] Backend crashed, trying to restart 3/3 
INFO[0015] [nxlog] Starting (exec driver)               
ERRO[0015] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration! 
ERRO[0015] [nxlog] Collector failed to start after 3 tries! 
INFO[0017] [nxlog] Starting (exec driver)               
ERRO[0017] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration! 
ERRO[0017] [nxlog] Backend crashed, trying to restart 1/3 
INFO[0022] [nxlog] Starting (exec driver)               
ERRO[0022] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration! 
ERRO[0022] [nxlog] Backend crashed, trying to restart 2/3 
INFO[0027] [nxlog] Starting (exec driver)               
ERRO[0027] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration! 
ERRO[0027] [nxlog] Backend crashed, trying to restart 3/3 
INFO[0032] [nxlog] Starting (exec driver)               
ERRO[0032] [nxlog] Collector exits immediately, this should not happen! Please check your collector configuration! 
ERRO[0032] [nxlog] Collector failed to start after 3 tries! 

### Solution
 ./backends/nxlog/nxlog.go:81 return []string{"-f", "-c", "\"" + nxc.ConfigurationPath() + "\""} <-- ERRORs out while starting nxlog with: No such File or Directory

./backends/nxlog/nxlog.go:81 return []string{"-f", "-c", nxc.ConfigurationPath() } <-- works as intended 

### Environment

* Sidecar Version: collector-sidecar-0.1.0-1.x86_64
* Graylog Version: graylog-server-2.1.1-1.noarch
* Operating System: CentOS 7.2.1511
* Elasticsearch Version:  elasticsearch-2.4.0-1.noarch
* MongoDB Version:  mongodb-org-server-3.2.9-1.el7.x86_64

**Comment by arogozin** [comment]
`func (nxc *NxConfig) ExecArgs() []string {
	return []string{"-f", "-c", nxc.ConfigurationPath()}
}`

Removing OS check for windows and changing to this return got rid of that error. Status of collector is running, but it does not seem to send messages now. Does it send messages for you?

**Comment by lpohl** [comment]
> Comment from arogozin:

> func (nxc *NxConfig) ExecArgs() []string {
> return []string{"-f", "-c", nxc.ConfigurationPath()}
> }

> Removing OS check for windows and changing to this return got rid of that error. Status of collector is running, but it does not seem to send messages now. Does it send messages for you?

After my change nxlog did start and I was able to modifiy the configuration via Webinterface.
I added some Input and nxlog did get restarted and new messages did appear in graylog.

I didn't check it on Windows, but that is next I will test.

**Comment by mariussturm** [comment]
Right, we need the extra quotes only for Windows so that pathes like C:\\Program<space>Files do work. I think this commit should fix all cases: https://github.com/Graylog2/collector-sidecar/commit/c6bb203fa28aef094621932330bb4f61befcd3d6
Feedback welcome!

**Comment by lpohl** [comment]
Yes, I was thinking that on Windows this makes sense, even on Unix if you have spaces in the path.
But then shouldn't the quotes entered in the config instead of in the code?

NxLog on Linux is indeed working fine with the changes.
Windows I still have to test.

**Comment by mariussturm** [comment]
Closing this for now, I couldn't see any more problems.

**Comment by madchap** [comment]
Hi,

Sorry if I didn't understand everything here, but we assume it is then normal that the collector won't start upon installation, and that one needs to first copy a valid nxlog.conf in the generated folder?

Thank you.
fred

**Comment by joschi** [comment]
@madchap The nxlog configuration file will be generated (hence the name of the directory) once the Graylog Collector Sidecar connected to the Graylog cluster and retrieved its configuration.

Please see http://docs.graylog.org/en/2.1/pages/collector_sidecar.html for the installation and configuration instructions.

**Comment by madchap** [comment]
Indeed! Thanks. In my case, my collector config was missing a tag.
