### ISSUE TITLE
how to configure?

### ISSUE THREAD

**Issue by perler** [Graylog2/collector-sidecar#74]
### Problem description
may be stupidity on my part, but I don't find any documentation how to configure the sidecar

### Steps to reproduce the problem

1. installed
2. error messages in graylog:  Nxlog: Collector failed to start after 3 tries!
3. log shows no configuration for nxlog generated
4. but how to generate it?!

### Environment

* Sidecar Version: 0.1.0-1
* Graylog Version: 2.1
* Operating System: ubuntu 14.04
* Elasticsearch Version: 2.4.1
* MongoDB Version: 1.2.0.6.1.1

**Comment by mariussturm** [comment]
The Sidecar itself doesn't need much configuration. Just the URL to the Graylog API and a list of tags which settings it should fetch from the server. Have a look for it here: http://docs.graylog.org/en/2.1/pages/collector_sidecar.html#configuration

To configure the used collector go to the Graylog web interface and set it up accordingly like documented here: http://docs.graylog.org/en/2.1/pages/collector_sidecar.html#step-by-step-guide
