### ISSUE TITLE
multiple collectors into one input (on th graylog server)?

### ISSUE THREAD

**Issue by perler** [Graylog2/collector-sidecar#77]
### Problem description

the documentation is not quite clear here: do I need one input for each collector (ie server in our case) or does every collector needs his own input?

### Steps to reproduce the problem

1. n/a

### Environment

* Sidecar Version: 0.1.0-1
* Graylog Version: 2.1
* Operating System: ubuntu 14.04
* Elasticsearch Version:
* MongoDB Version:

**Comment by joschi** [comment]
@perler No, multiple collectors can use the same Graylog input (e. g. all Filebeat collectors can use the same Beats input).

**Comment by perler** [comment]
thanks
