### ISSUE TITLE
NXLog configuration

### ISSUE THREAD

**Issue by joshrp** [Graylog2/collector-sidecar#8]
The default configuration written for nxlog puts the modules directory as `/usr/lib/nxlog/modules` but my CentOS 6.6 installation has it in `/var/libexec/nxlog/modules`. If I change this and run nxlog manually to confirm then all is well. 

Maybe this can be solved if there's a default nxlog config that could be pulled at startup to override these thing, binary location and UID/GID I imagine ought to be configurable too.

**Comment by joshrp** [comment]
Ah! After trawling the code for a while, I realised the default settings for the backends are actually sent by the server. This is fine for a short term solution but isn't going to scale as we deploy collectors onto other platforms where the the modules live in a different place and want to share the configs between them.

**Comment by mariussturm** [comment]
The path is stored in the `nxlog-defaults` snippet. Just edit it to your needs.

**Comment by wizhippo** [comment]
@mariussturm `nxlog-defaults` where do you set this?

**Comment by mariussturm** [comment]
@wizhippo it's created automatically for every new configuration. Have a look in the Snippet section and click 'Edit'.

**Comment by wizhippo** [comment]
Found it thanks.  I missed that this setting is in the gui.
