### ISSUE TITLE
[feature] take node_id value from server's hostname

### ISSUE THREAD

**Issue by andrewmeyer** [Graylog2/collector-sidecar#84]
Is it possible to have the node_id taken from the device's hostname and then overridden in the yaml file?  This would greatly assist automated deployments since the node_id would not need to be changed on every server.

**Comment by mariussturm** [comment]
Hi Andrew,
this is already possible. Just leave the node_id field empty like: `node_id:`
After starting the Sidecar with that you will see a log message saying:
`INFO[0000] No node-id was configured, falling back to hostname`
