### ISSUE TITLE
Reading in UTF-16LE Log Files (MSSQL)

### ISSUE THREAD

**Issue by Fossiltalk** [Graylog2/collector-sidecar#86]
### Problem description
I'm trying to read in MSSQL logs, which are UTF-16 LE encoded.  I know I have to modify the filebeat configuration to accommodate this, but whenever I try adding encoding:utf-16le as a beats snippet, it does not appear to change filebeat's behavior.

In graylog, this results in an inability to write extractors for the log messages.  I believe this is because the messages are being read as UTF-8, meaning that UTF-8 character is being read, followed by a null character for each UTF-16 character.  This becomes more evident when you show terms on a log message:

![screenshot 72](https://cloud.githubusercontent.com/assets/12259193/19729112/d8558d1c-9b63-11e6-9563-9e90d5c80861.png)

To get around this an extractor has to be written to re-write the message body without each of those null characters, or to accommodate them in-line, which is rather expensive.

### Steps to reproduce the problem

1.   Importing MSSQL Logs or any other document that is UTF-16 LE encoded should cause the issue to occur.

### Environment

* Sidecar Version: 0.0.9 (stable)
* Graylog Version: 2.1.1+01d50e5
* Operating System: Windows Server 2008 R2 (client)  Ubuntu Server 14.04.5 LTS (server)
* Elasticsearch Version: 2.4.1
* MongoDB Version: 2.4.9

**Comment by joschi** [comment]
@Fossiltalk How exactly are you shipping the logs to Graylog?
Which collector are you using and how did you configure it?

**Comment by Fossiltalk** [comment]
This is with the filebeat collector that is provided with 0.0.9

collector_sidecar.yml
------------------------------------------------------------------------
server_url: {redacted}
update_interval: 10
tls_skip_verify: false
send_status: true
list_log_files:
node_id: {redacted}
collector_id: file:C:\Program Files\graylog\collector-sidecar\collector-id
log_path: C:\Program Files\graylog\collector-sidecar
log_rotation_time: 86400
log_max_age: 604800
tags:
  - Windows
  - MSSQL
backends:
    - name: nxlog
      enabled: false
      binary_path: C:\Program Files (x86)\nxlog\nxlog.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\nxlog.conf
    - name: winlogbeat
      enabled: true
      binary_path: C:\Program Files\graylog\collector-sidecar\winlogbeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\winlogbeat.yml
    - name: filebeat
      enabled: true
      binary_path: C:\Program Files\graylog\collector-sidecar\filebeat.exe
      configuration_path: C:\Program Files\graylog\collector-sidecar\generated\filebeat.yml
-----------------------------------------------------------------------------------------------------------

filebeat.yml
-----------------------------------------------------------------------------------------------------------
filebeat:
  prospectors:
  - document_type: log
    fields:
      gl2_source_collector: 3ac29a55-0e1d-4299-bbb4-40b3d4b5f278
      logfile: ERRORLOG
    ignore_older: 24h
    input_type: log
    paths:
    - C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\Log\ERRORLOG
    scan_frequency: 30s
    tail_files: false
  - document_type: log
    fields:
      gl2_source_collector: 3ac29a55-0e1d-4299-bbb4-40b3d4b5f278
      logfile: FDLAUNCHERRORLOG
    ignore_older: 24h
    input_type: log
    multiline:
      match: after
      negate: false
      pattern: ^[0-9]{1}
    paths:
    - C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\Log\FDLAUNCHERRORLOG
    scan_frequency: 30s
    tail_files: false
  - document_type: log
    fields:
      gl2_source_collector: 3ac29a55-0e1d-4299-bbb4-40b3d4b5f278
      logfile: SQLAGENT.OUT
    ignore_older: 24h
    input_type: log
    multiline:
      match: after
      negate: false
      pattern: ^[0-9]{1}
    paths:
    - C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\Log\SQLAGENT.OUT
    scan_frequency: 30s
    tail_files: false
output:
  logstash:
    hosts:
    - graylog.dev.ardencompanies.com:5600
---------------------------------------------------------------------------------------------------------------

**Comment by mariussturm** [comment]
The 'encoding' option will be available in Graylog 2.2 https://github.com/Graylog2/graylog-plugin-collector/pull/26

**Comment by Fossiltalk** [comment]
Good to know.  Thanks!
