### ISSUE TITLE
identify source filename when using file import modules on log collectors

### ISSUE THREAD

**Issue by andreascalvo** [Graylog2/collector-sidecar#9]
When creating a configuration for collector-sidecar with a file input type, it'd be good to be able to populate a field that stores the filename.
Right now, only the ID and type of the input are stored.

**Comment by mvazquezc** [comment]
+1

**Comment by Spafbi** [comment]
Including the source filename is critical when using wildcards in filenames. I have not been able to identify a method by which the Graylog2 web interface may be used to cause the source "file_name" to be passed and stored as a field.

**Comment by mariussturm** [comment]
We have added a FileName field for the NXLog file input in v0.0.4
