### ISSUE TITLE
"Exec $Hostname = hostname_fqdn();¨ overwriting correct source names when using Windows event forwarding

### ISSUE THREAD

**Issue by fastwalker2k4** [Graylog2/collector-sidecar#91]
### Problem description

I´m setting up a central Windows event collector, with NXLog to forward to Graylog. With a completely default setup, adding only a UDP collector to forward Windows event logs, the events from all different sources end up with the NXLog server name, not the name of the server the event originated from. If I delete the following line from the generated NXLog config, it fixes the problem:  

¨Exec $Hostname = hostname_fqdn();¨.

Everytime the 'collector sidecar' service restarts, the config gets overwritten, so this line comes back and overwrites the source names again.

### Steps to reproduce the problem

1. Start new Graylog Virtual appliance;
2. Create a completely standard collector for the default UDP input;
3. Configure a Windows machine with 'collector sidecar' to use the created collector (only enabling NXLog backend and entering the server IP);
4. The generated config for NXLog should contain the following line: ¨Exec $Hostname = hostname_fqdn();¨. If the Windows machine contains events forwarded from other servers, they will all show the hostname of the NXLog server, instead of their own.

### Steps to fix the problem:

5. Stop 'graylog sidecar collector'
6. Copy the generated config to the standard NXLog config file, removing only the offending line
7. Start the NXLog binary (which will now run with the custom config)
8. Events coming in from the NXLog server, will now correctly show their source names in Graylog

### Environment

* Sidecar Version: 0.1.0
* Graylog Version: 2.1.1+01d50e5, codename Smuttynose
* Operating System: 14.04.1-Ubuntu (default virtual appliance), Windows server 2012 loggee
* Elasticsearch Version: 2.3.1 (default with virtual appliance)
* MongoDB Version: 3.2.5 (default with virtual appliance)

**Comment by mariussturm** [comment]
Could you please post your generated nxlog configuration with and without the change you did?

**Comment by fastwalker2k4** [comment]
Yes. Here is the auto generated NXLog config (which is overwriting the source names):

```
define ROOT C:\Program Files (x86)\nxlog

<Extension gelf>
  Module xm_gelf
</Extension>

Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%ROOT%\data\nxlog.log', 7);
     </Schedule>
</Extension>




<Input 581720cf88a523060108547c>
	Module im_msvistalog
	PollInterval 1
	SavePos	True
	ReadFromLast True
</Input>



<Output 5817209c88a5230601085447>
	Module om_udp
	Host 192.168.1.85
	Port 12201
	OutputType  GELF
	Exec $short_message = $raw_event; # Avoids truncation of the short_message field.
	Exec $gl2_source_collector = 'd011c5ad-60df-4314-b7ea-736a39ef720f';
	Exec $Hostname = hostname_fqdn();
</Output>



<Route route-0>
  Path 581720cf88a523060108547c => 5817209c88a5230601085447
</Route>
```

Here is my manual NXLog config (which fixed the issue):

```
define ROOT C:\Program Files (x86)\nxlog

<Extension gelf>
  Module xm_gelf
</Extension>

Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%ROOT%\data\nxlog.log', 7);
     </Schedule>
</Extension>

<Input 581720cf88a523060108547c>
	Module im_msvistalog
	PollInterval 1
	SavePos	True
	ReadFromLast True
</Input>



<Output 5817209c88a5230601085447>
	Module om_udp
	Host 192.168.1.85
	Port 12201
	OutputType  GELF
	Exec $short_message = $raw_event; # Avoids truncation of the short_message field.
	Exec $gl2_source_collector = 'd011c5ad-60df-4314-b7ea-736a39ef720f';
</Output>

<Route route-0>
  Path 581720cf88a523060108547c => 5817209c88a5230601085447
</Route>
```

**Comment by mariussturm** [comment]
The hostname field will be optional in Graylog 2.2: https://github.com/Graylog2/collector-sidecar/commit/840d51b4bfee6860ece749a08f42109486312264 and https://github.com/Graylog2/graylog-plugin-collector/commit/a13b0411121601c5a8a3c8cb26d83ec91ca58b19
