### ISSUE TITLE
SysV (Redhat/CentOS 6) init script can lead to multiple processes running

### ISSUE THREAD

**Issue by jessecarbon** [Graylog2/collector-sidecar#92]
### Problem description
This is actually a bug in the [`services` library](https://github.com/kardianos/service) used by Graylog. I've [opened a bug there](https://github.com/kardianos/service/issues/78), but figured I would document it here as well.

The init script generated by `graylog-collector-sidecar -service install` does not create, or look for consistently named PID files. This can lead to multiple processes running if you try restarting `collector-sidecar` after it was initially started on boot.

### Steps to reproduce the problem

1. As per the [official Graylog documentation](http://docs.graylog.org/en/2.1/pages/collector_sidecar.html#id3), install the `collector-sidecar` RPM for Red Hat/CentOS 6
1. Generate the init script with `graylog-collector-sidecar -service install`
1. RHEL/CentOS 6 does not use systemd, so create the startup symlinks with `chkconfig --add collector-sidecar`
1. Restart the server and notice when the server is back up, the PID file is `/var/run/S99collector-sidecar.pid` (or similar priority)
1. Try to restart the service and notice it says the service is not running, so it starts it:
```
# service collector-sidecar restart
Not running
Starting collector-sidecar
```

There are now two collectors running:
```
# ps -ef | grep -i graylog
root      2819     1  0 15:58 ?        00:00:00 /usr/bin/graylog-collector-sidecar
root      2896  2819  0 15:58 ?        00:00:00 /usr/bin/filebeat -c /etc/graylog/collector-sidecar/generated/filebeat.yml
root      3070     1  0 16:00 pts/0    00:00:00 /usr/bin/graylog-collector-sidecar
root      3104  3070  0 16:00 pts/0    00:00:00 /usr/bin/filebeat -c /etc/graylog/collector-sidecar/generated/filebeat.yml
```
and 2 PID files:
```
# ls -lh /var/run/*collector*
-rw-r--r--. 1 root root 5 Nov  2 16:00 /var/run/collector-sidecar.pid
-rw-r--r--. 1 root root 5 Nov  2 15:58 /var/run/S99collector-sidecar.pid
```

See the bug in the `service` library for more information - https://github.com/kardianos/service/issues/78

### Environment

* Sidecar Version: 0.0.9-1
* Graylog Version: 2.1.1
* Operating System: CentOS release 6.8 (Final)

**Comment by mariussturm** [comment]
Thanks!

**Comment by jalogisch** [comment]
already fixed
