### ISSUE TITLE
winlogbeat reports always NULL for Application log messages on Windows

### ISSUE THREAD

**Issue by o1e9** [Graylog2/collector-sidecar#97]
### Problem description

It seems **winlogbeat** on Windows has an issue to read Application log messages.  It reports _NULL_ for all messages instead of fetch message details.  As a result all Application message in Graylog are _NULL_ with relatively no details.

### Steps to reproduce the problem

1. Install Sidecar with **winlogbeat** backend for Windows logs.
1. Monitor incoming message in Graylog input stream for messages from <code>winlogbeat_log_name: Application</code>.
1. All <code>winlogbeat_log_name: Application</code> messages comes with _NULL_ message and almost no details about.

### Environment

* Sidecar Version: 0.1.0 beta1 64bit
* Graylog Version: 2.1.2
* Operating System: CentOS7.2 for Graylog, Windows Server 2008R2 for sidecar/winlogbeat
* Elasticsearch Version: 2.4.1
* MongoDB Version: 3.2.10

**Comment by mariussturm** [comment]
Wouldn't this be an issue for Winlogbeat itself rather than the Sidecar?

**Comment by o1e9** [comment]
Hmmm, you are right, it looks like Beat issue rather Sidecar.

**Comment by o1e9** [comment]
So waiting for Beat 5.0.0?

**Comment by mariussturm** [comment]
Guess this should work with 1.x as well, you can ask the Elastic guys. PLease create here another ticket in case something is wrong with the rendered configuration.
