### ISSUE TITLE
Restart sidecar via systemctl times out

### ISSUE THREAD

**Issue by bernd** [Graylog2/collector-sidecar#99]
### Problem description

When trying to restart the sidecar via `systemctl restart collector-sidecar.service` it takes a really long time until the process gets restarted.

The systemd logs for the unit show that it runs into a timeout.

```
Nov 09 16:21:18 dev-demo-2 systemd[1]: Stopping Wrapper service for Graylog controlled collector...
[...]
Nov 09 16:22:48 dev-demo-2 systemd[1]: collector-sidecar.service: State 'stop-sigterm' timed out. Killing.
Nov 09 16:22:48 dev-demo-2 systemd[1]: collector-sidecar.service: Main process exited, code=killed, status=9/KILL
Nov 09 16:22:48 dev-demo-2 systemd[1]: Stopped Wrapper service for Graylog controlled collector.
Nov 09 16:22:48 dev-demo-2 systemd[1]: collector-sidecar.service: Unit entered failed state.
Nov 09 16:22:48 dev-demo-2 systemd[1]: collector-sidecar.service: Failed with result 'signal'.
Nov 09 16:22:48 dev-demo-2 systemd[1]: Started Wrapper service for Graylog controlled collector.
```

### Steps to reproduce the problem

1. Install sidecar on a Linux distribution with systemd (e.g. Ubuntu 16.04 LTS)
2. Install service via `graylog-collector-sidecar -service install`
3. Add some configuration in the collector web UI
4. Restart the sidecar via `systemctl restart collector-sidecar.service`

### Environment

* Sidecar Version: 5e577167b55db1bdd4d99c05cacfe0d2fe13593a
* Graylog Version: Graylog 2.2.0-alpha.5-SNAPSHOT+292ec02
* Operating System: Ubuntu 16.04 LTS

**Comment by mariussturm** [comment]
Fixed via #107
